libcopp: copp::util::details Namespace Reference
copp::util::details Namespace Reference
Data Structures
struct uint64_id_allocator_tls_cache_t
Functions
static uint64_t allocate_id_by_atomic ()
uint64_id_allocator_tls_cache_t * get_uint64_id_allocator_tls_cache ()
Function Documentation
allocate_id_by_atomic()
static uint64_t copp::util::details::allocate_id_by_atomic () static
Definition at line 16 of file uint64_id_allocator.cpp.
References libcopp::util::lock::atomic_int_type< Ty >::compare_exchange_strong(), libcopp::util::lock::atomic_int_type< Ty >::compare_exchange_weak(), libcopp::util::lock::atomic_int_type< Ty >::load(), libcopp::util::lock::memory_order_acq_rel, and libcopp::util::lock::memory_order_acquire.
Referenced by copp::util::uint64_id_allocator::allocate().
get_uint64_id_allocator_tls_cache()
uint64_id_allocator_tls_cache_t* copp::util::details::get_uint64_id_allocator_tls_cache ()
Definition at line 102 of file uint64_id_allocator.cpp.
Referenced by copp::util::uint64_id_allocator::allocate().