libcopp: copp::future::context_t< void > Class Template Reference
copp::future::context_t< void > Class Template Reference
context_t<void>
#include <context.h>
Data Structures
struct construct_helper_t
struct poll_event_data_t
Public Types
typedef context_t< void > self_type
typedef std::function< void(self_type &)> wake_fn_t
typedef std::function< void(self_type &, poll_event_data_t)> poll_fn_t
typedef void * value_type
Public Member Functions
context_t ()
template<class TFIRST , class... TARGS>
context_t (TFIRST &&helper, TARGS &&...)
~context_t ()
template<class TCONTEXT , class TFUTURE >
void poll_as (TFUTURE &&fut)
void wake ()
void set_poll_fn (poll_fn_t fn)
const poll_fn_t & get_poll_fn () const LIBCOPP_MACRO_NOEXCEPT
poll_fn_t & get_poll_fn () LIBCOPP_MACRO_NOEXCEPT
void set_wake_fn (wake_fn_t fn)
const wake_fn_t & get_wake_fn () const LIBCOPP_MACRO_NOEXCEPT
wake_fn_t & get_wake_fn () LIBCOPP_MACRO_NOEXCEPT
void set_on_destroy (wake_fn_t fn)
const wake_fn_t & get_on_destroy () const LIBCOPP_MACRO_NOEXCEPT
wake_fn_t & get_on_destroy () LIBCOPP_MACRO_NOEXCEPT
void set_private_data (void *ptr)
void * get_private_data () LIBCOPP_MACRO_NOEXCEPT
const void * get_private_data () const LIBCOPP_MACRO_NOEXCEPT
Static Public Member Functions
template<class U >
static construct_helper_t construct (U &&fn, void *ptr=NULL)
Private Member Functions
context_t (const context_t &) UTIL_CONFIG_DELETED_FUNCTION
context_t & operator= (const context_t &) UTIL_CONFIG_DELETED_FUNCTION
context_t (context_t &&) UTIL_CONFIG_DELETED_FUNCTION
context_t & operator= (context_t &&) UTIL_CONFIG_DELETED_FUNCTION
Private Attributes
value_type private_data_
context_event_function_t< wake_fn_t > wake_fn_
context_event_function_t< poll_fn_t > poll_fn_
context_event_function_t< wake_fn_t > on_destroy_fn_
Detailed Description
template<>
class copp::future::context_t< void >
context_t<void>
Note
pool_fn(self_type&, poll_event_data_t) will be called with pool_fn(*this, {&out, private_data_}) when related event state changes, and the "out" must be set if the action is ready
Definition at line 148 of file context.h.
Member Typedef Documentation
poll_fn_t
typedef std::function<void(self_type &, poll_event_data_t)> copp::future::context_t< void >::poll_fn_t
Definition at line 157 of file context.h.
self_type
typedef context_t<void> copp::future::context_t< void >::self_type
Definition at line 155 of file context.h.
value_type
typedef void* copp::future::context_t< void >::value_type
Definition at line 158 of file context.h.
wake_fn_t
typedef std::function<void(self_type &)> copp::future::context_t< void >::wake_fn_t
Definition at line 156 of file context.h.
Constructor & Destructor Documentation
context_t() [1/4]
copp::future::context_t< void >::context_t (const context_t< void > &) private
context_t() [2/4]
copp::future::context_t< void >::context_t (context_t< void > &&) private
context_t() [3/4]
copp::future::context_t< void >::context_t () inline
Definition at line 181 of file context.h.
context_t() [4/4]
template<class TFIRST , class... TARGS> copp::future::context_t< void >::context_t (TFIRST && helper, TARGS && ...) inline
Definition at line 183 of file context.h.
References util::cli::phoenix::assign().
~context_t()
copp::future::context_t< void >::~context_t () inline
Definition at line 188 of file context.h.
Member Function Documentation
construct()
template<class U > static construct_helper_t copp::future::context_t< void >::construct (U && fn, void * ptr = NULL) inline static
Definition at line 177 of file context.h.
get_on_destroy() [1/2]
const wake_fn_t& copp::future::context_t< void >::get_on_destroy () const inline
Definition at line 215 of file context.h.
get_on_destroy() [2/2]
wake_fn_t& copp::future::context_t< void >::get_on_destroy () inline
Definition at line 216 of file context.h.
get_poll_fn() [1/2]
const poll_fn_t& copp::future::context_t< void >::get_poll_fn () const inline
Definition at line 207 of file context.h.
get_poll_fn() [2/2]
poll_fn_t& copp::future::context_t< void >::get_poll_fn () inline
Definition at line 208 of file context.h.
get_private_data() [1/2]
void* copp::future::context_t< void >::get_private_data () inline
Definition at line 219 of file context.h.
get_private_data() [2/2]
const void* copp::future::context_t< void >::get_private_data () const inline
Definition at line 220 of file context.h.
get_wake_fn() [1/2]
const wake_fn_t& copp::future::context_t< void >::get_wake_fn () const inline
Definition at line 211 of file context.h.
get_wake_fn() [2/2]
wake_fn_t& copp::future::context_t< void >::get_wake_fn () inline
Definition at line 212 of file context.h.
operator=() [1/2]
context_t& copp::future::context_t< void >::operator= (const context_t< void > &) private
operator=() [2/2]
context_t& copp::future::context_t< void >::operator= (context_t< void > &&) private
poll_as()
template<class TCONTEXT , class TFUTURE > void copp::future::context_t< void >::poll_as (TFUTURE && fut) inline
Definition at line 193 of file context.h.
set_on_destroy()
void copp::future::context_t< void >::set_on_destroy (wake_fn_t fn) inline
Definition at line 214 of file context.h.
Referenced by test_future_void_context_poll_functor< void >::operator()(), and test_future_void_context_poll_functor< T >::operator()().
set_poll_fn()
void copp::future::context_t< void >::set_poll_fn (poll_fn_t fn) inline
Definition at line 206 of file context.h.
set_private_data()
void copp::future::context_t< void >::set_private_data (void * ptr) inline
Definition at line 218 of file context.h.
Referenced by run_with_void_context().
set_wake_fn()
void copp::future::context_t< void >::set_wake_fn (wake_fn_t fn) inline
Definition at line 210 of file context.h.
wake()
void copp::future::context_t< void >::wake () inline
Definition at line 204 of file context.h.
Referenced by run_with_void_context().
Field Documentation
on_destroy_fn_
context_event_function_t<wake_fn_t> copp::future::context_t< void >::on_destroy_fn_ private
Definition at line 226 of file context.h.
poll_fn_
context_event_function_t<poll_fn_t> copp::future::context_t< void >::poll_fn_ private
Definition at line 225 of file context.h.
private_data_
value_type copp::future::context_t< void >::private_data_ private
Definition at line 223 of file context.h.
wake_fn_
context_event_function_t<wake_fn_t> copp::future::context_t< void >::wake_fn_ private
Definition at line 224 of file context.h.
The documentation for this class was generated from the following file:
/home/travis/build/owt5008137/libcopp/include/libcopp/future/context.h