libcopp: libcopp::util Namespace Reference
libcopp::util Namespace Reference
Namespaces
lock
Data Structures
class intrusive_ptr
Functions
template<typename T , typename U >
bool operator== (intrusive_ptr< T > const &a, intrusive_ptr< U > const &b) LIBCOPP_MACRO_NOEXCEPT
template<typename T , typename U >
bool operator== (intrusive_ptr< T > const &a, U *b) LIBCOPP_MACRO_NOEXCEPT
template<typename T , typename U >
bool operator== (T *a, intrusive_ptr< U > const &b) LIBCOPP_MACRO_NOEXCEPT
template<typename T , typename U >
bool operator!= (intrusive_ptr< T > const &a, intrusive_ptr< U > const &b) LIBCOPP_MACRO_NOEXCEPT
template<typename T , typename U >
bool operator!= (intrusive_ptr< T > const &a, U *b) LIBCOPP_MACRO_NOEXCEPT
template<typename T , typename U >
bool operator!= (T *a, intrusive_ptr< U > const &b) LIBCOPP_MACRO_NOEXCEPT
template<typename T , typename U >
bool operator< (intrusive_ptr< T > const &a, intrusive_ptr< U > const &b) LIBCOPP_MACRO_NOEXCEPT
template<typename T , typename U >
bool operator< (intrusive_ptr< T > const &a, U *b) LIBCOPP_MACRO_NOEXCEPT
template<typename T , typename U >
bool operator< (T *a, intrusive_ptr< U > const &b) LIBCOPP_MACRO_NOEXCEPT
template<typename T , typename U >
bool operator<= (intrusive_ptr< T > const &a, intrusive_ptr< U > const &b) LIBCOPP_MACRO_NOEXCEPT
template<typename T , typename U >
bool operator<= (intrusive_ptr< T > const &a, U *b) LIBCOPP_MACRO_NOEXCEPT
template<typename T , typename U >
bool operator<= (T *a, intrusive_ptr< U > const &b) LIBCOPP_MACRO_NOEXCEPT
template<typename T , typename U >
bool operator> (intrusive_ptr< T > const &a, intrusive_ptr< U > const &b) LIBCOPP_MACRO_NOEXCEPT
template<typename T , typename U >
bool operator> (intrusive_ptr< T > const &a, U *b) LIBCOPP_MACRO_NOEXCEPT
template<typename T , typename U >
bool operator> (T *a, intrusive_ptr< U > const &b) LIBCOPP_MACRO_NOEXCEPT
template<typename T , typename U >
bool operator>= (intrusive_ptr< T > const &a, intrusive_ptr< U > const &b) LIBCOPP_MACRO_NOEXCEPT
template<typename T , typename U >
bool operator>= (intrusive_ptr< T > const &a, U *b) LIBCOPP_MACRO_NOEXCEPT
template<typename T , typename U >
bool operator>= (T *a, intrusive_ptr< U > const &b) LIBCOPP_MACRO_NOEXCEPT
template<typename T >
void swap (intrusive_ptr< T > &lhs, intrusive_ptr< T > &rhs)
template<typename T >
T * get_pointer (intrusive_ptr< T > const &p)
template<typename T , typename U >
intrusive_ptr< T > static_pointer_cast (intrusive_ptr< U > const &p)
template<typename T , typename U >
intrusive_ptr< T > const_pointer_cast (intrusive_ptr< U > const &p)
template<typename E , typename T , typename Y >
std::basic_ostream< E, T > & operator<< (std::basic_ostream< E, T > &os, intrusive_ptr< Y > const &p)
Function Documentation
const_pointer_cast()
template<typename T , typename U > intrusive_ptr<T> libcopp::util::const_pointer_cast (intrusive_ptr< U > const & p)
Definition at line 364 of file intrusive_ptr.h.
References libcopp::util::intrusive_ptr< T >::get().
get_pointer()
template<typename T > T* libcopp::util::get_pointer (intrusive_ptr< T > const & p)
Definition at line 354 of file intrusive_ptr.h.
References libcopp::util::intrusive_ptr< T >::get().
operator!=() [1/3]
template<typename T , typename U > bool libcopp::util::operator!= (intrusive_ptr< T > const & a, intrusive_ptr< U > const & b) inline
Definition at line 194 of file intrusive_ptr.h.
operator!=() [2/3]
template<typename T , typename U > bool libcopp::util::operator!= (intrusive_ptr< T > const & a, U * b) inline
Definition at line 199 of file intrusive_ptr.h.
operator!=() [3/3]
template<typename T , typename U > bool libcopp::util::operator!= (T * a, intrusive_ptr< U > const & b) inline
Definition at line 204 of file intrusive_ptr.h.
operator<() [1/3]
template<typename T , typename U > bool libcopp::util::operator< (intrusive_ptr< T > const & a, intrusive_ptr< U > const & b) inline
Definition at line 209 of file intrusive_ptr.h.
operator<() [2/3]
template<typename T , typename U > bool libcopp::util::operator< (intrusive_ptr< T > const & a, U * b) inline
Definition at line 214 of file intrusive_ptr.h.
operator<() [3/3]
template<typename T , typename U > bool libcopp::util::operator< (T * a, intrusive_ptr< U > const & b) inline
Definition at line 219 of file intrusive_ptr.h.
operator<<()
template<typename E , typename T , typename Y > std::basic_ostream<E, T>& libcopp::util::operator<< (std::basic_ostream< E, T > & os, intrusive_ptr< Y > const & p)
Definition at line 377 of file intrusive_ptr.h.
References libcopp::util::intrusive_ptr< T >::get().
operator<=() [1/3]
template<typename T , typename U > bool libcopp::util::operator<= (intrusive_ptr< T > const & a, intrusive_ptr< U > const & b) inline
Definition at line 224 of file intrusive_ptr.h.
operator<=() [2/3]
template<typename T , typename U > bool libcopp::util::operator<= (intrusive_ptr< T > const & a, U * b) inline
Definition at line 229 of file intrusive_ptr.h.
operator<=() [3/3]
template<typename T , typename U > bool libcopp::util::operator<= (T * a, intrusive_ptr< U > const & b) inline
Definition at line 234 of file intrusive_ptr.h.
operator==() [1/3]
template<typename T , typename U > bool libcopp::util::operator== (intrusive_ptr< T > const & a, intrusive_ptr< U > const & b) inline
Definition at line 163 of file intrusive_ptr.h.
operator==() [2/3]
template<typename T , typename U > bool libcopp::util::operator== (intrusive_ptr< T > const & a, U * b) inline
Definition at line 168 of file intrusive_ptr.h.
operator==() [3/3]
template<typename T , typename U > bool libcopp::util::operator== (T * a, intrusive_ptr< U > const & b) inline
Definition at line 173 of file intrusive_ptr.h.
operator>() [1/3]
template<typename T , typename U > bool libcopp::util::operator> (intrusive_ptr< T > const & a, intrusive_ptr< U > const & b) inline
Definition at line 239 of file intrusive_ptr.h.
operator>() [2/3]
template<typename T , typename U > bool libcopp::util::operator> (intrusive_ptr< T > const & a, U * b) inline
Definition at line 244 of file intrusive_ptr.h.
operator>() [3/3]
template<typename T , typename U > bool libcopp::util::operator> (T * a, intrusive_ptr< U > const & b) inline
Definition at line 249 of file intrusive_ptr.h.
operator>=() [1/3]
template<typename T , typename U > bool libcopp::util::operator>= (intrusive_ptr< T > const & a, intrusive_ptr< U > const & b) inline
Definition at line 254 of file intrusive_ptr.h.
operator>=() [2/3]
template<typename T , typename U > bool libcopp::util::operator>= (intrusive_ptr< T > const & a, U * b) inline
Definition at line 259 of file intrusive_ptr.h.
operator>=() [3/3]
template<typename T , typename U > bool libcopp::util::operator>= (T * a, intrusive_ptr< U > const & b) inline
Definition at line 264 of file intrusive_ptr.h.
static_pointer_cast()
template<typename T , typename U > intrusive_ptr<T> libcopp::util::static_pointer_cast (intrusive_ptr< U > const & p)
Definition at line 359 of file intrusive_ptr.h.
References libcopp::util::intrusive_ptr< T >::get().
swap()
template<typename T > void libcopp::util::swap (intrusive_ptr< T > & lhs, intrusive_ptr< T > & rhs)
Definition at line 347 of file intrusive_ptr.h.
References libcopp::util::intrusive_ptr< T >::swap().
Referenced by CASE_TEST(), copp::allocator::stack_allocator_memory::operator=(), copp::future::result_base_t< TOK, TERR, false >::operator=(), copp::future::result_base_t< TOK, TERR, false >::result_base_t(), copp::allocator::stack_allocator_memory::stack_allocator_memory(), copp::coroutine_context::start(), copp::allocator::stack_allocator_memory::swap(), copp::future::poll_t< T, typename poll_storage_select_ptr_t< T >::type >::swap(), copp::future::poll_storage_base_t< T, TPTR >::swap(), copp::future::result_base_t< TOK, TERR, true >::swap(), and copp::future::result_base_t< TOK, TERR, false >::swap().