libcopp: cotask::task_manager< TTask, TTaskContainer > Class Template Reference
cotask::task_manager< TTask, TTaskContainer > Class Template Reference
task manager
#include <task_manager.h>
Data Structures
struct flag_guard_t
struct flag_t
Public Types
typedef TTask task_t
typedef TTaskContainer container_t
typedef task_t::id_t id_t
typedef task_t::ptr_t task_ptr_t
typedef task_manager< task_t, container_t > self_t
typedef std::shared_ptr< self_t > ptr_t
Public Member Functions
task_manager ()
~task_manager ()
void reset ()
int add_task (const task_ptr_t &task, time_t timeout_sec, int timeout_nsec)
add task to manager please make the task has method of get_id() and will return a unique id
int add_task (const task_ptr_t &task)
add task to manager please make the task has method of get_id() and will return a unique id
int set_timeout (id_t id, time_t timeout_sec, int timeout_nsec)
set or update task timeout
int remove_task (id_t id, const task_ptr_t &confirm_ptr)
remove task in this manager
int remove_task (id_t id)
remove task in this manager
int remove_task (id_t id, const task_t *confirm_ptr)
remove task in this manager
task_ptr_t find_task (id_t id)
find task by id
int start (id_t id, void *priv_data=NULL)
int resume (id_t id, void *priv_data=NULL)
int cancel (id_t id, void *priv_data=NULL)
int kill (id_t id, enum EN_TASK_STATUS status, void *priv_data=NULL)
int kill (id_t id, void *priv_data=NULL)
int tick (time_t sec, int nsec=0)
active tick event and deal with clock
size_t get_tick_checkpoint_size () const LIBCOPP_MACRO_NOEXCEPT
get timeout checkpoint number in this manager
size_t get_task_size () const LIBCOPP_MACRO_NOEXCEPT
get task number in this manager
detail::tickspec_t get_last_tick_time () const LIBCOPP_MACRO_NOEXCEPT
get last tick time
const container_t & get_container () const LIBCOPP_MACRO_NOEXCEPT
task container, this api is just used for provide information to users
const std::set< detail::task_timer_node< task_t > > & get_checkpoints () const LIBCOPP_MACRO_NOEXCEPT
get all task checkpoints, this api is just used for provide information to users
Static Public Member Functions
static ptr_t create ()
create a new task manager
Private Member Functions
void set_timeout_timer (detail::task_manager_node< task_t > &node, time_t timeout_sec, int timeout_nsec)
void remove_timeout_timer (detail::task_manager_node< task_t > &node)
Private Attributes
container_t tasks_
detail::tickspec_t last_tick_time_
std::set< detail::task_timer_node< task_t > > task_timeout_timer_
libcopp::util::lock::spin_lock action_lock_
int flags_
Detailed Description
template<typename TTask, typename TTaskContainer = std::map<typename TTask::id_t, detail::task_manager_node<TTask> >>
class cotask::task_manager< TTask, TTaskContainer >
task manager
Definition at line 154 of file task_manager.h.
Member Typedef Documentation
container_t
template<typename TTask , typename TTaskContainer = std::map<typename TTask::id_t, detail::task_manager_node<TTask> >> typedef TTaskContainer cotask::task_manager< TTask, TTaskContainer >::container_t
Definition at line 157 of file task_manager.h.
id_t
template<typename TTask , typename TTaskContainer = std::map<typename TTask::id_t, detail::task_manager_node<TTask> >> typedef task_t::id_t cotask::task_manager< TTask, TTaskContainer >::id_t
Definition at line 158 of file task_manager.h.
ptr_t
template<typename TTask , typename TTaskContainer = std::map<typename TTask::id_t, detail::task_manager_node<TTask> >> typedef std::shared_ptr<self_t> cotask::task_manager< TTask, TTaskContainer >::ptr_t
Definition at line 161 of file task_manager.h.
self_t
template<typename TTask , typename TTaskContainer = std::map<typename TTask::id_t, detail::task_manager_node<TTask> >> typedef task_manager<task_t, container_t> cotask::task_manager< TTask, TTaskContainer >::self_t
Definition at line 160 of file task_manager.h.
task_ptr_t
template<typename TTask , typename TTaskContainer = std::map<typename TTask::id_t, detail::task_manager_node<TTask> >> typedef task_t::ptr_t cotask::task_manager< TTask, TTaskContainer >::task_ptr_t
Definition at line 159 of file task_manager.h.
task_t
template<typename TTask , typename TTaskContainer = std::map<typename TTask::id_t, detail::task_manager_node<TTask> >> typedef TTask cotask::task_manager< TTask, TTaskContainer >::task_t
Definition at line 156 of file task_manager.h.
Constructor & Destructor Documentation
task_manager()
template<typename TTask , typename TTaskContainer = std::map<typename TTask::id_t, detail::task_manager_node<TTask> >> cotask::task_manager< TTask, TTaskContainer >::task_manager () inline
Definition at line 193 of file task_manager.h.
~task_manager()
template<typename TTask , typename TTaskContainer = std::map<typename TTask::id_t, detail::task_manager_node<TTask> >> cotask::task_manager< TTask, TTaskContainer >::~task_manager () inline
Definition at line 198 of file task_manager.h.
Member Function Documentation
add_task() [1/2]
template<typename TTask , typename TTaskContainer = std::map<typename TTask::id_t, detail::task_manager_node<TTask> >> int cotask::task_manager< TTask, TTaskContainer >::add_task (const task_ptr_t & task) inline
add task to manager please make the task has method of get_id() and will return a unique id
Parameters
task task to be inserted
Returns
0 or error code
Definition at line 319 of file task_manager.h.
References cotask::task_manager< TTask, TTaskContainer >::add_task().
Referenced by cotask::task_manager< TTask, TTaskContainer >::add_task().
add_task() [2/2]
template<typename TTask , typename TTaskContainer = std::map<typename TTask::id_t, detail::task_manager_node<TTask> >> int cotask::task_manager< TTask, TTaskContainer >::add_task (const task_ptr_t & task, time_t timeout_sec, int timeout_nsec) inline
add task to manager please make the task has method of get_id() and will return a unique id
Parameters
task task to be inserted
timeout_sec timeout in second (unix time stamp recommanded)
timeout_nsec timeout in nanosecond (must be in the range 0-999999999)
Returns
0 or error code
Note
if a task added before the first calling of tick method, the timeout will be set releative to the first calling time of tick method
See also
tick
Definition at line 255 of file task_manager.h.
References copp::COPP_EC_ALREADY_EXIST, copp::COPP_EC_ARGS_ERROR, copp::COPP_EC_CAST_FAILED, copp::COPP_EC_EXTERNAL_INSERT_FAILED, copp::COPP_EC_IN_RESET, copp::COPP_EC_SUCCESS, copp::COPP_EC_TASK_ALREADY_IN_ANOTHER_MANAGER, copp::COPP_EC_TASK_IS_EXITING, cotask::impl::task_impl::get_id(), cotask::impl::task_impl::is_exiting(), cotask::detail::task_manager_node< TTask >::task_, and cotask::detail::task_manager_node< TTask >::timer_node.
cancel()
template<typename TTask , typename TTaskContainer = std::map<typename TTask::id_t, detail::task_manager_node<TTask> >> int cotask::task_manager< TTask, TTaskContainer >::cancel (id_t id, void * priv_data = NULL) inline
Definition at line 548 of file task_manager.h.
References copp::COPP_EC_IN_RESET, and copp::COPP_EC_NOT_FOUND.
create()
template<typename TTask , typename TTaskContainer = std::map<typename TTask::id_t, detail::task_manager_node<TTask> >> static ptr_t cotask::task_manager< TTask, TTaskContainer >::create () inline static
create a new task manager
Returns
smart pointer of task manager
Definition at line 240 of file task_manager.h.
find_task()
template<typename TTask , typename TTaskContainer = std::map<typename TTask::id_t, detail::task_manager_node<TTask> >> task_ptr_t cotask::task_manager< TTask, TTaskContainer >::find_task (id_t id) inline
find task by id
Parameters
id task id
Returns
smart pointer of task
Definition at line 423 of file task_manager.h.
get_checkpoints()
template<typename TTask , typename TTaskContainer = std::map<typename TTask::id_t, detail::task_manager_node<TTask> >> const std::set<detail::task_timer_node<task_t> >& cotask::task_manager< TTask, TTaskContainer >::get_checkpoints () const inline
get all task checkpoints, this api is just used for provide information to users
Returns
task checkpoints
Definition at line 774 of file task_manager.h.
get_container()
template<typename TTask , typename TTaskContainer = std::map<typename TTask::id_t, detail::task_manager_node<TTask> >> const container_t& cotask::task_manager< TTask, TTaskContainer >::get_container () const inline
task container, this api is just used for provide information to users
Returns
task container
Definition at line 768 of file task_manager.h.
get_last_tick_time()
template<typename TTask , typename TTaskContainer = std::map<typename TTask::id_t, detail::task_manager_node<TTask> >> detail::tickspec_t cotask::task_manager< TTask, TTaskContainer >::get_last_tick_time () const inline
get last tick time
Returns
last tick time
Definition at line 762 of file task_manager.h.
get_task_size()
template<typename TTask , typename TTaskContainer = std::map<typename TTask::id_t, detail::task_manager_node<TTask> >> size_t cotask::task_manager< TTask, TTaskContainer >::get_task_size () const inline
get task number in this manager
Returns
task number
Definition at line 756 of file task_manager.h.
get_tick_checkpoint_size()
template<typename TTask , typename TTaskContainer = std::map<typename TTask::id_t, detail::task_manager_node<TTask> >> size_t cotask::task_manager< TTask, TTaskContainer >::get_tick_checkpoint_size () const inline
get timeout checkpoint number in this manager
Returns
checkpoint number
Definition at line 750 of file task_manager.h.
kill() [1/2]
template<typename TTask , typename TTaskContainer = std::map<typename TTask::id_t, detail::task_manager_node<TTask> >> int cotask::task_manager< TTask, TTaskContainer >::kill (id_t id, enum EN_TASK_STATUS status, void * priv_data = NULL) inline
Definition at line 599 of file task_manager.h.
References copp::COPP_EC_IN_RESET, and copp::COPP_EC_NOT_FOUND.
kill() [2/2]
template<typename TTask , typename TTaskContainer = std::map<typename TTask::id_t, detail::task_manager_node<TTask> >> int cotask::task_manager< TTask, TTaskContainer >::kill (id_t id, void * priv_data = NULL) inline
Definition at line 639 of file task_manager.h.
References cotask::EN_TS_KILLED, and cotask::task_manager< TTask, TTaskContainer >::kill().
Referenced by cotask::task_manager< TTask, TTaskContainer >::kill().
remove_task() [1/3]
template<typename TTask , typename TTaskContainer = std::map<typename TTask::id_t, detail::task_manager_node<TTask> >> int cotask::task_manager< TTask, TTaskContainer >::remove_task (id_t id) inline
remove task in this manager
Parameters
id task id
Returns
0 or error code
Definition at line 368 of file task_manager.h.
References cotask::task_manager< TTask, TTaskContainer >::remove_task().
Referenced by cotask::task_manager< TTask, TTaskContainer >::remove_task().
remove_task() [2/3]
template<typename TTask , typename TTaskContainer = std::map<typename TTask::id_t, detail::task_manager_node<TTask> >> int cotask::task_manager< TTask, TTaskContainer >::remove_task (id_t id, const task_ptr_t & confirm_ptr) inline
remove task in this manager
Parameters
id task id
confirm_ptr check task ptr before just remove by id
Returns
0 or error code
Definition at line 361 of file task_manager.h.
References cotask::task_manager< TTask, TTaskContainer >::remove_task().
Referenced by cotask::task_manager< TTask, TTaskContainer >::remove_task().
remove_task() [3/3]
template<typename TTask , typename TTaskContainer = std::map<typename TTask::id_t, detail::task_manager_node<TTask> >> int cotask::task_manager< TTask, TTaskContainer >::remove_task (id_t id, const task_t * confirm_ptr) inline
remove task in this manager
Parameters
id task id
confirm_ptr check task ptr before just remove by id
Returns
0 or error code
Definition at line 376 of file task_manager.h.
References copp::COPP_EC_IN_RESET, copp::COPP_EC_NOT_FOUND, copp::COPP_EC_SUCCESS, cotask::EN_TS_CREATED, cotask::EN_TS_DONE, and cotask::EN_TS_KILLED.
remove_timeout_timer()
template<typename TTask , typename TTaskContainer = std::map<typename TTask::id_t, detail::task_manager_node<TTask> >> void cotask::task_manager< TTask, TTaskContainer >::remove_timeout_timer (detail::task_manager_node< task_t > & node) inline private
Definition at line 802 of file task_manager.h.
References cotask::detail::task_manager_node< TTask >::timer_node.
reset()
template<typename TTask , typename TTaskContainer = std::map<typename TTask::id_t, detail::task_manager_node<TTask> >> void cotask::task_manager< TTask, TTaskContainer >::reset () inline
Definition at line 203 of file task_manager.h.
References cotask::EN_TS_KILLED.
resume()
template<typename TTask , typename TTaskContainer = std::map<typename TTask::id_t, detail::task_manager_node<TTask> >> int cotask::task_manager< TTask, TTaskContainer >::resume (id_t id, void * priv_data = NULL) inline
Definition at line 500 of file task_manager.h.
References copp::COPP_EC_IN_RESET, copp::COPP_EC_NOT_FOUND, and cotask::EN_TS_DONE.
set_timeout()
template<typename TTask , typename TTaskContainer = std::map<typename TTask::id_t, detail::task_manager_node<TTask> >> int cotask::task_manager< TTask, TTaskContainer >::set_timeout (id_t id, time_t timeout_sec, int timeout_nsec) inline
set or update task timeout
Parameters
id task id of which should be already added into this manager
timeout_sec timeout in second (unix time stamp recommanded)
timeout_nsec timeout in nanosecond (must be in the range 0-999999999)
Returns
0 or error code
Note
if a task added before the first calling of tick method, the timeout will be set releative to the first calling time of tick method
this function can be call multiply times, we will use the last timeout. set_timeout(TASK_ID, 0, 0) means the task with TASK_ID will never expire.
See also
tick
Definition at line 335 of file task_manager.h.
References copp::COPP_EC_IN_RESET, copp::COPP_EC_NOT_FOUND, and copp::COPP_EC_SUCCESS.
set_timeout_timer()
template<typename TTask , typename TTaskContainer = std::map<typename TTask::id_t, detail::task_manager_node<TTask> >> void cotask::task_manager< TTask, TTaskContainer >::set_timeout_timer (detail::task_manager_node< task_t > & node, time_t timeout_sec, int timeout_nsec) inline private
Definition at line 779 of file task_manager.h.
References cotask::detail::task_timer_node< TTask >::expired_time, cotask::detail::task_manager_node< TTask >::task_, cotask::detail::task_timer_node< TTask >::task_id, cotask::detail::task_manager_node< TTask >::timer_node, cotask::detail::tickspec_t::tv_nsec, and cotask::detail::tickspec_t::tv_sec.
start()
template<typename TTask , typename TTaskContainer = std::map<typename TTask::id_t, detail::task_manager_node<TTask> >> int cotask::task_manager< TTask, TTaskContainer >::start (id_t id, void * priv_data = NULL) inline
Definition at line 452 of file task_manager.h.
References copp::COPP_EC_IN_RESET, copp::COPP_EC_NOT_FOUND, and cotask::EN_TS_DONE.
tick()
template<typename TTask , typename TTaskContainer = std::map<typename TTask::id_t, detail::task_manager_node<TTask> >> int cotask::task_manager< TTask, TTaskContainer >::tick (time_t sec, int nsec = 0) inline
active tick event and deal with clock
Parameters
sec current time in second (unix time stamp recommanded)
nsec current time in nanosecond (must be in the range 0-999999999)
Returns
0 or error code
Note
timeout tasks will be removed here
Definition at line 649 of file task_manager.h.
References copp::COPP_EC_IN_RESET, copp::COPP_EC_SUCCESS, cotask::EN_TS_TIMEOUT, cotask::detail::task_timer_node< TTask >::expired_time, set(), cotask::detail::tickspec_t::tv_nsec, and cotask::detail::tickspec_t::tv_sec.
Field Documentation
action_lock_
template<typename TTask , typename TTaskContainer = std::map<typename TTask::id_t, detail::task_manager_node<TTask> >> libcopp::util::lock::spin_lock cotask::task_manager< TTask, TTaskContainer >::action_lock_ private
Definition at line 825 of file task_manager.h.
flags_
template<typename TTask , typename TTaskContainer = std::map<typename TTask::id_t, detail::task_manager_node<TTask> >> int cotask::task_manager< TTask, TTaskContainer >::flags_ private
Definition at line 827 of file task_manager.h.
last_tick_time_
template<typename TTask , typename TTaskContainer = std::map<typename TTask::id_t, detail::task_manager_node<TTask> >> detail::tickspec_t cotask::task_manager< TTask, TTaskContainer >::last_tick_time_ private
Definition at line 821 of file task_manager.h.
task_timeout_timer_
template<typename TTask , typename TTaskContainer = std::map<typename TTask::id_t, detail::task_manager_node<TTask> >> std::set<detail::task_timer_node<task_t> > cotask::task_manager< TTask, TTaskContainer >::task_timeout_timer_ private
Definition at line 822 of file task_manager.h.
tasks_
template<typename TTask , typename TTaskContainer = std::map<typename TTask::id_t, detail::task_manager_node<TTask> >> container_t cotask::task_manager< TTask, TTaskContainer >::tasks_ private
Definition at line 820 of file task_manager.h.
The documentation for this class was generated from the following file:
/home/runner/work/libcopp/libcopp/include/libcotask/task_manager.h