libcopp: copp::allocator::stack_allocator_malloc Class Reference
copp::allocator::stack_allocator_malloc Class Reference
memory allocator this allocator will maintain buffer using malloc/free function
#include <stack_allocator_malloc.h>
Public Member Functions
stack_allocator_malloc () LIBCOPP_MACRO_NOEXCEPT
~stack_allocator_malloc ()
stack_allocator_malloc (const stack_allocator_malloc &other) LIBCOPP_MACRO_NOEXCEPT
stack_allocator_malloc & operator= (const stack_allocator_malloc &other) LIBCOPP_MACRO_NOEXCEPT
void allocate (stack_context &ctx, std::size_t size) LIBCOPP_MACRO_NOEXCEPT
void deallocate (stack_context &ctx) LIBCOPP_MACRO_NOEXCEPT
Detailed Description
memory allocator this allocator will maintain buffer using malloc/free function
Definition at line 25 of file stack_allocator_malloc.h.
Constructor & Destructor Documentation
stack_allocator_malloc() [1/2]
LIBCOPP_COPP_API copp::allocator::stack_allocator_malloc::stack_allocator_malloc ()
Definition at line 26 of file stack_allocator_malloc.cpp.
Referenced by operator=().
~stack_allocator_malloc()
LIBCOPP_COPP_API copp::allocator::stack_allocator_malloc::~stack_allocator_malloc ()
Definition at line 27 of file stack_allocator_malloc.cpp.
stack_allocator_malloc() [2/2]
LIBCOPP_COPP_API copp::allocator::stack_allocator_malloc::stack_allocator_malloc (const stack_allocator_malloc & other)
Definition at line 28 of file stack_allocator_malloc.cpp.
Member Function Documentation
allocate()
LIBCOPP_COPP_API void copp::allocator::stack_allocator_malloc::allocate (stack_context & ctx, std::size_t size)
allocate memory and attach to stack context [standard function]
Parameters
ctx stack context
size stack size
Note
size must less or equal than attached
Definition at line 39 of file stack_allocator_malloc.cpp.
References copp::stack_traits::maximum_size(), copp::stack_traits::minimum_size(), and copp::stack_traits::round_to_page_size().
deallocate()
LIBCOPP_COPP_API void copp::allocator::stack_allocator_malloc::deallocate (stack_context & ctx)
deallocate memory from stack context [standard function]
Parameters
ctx stack context
Definition at line 60 of file stack_allocator_malloc.cpp.
References copp::stack_traits::is_unbounded(), copp::stack_traits::maximum_size(), and copp::stack_traits::minimum_size().
operator=()
LIBCOPP_COPP_API stack_allocator_malloc & copp::allocator::stack_allocator_malloc::operator= (const stack_allocator_malloc & other)
Definition at line 29 of file stack_allocator_malloc.cpp.
References LIBCOPP_COPP_API, LIBCOPP_MACRO_NOEXCEPT, and stack_allocator_malloc().
The documentation for this class was generated from the following files:
/home/travis/build/owt5008137/libcopp/include/libcopp/stack/allocator/stack_allocator_malloc.h
/home/travis/build/owt5008137/libcopp/src/libcopp/stack/allocator/stack_allocator_malloc.cpp