libcopp: copp Namespace Reference
copp Namespace Reference
Namespaces
allocator
detail
details
fcontext
future
this_coroutine
type_traits
util
Data Structures
class coroutine_context
base type of all coroutine context
class coroutine_context_base
base type of all coroutine context
class coroutine_context_container
coroutine container contain stack context, stack allocator and runtime fcontext
struct libcopp_inner_api_helper
struct stack_context
class stack_pool
struct stack_traits
Typedefs
typedef coroutine_context_container< allocator::default_statck_allocator > coroutine_context_default
Enumerations
enum copp_error_code {
COPP_EC_SUCCESS = 0, COPP_EC_UNKNOWN = -101, COPP_EC_EXTERNAL_INSERT_FAILED = -102, COPP_EC_EXTERNAL_ERASE_FAILED = -103,
COPP_EC_IN_RESET = -104, COPP_EC_ALLOC_STACK_FAILED = -201, COPP_EC_NOT_INITED = -1001, COPP_EC_ALREADY_INITED = -1002,
COPP_EC_ACCESS_VIOLATION = -1003, COPP_EC_NOT_READY = -1004, COPP_EC_NOT_RUNNING = -1005, COPP_EC_IS_RUNNING = -1006,
COPP_EC_ALREADY_FINISHED = -1007, COPP_EC_NOT_FOUND = -1008, COPP_EC_ALREADY_EXIST = -1009, COPP_EC_ARGS_ERROR = -1010,
COPP_EC_CAST_FAILED = -1011, COPP_EC_HAS_UNHANDLE_EXCEPTION = -1012, COPP_EC_FCONTEXT_MAKE_FAILED = -2001, COPP_EC_CAN_NOT_USE_CROSS_FCONTEXT_AND_FIBER = -2002,
COPP_EC_TASK_CAN_NOT_WAIT_SELF = -3001, COPP_EC_TASK_IS_EXITING = -3002, COPP_EC_TASK_ADD_NEXT_FAILED = -3003, COPP_EC_TASK_NOT_IN_ACTION = -3004,
COPP_EC_TASK_ALREADY_IN_ANOTHER_MANAGER = -3005
}
Functions
static void jump_to (fcontext::fcontext_t &to_fctx, EXPLICIT_UNUSED_ATTR stack_context &from_sctx, EXPLICIT_UNUSED_ATTR stack_context &to_sctx, libcopp_inner_api_helper::jump_src_data_t &jump_transfer) LIBCOPP_MACRO_NOEXCEPT
call platform jump to asm instruction
Detailed Description
coroutine context container
Typedef Documentation
coroutine_context_default
typedef coroutine_context_container<allocator::default_statck_allocator> copp::coroutine_context_default
Definition at line 211 of file coroutine_context_container.h.
Enumeration Type Documentation
copp_error_code
enum copp::copp_error_code
error code
Enumerator
COPP_EC_SUCCESS
COPP_EC_SUCCESS.
COPP_EC_UNKNOWN
COPP_EC_UNKNOWN.
COPP_EC_EXTERNAL_INSERT_FAILED
COPP_EC_EXTERNAL_INSERT_FAILED.
COPP_EC_EXTERNAL_ERASE_FAILED
COPP_EC_EXTERNAL_ERASE_FAILED.
COPP_EC_IN_RESET
COPP_EC_IN_RESET.
COPP_EC_ALLOC_STACK_FAILED
COPP_EC_ALLOC_STACK_FAILED.
COPP_EC_NOT_INITED
COPP_EC_NOT_INITED.
COPP_EC_ALREADY_INITED
COPP_EC_ALREADY_INITED.
COPP_EC_ACCESS_VIOLATION
COPP_EC_ACCESS_VIOLATION.
COPP_EC_NOT_READY
COPP_EC_NOT_READY.
COPP_EC_NOT_RUNNING
COPP_EC_NOT_RUNNING.
COPP_EC_IS_RUNNING
COPP_EC_IS_RUNNING.
COPP_EC_ALREADY_FINISHED
COPP_EC_ALREADY_FINISHED.
COPP_EC_NOT_FOUND
COPP_EC_NOT_FOUND.
COPP_EC_ALREADY_EXIST
COPP_EC_ALREADY_EXIST.
COPP_EC_ARGS_ERROR
COPP_EC_ARGS_ERROR.
COPP_EC_CAST_FAILED
COPP_EC_CAST_FAILED.
COPP_EC_HAS_UNHANDLE_EXCEPTION
COPP_EC_CAST_FAILED.
COPP_EC_FCONTEXT_MAKE_FAILED
COPP_EC_FCONTEXT_MAKE_FAILED.
COPP_EC_CAN_NOT_USE_CROSS_FCONTEXT_AND_FIBER
COPP_EC_CAN_NOT_USE_CROSS_FCONTEXT_AND_FIBER.
COPP_EC_TASK_CAN_NOT_WAIT_SELF
COPP_EC_TASK_CAN_NOT_WAIT_SELF.
COPP_EC_TASK_IS_EXITING
COPP_EC_TASK_IS_EXITING.
COPP_EC_TASK_ADD_NEXT_FAILED
COPP_EC_TASK_ADD_NEXT_FAILED.
COPP_EC_TASK_NOT_IN_ACTION
COPP_EC_TASK_NOT_IN_ACTION.
COPP_EC_TASK_ALREADY_IN_ANOTHER_MANAGER
COPP_EC_TASK_ALREADY_IN_ANOTHER_MANAGER.
Definition at line 11 of file errno.h.
Function Documentation
jump_to()
static void copp::jump_to (fcontext::fcontext_t & to_fctx, EXPLICIT_UNUSED_ATTR stack_context & from_sctx, EXPLICIT_UNUSED_ATTR stack_context & to_sctx, libcopp_inner_api_helper::jump_src_data_t & jump_transfer) inline static
call platform jump to asm instruction
Parameters
to_fctx jump to function context
from_sctx jump from stack context(only used for save segment stack)
to_sctx jump to stack context(only used for set segment stack)
jump_transfer jump data
save from_co's fcontext and switch status we should use from_co in transfer_t, because it may not jump from jump_transfer.to_co
if we jump sequence is A->B->C->A.resume(), and if this call is A->B, then jump_src->from_co = C, jump_src->to_co = A, jump_transfer.from_co = A, jump_transfer.to_co = B and now we should save the callee of C and set the caller of A = C
if we jump sequence is A->B.yield()->A, and if this call is A->B, then jump_src->from_co = B, jump_src->to_co = UTIL_CONFIG_NULLPTR, jump_transfer.from_co = A, jump_transfer.to_co = B and now we should save the callee of B and should change the caller of A
Definition at line 211 of file coroutine_context.cpp.
References copp::fcontext::copp_jump_fcontext(), copp::fcontext::transfer_t::data, copp::fcontext::transfer_t::fctx, copp::coroutine_context::jump_src_data_t::from_co, copp::coroutine_context::jump_src_data_t::priv_data, copp::libcopp_inner_api_helper::set_callee(), copp::libcopp_inner_api_helper::set_caller(), copp::detail::set_this_coroutine_context(), and copp::coroutine_context::jump_src_data_t::to_co.
Referenced by copp::coroutine_context::start(), and copp::coroutine_context::yield().