libcopp: cotask::impl::task_impl Class Reference
cotask::impl::task_impl Class Reference abstract
#include <task_impl.h>
Data Structures
struct ext_coroutine_flag_t
Public Types
typedef copp::util::uint64_id_allocator::value_type id_t
typedef copp::util::uint64_id_allocator id_allocator_t
Public Member Functions
LIBCOPP_COTASK_API task_impl ()
virtual LIBCOPP_COTASK_API ~task_impl ()=0
UTIL_FORCEINLINE id_t get_id () const LIBCOPP_MACRO_NOEXCEPT
UTIL_FORCEINLINE EN_TASK_STATUS get_status () const LIBCOPP_MACRO_NOEXCEPT
virtual LIBCOPP_COTASK_API bool is_canceled () const LIBCOPP_MACRO_NOEXCEPT
virtual LIBCOPP_COTASK_API bool is_completed () const LIBCOPP_MACRO_NOEXCEPT
virtual LIBCOPP_COTASK_API bool is_faulted () const LIBCOPP_MACRO_NOEXCEPT
virtual LIBCOPP_COTASK_API bool is_timeout () const LIBCOPP_MACRO_NOEXCEPT
LIBCOPP_COTASK_API bool is_exiting () const LIBCOPP_MACRO_NOEXCEPT
check if a cotask is exiting
virtual LIBCOPP_COTASK_API int get_ret_code () const =0
virtual int start (void *priv_data, EN_TASK_STATUS expected_status=EN_TS_CREATED)=0
virtual int resume (void *priv_data, EN_TASK_STATUS expected_status=EN_TS_WAITING)=0
virtual int yield (void **priv_data)=0
virtual int cancel (void *priv_data)=0
virtual int kill (enum EN_TASK_STATUS status, void *priv_data)=0
UTIL_FORCEINLINE int kill (void *priv_data)
UTIL_FORCEINLINE int start ()
UTIL_FORCEINLINE int resume ()
UTIL_FORCEINLINE int yield ()
UTIL_FORCEINLINE int cancel ()
UTIL_FORCEINLINE int kill (enum EN_TASK_STATUS status)
UTIL_FORCEINLINE int kill ()
virtual LIBCOPP_COTASK_API int on_finished ()
UTIL_FORCEINLINE action_ptr_t get_raw_action () const LIBCOPP_MACRO_NOEXCEPT
get raw action pointer
Static Public Member Functions
static LIBCOPP_COTASK_API task_impl * this_task ()
Protected Member Functions
LIBCOPP_COTASK_API void _set_action (action_ptr_t action)
LIBCOPP_COTASK_API action_ptr_t _get_action ()
LIBCOPP_COTASK_API bool _cas_status (EN_TASK_STATUS &expected, EN_TASK_STATUS desired)
LIBCOPP_COTASK_API int _notify_finished (void *priv_data)
Protected Attributes
typedef action_ptr_t
void * finish_priv_data_
Private Member Functions
task_impl (const task_impl &) UTIL_CONFIG_DELETED_FUNCTION
task_impl & operator= (const task_impl &) UTIL_CONFIG_DELETED_FUNCTION
Private Attributes
action_ptr_t action_
id_t id_
::libcopp::util::lock::atomic_int_type< uint32_t > status_
Friends
LIBCOPP_COTASK_API friend void intrusive_ptr_add_ref (task_impl *p)
LIBCOPP_COTASK_API friend void intrusive_ptr_release (task_impl *p)
Detailed Description
Definition at line 44 of file task_impl.h.
Member Typedef Documentation
id_allocator_t
typedef copp::util::uint64_id_allocator cotask::impl::task_impl::id_allocator_t
Definition at line 55 of file task_impl.h.
id_t
typedef copp::util::uint64_id_allocator::value_type cotask::impl::task_impl::id_t
Definition at line 54 of file task_impl.h.
Constructor & Destructor Documentation
task_impl() [1/2]
cotask::impl::task_impl::task_impl (const task_impl &) private
task_impl() [2/2]
LIBCOPP_COTASK_API cotask::impl::task_impl::task_impl ()
Definition at line 23 of file task_impl.cpp.
References copp::util::uint64_id_allocator::allocate(), and id_.
~task_impl()
LIBCOPP_COTASK_API cotask::impl::task_impl::~task_impl () pure virtual
Definition at line 30 of file task_impl.cpp.
References copp::util::uint64_id_allocator::deallocate(), cotask::EN_TS_DONE, and id_.
Member Function Documentation
_cas_status()
LIBCOPP_COTASK_API bool cotask::impl::task_impl::_cas_status (EN_TASK_STATUS & expected, EN_TASK_STATUS desired) protected
Definition at line 68 of file task_impl.cpp.
References libcopp::util::lock::atomic_int_type< Ty >::compare_exchange_weak(), libcopp::util::lock::memory_order_acq_rel, libcopp::util::lock::memory_order_acquire, and status_.
_get_action()
LIBCOPP_COTASK_API task_impl::action_ptr_t cotask::impl::task_impl::_get_action () protected
Definition at line 66 of file task_impl.cpp.
References action_.
Referenced by _notify_finished().
_notify_finished()
LIBCOPP_COTASK_API int cotask::impl::task_impl::_notify_finished (void * priv_data) protected
Definition at line 79 of file task_impl.cpp.
References _get_action(), copp::COPP_EC_HAS_UNHANDLE_EXCEPTION, finish_priv_data_, and on_finished().
Referenced by cotask::task< TCO_MACRO >::_notify_finished().
_set_action()
LIBCOPP_COTASK_API void cotask::impl::task_impl::_set_action (action_ptr_t action) protected
Definition at line 64 of file task_impl.cpp.
References print_color::action, and action_.
cancel() [1/2]
UTIL_FORCEINLINE int cotask::impl::task_impl::cancel () inline
Definition at line 118 of file task_impl.h.
References cancel().
Referenced by cancel().
cancel() [2/2]
virtual int cotask::impl::task_impl::cancel (void * priv_data) pure virtual
Implemented in cotask::task< TCO_MACRO >.
get_id()
UTIL_FORCEINLINE id_t cotask::impl::task_impl::get_id () const inline
Definition at line 82 of file task_impl.h.
Referenced by cotask::task_manager< TTask, TTaskContainer >::add_task().
get_raw_action()
UTIL_FORCEINLINE action_ptr_t cotask::impl::task_impl::get_raw_action () const inline
get raw action pointer
Note
this function is provided just for debug or show some information, it may return the inner type created by cotask
Returns
pointer to task_action instance
Definition at line 144 of file task_impl.h.
get_ret_code()
virtual LIBCOPP_COTASK_API int cotask::impl::task_impl::get_ret_code () const pure virtual
Implemented in cotask::task< TCO_MACRO >.
get_status()
UTIL_FORCEINLINE EN_TASK_STATUS cotask::impl::task_impl::get_status () const inline
get task status
Returns
task status
Definition at line 88 of file task_impl.h.
References libcopp::util::lock::memory_order_acquire.
Referenced by is_canceled(), is_exiting(), is_faulted(), and is_timeout().
is_canceled()
LIBCOPP_COTASK_API bool cotask::impl::task_impl::is_canceled () const virtual
Definition at line 39 of file task_impl.cpp.
References cotask::EN_TS_CANCELED, and get_status().
is_completed()
LIBCOPP_COTASK_API bool cotask::impl::task_impl::is_completed () const virtual
Reimplemented in cotask::task< TCO_MACRO >.
Definition at line 41 of file task_impl.cpp.
References is_exiting().
is_exiting()
LIBCOPP_COTASK_API bool cotask::impl::task_impl::is_exiting () const
check if a cotask is exiting
Note
cotask is exiting means the cotask is is_completed() or is killed. if a cotask is killed and is running, then is_completed() == false but is_exiting() == true, and after the cotask finished, is_completed() == true
Returns
return true if a cotask is exiting.
Definition at line 47 of file task_impl.cpp.
References cotask::EN_TS_DONE, and get_status().
Referenced by cotask::task_manager< TTask, TTaskContainer >::add_task(), and is_completed().
is_faulted()
LIBCOPP_COTASK_API bool cotask::impl::task_impl::is_faulted () const virtual
Definition at line 43 of file task_impl.cpp.
References cotask::EN_TS_KILLED, and get_status().
is_timeout()
LIBCOPP_COTASK_API bool cotask::impl::task_impl::is_timeout () const virtual
Definition at line 45 of file task_impl.cpp.
References cotask::EN_TS_TIMEOUT, and get_status().
kill() [1/4]
UTIL_FORCEINLINE int cotask::impl::task_impl::kill () inline
Definition at line 120 of file task_impl.h.
References kill().
Referenced by kill().
kill() [2/4]
UTIL_FORCEINLINE int cotask::impl::task_impl::kill (enum EN_TASK_STATUS status) inline
Definition at line 119 of file task_impl.h.
References kill().
Referenced by kill().
kill() [3/4]
virtual int cotask::impl::task_impl::kill (enum EN_TASK_STATUS status, void * priv_data) pure virtual
Implemented in cotask::task< TCO_MACRO >.
kill() [4/4]
UTIL_FORCEINLINE int cotask::impl::task_impl::kill (void * priv_data) inline
Definition at line 113 of file task_impl.h.
References cotask::EN_TS_KILLED, and kill().
Referenced by kill().
on_finished()
LIBCOPP_COTASK_API int cotask::impl::task_impl::on_finished () virtual
Definition at line 49 of file task_impl.cpp.
Referenced by _notify_finished().
operator=()
task_impl& cotask::impl::task_impl::operator= (const task_impl &) private
resume() [1/2]
UTIL_FORCEINLINE int cotask::impl::task_impl::resume () inline
Definition at line 116 of file task_impl.h.
References resume().
Referenced by resume().
resume() [2/2]
virtual int cotask::impl::task_impl::resume (void * priv_data, EN_TASK_STATUS expected_status = EN_TS_WAITING) pure virtual
Implemented in cotask::task< TCO_MACRO >.
start() [1/2]
UTIL_FORCEINLINE int cotask::impl::task_impl::start () inline
Definition at line 115 of file task_impl.h.
References start().
Referenced by start().
start() [2/2]
virtual int cotask::impl::task_impl::start (void * priv_data, EN_TASK_STATUS expected_status = EN_TS_CREATED) pure virtual
Implemented in cotask::task< TCO_MACRO >.
this_task()
LIBCOPP_COTASK_API task_impl * cotask::impl::task_impl::this_task () static
get current running task
Returns
current running task or empty pointer
Definition at line 51 of file task_impl.cpp.
References copp::coroutine_context_base::check_flags(), cotask::impl::task_impl::ext_coroutine_flag_t::EN_ECFT_COTASK, copp::coroutine_context_base::get_private_buffer(), and copp::coroutine_context_base::get_this_coroutine_base().
Referenced by cotask::this_task::get_task(), and cotask::task< TCO_MACRO >::this_task().
yield() [1/2]
UTIL_FORCEINLINE int cotask::impl::task_impl::yield () inline
Definition at line 117 of file task_impl.h.
References yield().
Referenced by yield().
yield() [2/2]
virtual int cotask::impl::task_impl::yield (void ** priv_data) pure virtual
Implemented in cotask::task< TCO_MACRO >.
Referenced by main().
Friends And Related Function Documentation
intrusive_ptr_add_ref
LIBCOPP_COTASK_API friend void intrusive_ptr_add_ref (task_impl * p) friend
intrusive_ptr_release
LIBCOPP_COTASK_API friend void intrusive_ptr_release (task_impl * p) friend
Field Documentation
action_
action_ptr_t cotask::impl::task_impl::action_ private
Definition at line 159 of file task_impl.h.
Referenced by _get_action(), and _set_action().
action_ptr_t
typedef cotask::impl::task_impl::action_ptr_t protected
Definition at line 58 of file task_impl.h.
finish_priv_data_
void* cotask::impl::task_impl::finish_priv_data_ protected
Definition at line 163 of file task_impl.h.
Referenced by _notify_finished().
id_
id_t cotask::impl::task_impl::id_ private
Definition at line 160 of file task_impl.h.
Referenced by task_impl(), and ~task_impl().
status_
::libcopp::util::lock::atomic_int_type<uint32_t> cotask::impl::task_impl::status_ private
Definition at line 167 of file task_impl.h.
Referenced by _cas_status().
The documentation for this class was generated from the following files:
/home/runner/work/libcopp/libcopp/include/libcotask/impl/task_impl.h
/home/runner/work/libcopp/libcopp/src/libcotask/impl/task_impl.cpp