libcopp: /home/runner/work/libcopp/libcopp/test/case/future_and_std_coroutine_test.cpp File Reference
future_and_std_coroutine_test.cpp File Reference
#include <cstdio>
#include <cstring>
#include <iostream>
#include <string>
#include <libcopp/future/future.h>
#include <libcopp/future/poll.h>
#include "frame/test_macros.h"
#include <libcotask/task.h>
#include <libcopp/future/std_coroutine_generator.h>
#include <libcopp/future/std_coroutine_task.h>
Data Structures
struct test_no_trivial_parent_clazz
struct test_no_trivial_child_clazz
struct test_future_void_context_poll_functor< T >
struct test_future_void_context_poll_functor< void >
struct test_future_void_context_poll_functor< T >
struct test_future_custom_poller_for_context< T >
Functions
CASE_TEST (future, poll_void)
CASE_TEST (future, poll_trival)
CASE_TEST (future, poll_no_trivial)
CASE_TEST (future, poll_shared_ptr)
CASE_TEST (future, poll_void_reset_and_swap)
CASE_TEST (future, poll_trivial_reset_and_swap)
CASE_TEST (future, poll_no_trivial_reset_and_swap)
CASE_TEST (future, swap_trivial_result)
CASE_TEST (future, swap_no_trivial_result)
template<bool >
static const char * test_future_trivial_name ()
template<>
const char * test_future_trivial_name< false > ()
template<>
const char * test_future_trivial_name< true > ()
CASE_TEST (future, future_with_void_result_and_void_context)
CASE_TEST (future, future_with_trival_result_and_void_context)
CASE_TEST (future, future_and_custom_poller_context_trivial)
CASE_TEST (future, future_and_custom_poller_context_no_trivial)
CASE_TEST (future, future_with_copp_result_and_custom_poller_context_trivial)
CASE_TEST (future, future_with_copp_result_and_custom_poller_context_no_trivial)
Function Documentation
CASE_TEST() [1/15]
CASE_TEST (future , future_and_custom_poller_context_no_trivial)
Definition at line 391 of file future_and_std_coroutine_test.cpp.
References CASE_EXPECT_EQ, CASE_EXPECT_FALSE, CASE_EXPECT_NE, CASE_EXPECT_TRUE, copp::future::future_t< T, TPTR >::data(), copp::future::context_t< TPD >::get_private_data(), copp::future::context_t< TPD >::get_wake_fn(), copp::future::future_t< T, TPTR >::is_pending(), copp::future::future_t< T, TPTR >::is_ready(), copp::future::future_t< T, TPTR >::poll(), copp::future::future_t< T, TPTR >::raw_ptr(), copp::details::UTIL_CONFIG_STATIC_ASSERT(), and copp::future::context_t< TPD >::wake().
CASE_TEST() [2/15]
CASE_TEST (future , future_and_custom_poller_context_trivial)
Definition at line 356 of file future_and_std_coroutine_test.cpp.
References CASE_EXPECT_EQ, CASE_EXPECT_FALSE, CASE_EXPECT_NE, CASE_EXPECT_TRUE, copp::future::future_t< T, TPTR >::data(), copp::future::context_t< TPD >::get_private_data(), copp::future::context_t< TPD >::get_wake_fn(), copp::future::future_t< T, TPTR >::is_pending(), copp::future::future_t< T, TPTR >::is_ready(), copp::future::future_t< T, TPTR >::poll(), copp::future::future_t< T, TPTR >::raw_ptr(), copp::details::UTIL_CONFIG_STATIC_ASSERT(), and copp::future::context_t< TPD >::wake().
CASE_TEST() [3/15]
CASE_TEST (future , future_with_copp_result_and_custom_poller_context_no_trivial)
Definition at line 466 of file future_and_std_coroutine_test.cpp.
References CASE_EXPECT_EQ, CASE_EXPECT_FALSE, CASE_EXPECT_NE, CASE_EXPECT_TRUE, copp::future::future_t< T, TPTR >::data(), copp::future::context_t< TPD >::get_private_data(), copp::future::context_t< TPD >::get_wake_fn(), copp::future::future_t< T, TPTR >::is_pending(), copp::future::future_t< T, TPTR >::is_ready(), copp::future::future_t< T, TPTR >::poll(), copp::future::future_t< T, TPTR >::raw_ptr(), copp::details::UTIL_CONFIG_STATIC_ASSERT(), and copp::future::context_t< TPD >::wake().
CASE_TEST() [4/15]
CASE_TEST (future , future_with_copp_result_and_custom_poller_context_trivial)
Definition at line 428 of file future_and_std_coroutine_test.cpp.
References CASE_EXPECT_EQ, CASE_EXPECT_FALSE, CASE_EXPECT_NE, CASE_EXPECT_TRUE, copp::future::future_t< T, TPTR >::data(), copp::future::context_t< TPD >::get_private_data(), copp::future::context_t< TPD >::get_wake_fn(), copp::future::future_t< T, TPTR >::is_pending(), copp::future::future_t< T, TPTR >::is_ready(), copp::future::future_t< T, TPTR >::poll(), copp::future::future_t< T, TPTR >::raw_ptr(), copp::details::UTIL_CONFIG_STATIC_ASSERT(), and copp::future::context_t< TPD >::wake().
CASE_TEST() [5/15]
CASE_TEST (future , future_with_trival_result_and_void_context)
Definition at line 331 of file future_and_std_coroutine_test.cpp.
References CASE_EXPECT_EQ, CASE_EXPECT_FALSE, CASE_EXPECT_TRUE, copp::future::future_t< T, TPTR >::data(), copp::future::context_t< void >::get_wake_fn(), copp::future::future_t< T, TPTR >::is_pending(), copp::future::future_t< T, TPTR >::is_ready(), copp::future::future_t< T, TPTR >::poll(), copp::future::future_t< T, TPTR >::raw_ptr(), and copp::future::context_t< void >::wake().
CASE_TEST() [6/15]
CASE_TEST (future , future_with_void_result_and_void_context)
Definition at line 309 of file future_and_std_coroutine_test.cpp.
References CASE_EXPECT_EQ, CASE_EXPECT_FALSE, CASE_EXPECT_TRUE, copp::future::future_t< T, TPTR >::data(), copp::future::context_t< void >::get_wake_fn(), copp::future::future_t< T, TPTR >::is_pending(), copp::future::future_t< T, TPTR >::is_ready(), copp::future::future_t< T, TPTR >::poll(), copp::future::future_t< T, TPTR >::raw_ptr(), and copp::future::context_t< void >::wake().
CASE_TEST() [7/15]
CASE_TEST (future , poll_no_trivial)
Definition at line 61 of file future_and_std_coroutine_test.cpp.
References CASE_EXPECT_EQ, CASE_EXPECT_FALSE, and CASE_EXPECT_TRUE.
CASE_TEST() [8/15]
CASE_TEST (future , poll_no_trivial_reset_and_swap)
Definition at line 144 of file future_and_std_coroutine_test.cpp.
References CASE_EXPECT_EQ, CASE_EXPECT_FALSE, CASE_EXPECT_TRUE, copp::future::poll_t< T, TPTR >::data(), copp::future::poll_t< T, TPTR >::is_pending(), copp::future::poll_t< T, TPTR >::is_ready(), copp::future::poll_t< T, TPTR >::reset(), and libcopp::util::swap().
CASE_TEST() [9/15]
CASE_TEST (future , poll_shared_ptr)
Definition at line 75 of file future_and_std_coroutine_test.cpp.
References CASE_EXPECT_EQ, CASE_EXPECT_FALSE, and CASE_EXPECT_TRUE.
CASE_TEST() [10/15]
CASE_TEST (future , poll_trival)
Definition at line 47 of file future_and_std_coroutine_test.cpp.
References CASE_EXPECT_EQ, CASE_EXPECT_FALSE, CASE_EXPECT_TRUE, copp::future::poll_t< T, TPTR >::data(), and copp::future::poll_t< T, TPTR >::is_ready().
CASE_TEST() [11/15]
CASE_TEST (future , poll_trivial_reset_and_swap)
Definition at line 123 of file future_and_std_coroutine_test.cpp.
References CASE_EXPECT_EQ, CASE_EXPECT_FALSE, CASE_EXPECT_TRUE, copp::future::poll_t< T, TPTR >::data(), copp::future::poll_t< T, TPTR >::is_pending(), copp::future::poll_t< T, TPTR >::is_ready(), copp::future::poll_t< T, TPTR >::reset(), and libcopp::util::swap().
CASE_TEST() [12/15]
CASE_TEST (future , poll_void)
Definition at line 27 of file future_and_std_coroutine_test.cpp.
References CASE_EXPECT_EQ, CASE_EXPECT_FALSE, CASE_EXPECT_TRUE, copp::future::poll_t< T, TPTR >::data(), copp::future::poll_t< T, TPTR >::is_ready(), and copp::future::poll_t< T, TPTR >::raw_ptr().
CASE_TEST() [13/15]
CASE_TEST (future , poll_void_reset_and_swap)
Definition at line 103 of file future_and_std_coroutine_test.cpp.
References CASE_EXPECT_FALSE, CASE_EXPECT_TRUE, copp::future::poll_t< T, TPTR >::is_pending(), copp::future::poll_t< T, TPTR >::is_ready(), copp::future::poll_t< T, TPTR >::reset(), and libcopp::util::swap().
CASE_TEST() [14/15]
CASE_TEST (future , swap_no_trivial_result)
Definition at line 186 of file future_and_std_coroutine_test.cpp.
References CASE_EXPECT_EQ, CASE_EXPECT_FALSE, CASE_EXPECT_TRUE, copp::future::result_t< TOK, TERR >::create_error(), copp::future::result_t< TOK, TERR >::create_success(), and libcopp::util::swap().
CASE_TEST() [15/15]
CASE_TEST (future , swap_trivial_result)
Definition at line 165 of file future_and_std_coroutine_test.cpp.
References CASE_EXPECT_EQ, CASE_EXPECT_FALSE, CASE_EXPECT_TRUE, copp::future::result_t< TOK, TERR >::create_error(), copp::future::result_t< TOK, TERR >::create_success(), and libcopp::util::swap().
test_future_trivial_name()
template<bool > static const char* test_future_trivial_name () static
test_future_trivial_name< false >()
template<> const char* test_future_trivial_name< false > ()
Definition at line 277 of file future_and_std_coroutine_test.cpp.
test_future_trivial_name< true >()
template<> const char* test_future_trivial_name< true > ()
Definition at line 282 of file future_and_std_coroutine_test.cpp.