libcopp: cotask::this_task Namespace Reference
cotask::this_task Namespace Reference
Functions
LIBCOPP_COTASK_API impl::task_impl * get_task () LIBCOPP_MACRO_NOEXCEPT
get current running task
template<typename Tt >
LIBCOPP_COTASK_API_HEAD_ONLY Tt * get ()
get current running task and try to convert type
Function Documentation
get()
template<typename Tt > LIBCOPP_COTASK_API_HEAD_ONLY Tt* cotask::this_task::get ()
get current running task and try to convert type
Returns
current running task or empty pointer when not in task or fail to convert type
Definition at line 31 of file this_task.h.
References get_task().
get_task()
LIBCOPP_COTASK_API impl::task_impl * cotask::this_task::get_task ()
get current running task
Returns
current running task or empty pointer when not in task
Definition at line 15 of file this_task.cpp.
References cotask::impl::task_impl::this_task().
Referenced by CASE_TEST(), get(), and main().