libcopp: libcopp::util::lock::atomic_int_type< Ty > Class Template Reference
libcopp::util::lock::atomic_int_type< Ty > Class Template Reference
#include <atomic_int_type.h>
Public Types
typedef Ty value_type
Public Member Functions
atomic_int_type () LIBCOPP_MACRO_NOEXCEPT
atomic_int_type (value_type desired) LIBCOPP_MACRO_NOEXCEPT
void store (value_type desired, EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order order=::libcopp::util::lock::memory_order_seq_cst) LIBCOPP_MACRO_NOEXCEPT
void store (value_type desired, EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order order=::libcopp::util::lock::memory_order_seq_cst) volatile LIBCOPP_MACRO_NOEXCEPT
value_type load (EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order order=::libcopp::util::lock::memory_order_seq_cst) const LIBCOPP_MACRO_NOEXCEPT
value_type load (EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order order=::libcopp::util::lock::memory_order_seq_cst) const volatile LIBCOPP_MACRO_NOEXCEPT
operator value_type () const LIBCOPP_MACRO_NOEXCEPT
operator value_type () const volatile LIBCOPP_MACRO_NOEXCEPT
value_type operator= (value_type desired) LIBCOPP_MACRO_NOEXCEPT
value_type operator= (value_type desired) volatile LIBCOPP_MACRO_NOEXCEPT
value_type operator++ () LIBCOPP_MACRO_NOEXCEPT
value_type operator++ () volatile LIBCOPP_MACRO_NOEXCEPT
value_type operator++ (int) LIBCOPP_MACRO_NOEXCEPT
value_type operator++ (int) volatile LIBCOPP_MACRO_NOEXCEPT
value_type operator-- () LIBCOPP_MACRO_NOEXCEPT
value_type operator-- () volatile LIBCOPP_MACRO_NOEXCEPT
value_type operator-- (int) LIBCOPP_MACRO_NOEXCEPT
value_type operator-- (int) volatile LIBCOPP_MACRO_NOEXCEPT
value_type exchange (value_type desired, EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order order=::libcopp::util::lock::memory_order_seq_cst) LIBCOPP_MACRO_NOEXCEPT
value_type exchange (value_type desired, EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order order=::libcopp::util::lock::memory_order_seq_cst) volatile LIBCOPP_MACRO_NOEXCEPT
bool compare_exchange_weak (value_type &expected, value_type desired, EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order success, EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order failure) LIBCOPP_MACRO_NOEXCEPT
bool compare_exchange_weak (value_type &expected, value_type desired, EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order success, EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order failure) volatile LIBCOPP_MACRO_NOEXCEPT
bool compare_exchange_weak (value_type &expected, value_type desired, EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order order=::libcopp::util::lock::memory_order_seq_cst) LIBCOPP_MACRO_NOEXCEPT
bool compare_exchange_weak (value_type &expected, value_type desired, EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order order=::libcopp::util::lock::memory_order_seq_cst) volatile LIBCOPP_MACRO_NOEXCEPT
bool compare_exchange_strong (value_type &expected, value_type desired, EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order success, EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order failure) LIBCOPP_MACRO_NOEXCEPT
bool compare_exchange_strong (value_type &expected, value_type desired, EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order success, EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order failure) volatile LIBCOPP_MACRO_NOEXCEPT
bool compare_exchange_strong (value_type &expected, value_type desired, EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order order=::libcopp::util::lock::memory_order_seq_cst) LIBCOPP_MACRO_NOEXCEPT
bool compare_exchange_strong (value_type &expected, value_type desired, EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order order=::libcopp::util::lock::memory_order_seq_cst) volatile LIBCOPP_MACRO_NOEXCEPT
value_type fetch_add (value_type arg, EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order order=::libcopp::util::lock::memory_order_seq_cst) LIBCOPP_MACRO_NOEXCEPT
value_type fetch_add (value_type arg, EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order order=::libcopp::util::lock::memory_order_seq_cst) volatile LIBCOPP_MACRO_NOEXCEPT
value_type fetch_sub (value_type arg, EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order order=::libcopp::util::lock::memory_order_seq_cst) LIBCOPP_MACRO_NOEXCEPT
value_type fetch_sub (value_type arg, EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order order=::libcopp::util::lock::memory_order_seq_cst) volatile LIBCOPP_MACRO_NOEXCEPT
value_type fetch_and (value_type arg, EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order order=::libcopp::util::lock::memory_order_seq_cst) LIBCOPP_MACRO_NOEXCEPT
value_type fetch_and (value_type arg, EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order order=::libcopp::util::lock::memory_order_seq_cst) volatile LIBCOPP_MACRO_NOEXCEPT
value_type fetch_or (value_type arg, EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order order=::libcopp::util::lock::memory_order_seq_cst) LIBCOPP_MACRO_NOEXCEPT
value_type fetch_or (value_type arg, EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order order=::libcopp::util::lock::memory_order_seq_cst) volatile LIBCOPP_MACRO_NOEXCEPT
value_type fetch_xor (value_type arg, EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order order=::libcopp::util::lock::memory_order_seq_cst) LIBCOPP_MACRO_NOEXCEPT
value_type fetch_xor (value_type arg, EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order order=::libcopp::util::lock::memory_order_seq_cst) volatile LIBCOPP_MACRO_NOEXCEPT
Private Member Functions
atomic_int_type (const atomic_int_type &) UTIL_CONFIG_DELETED_FUNCTION
atomic_int_type & operator= (const atomic_int_type &) UTIL_CONFIG_DELETED_FUNCTION
atomic_int_type & operator= (const atomic_int_type &) volatile UTIL_CONFIG_DELETED_FUNCTION
Private Attributes
volatile value_type data_
Detailed Description
template<typename Ty = int>
class libcopp::util::lock::atomic_int_type< Ty >
Definition at line 351 of file atomic_int_type.h.
Member Typedef Documentation
value_type
template<typename Ty = int> typedef Ty libcopp::util::lock::atomic_int_type< Ty >::value_type
Definition at line 353 of file atomic_int_type.h.
Constructor & Destructor Documentation
atomic_int_type() [1/3]
template<typename Ty = int> libcopp::util::lock::atomic_int_type< Ty >::atomic_int_type (const atomic_int_type< Ty > &) private
atomic_int_type() [2/3]
template<typename Ty = int> libcopp::util::lock::atomic_int_type< Ty >::atomic_int_type () inline
Definition at line 369 of file atomic_int_type.h.
atomic_int_type() [3/3]
template<typename Ty = int> libcopp::util::lock::atomic_int_type< Ty >::atomic_int_type (value_type desired) inline
Definition at line 381 of file atomic_int_type.h.
Member Function Documentation
compare_exchange_strong() [1/4]
template<typename Ty = int> bool libcopp::util::lock::atomic_int_type< Ty >::compare_exchange_strong (value_type & expected, value_type desired, EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order order = ::libcopp::util::lock::memory_order_seq_cst) inline
Definition at line 723 of file atomic_int_type.h.
compare_exchange_strong() [2/4]
template<typename Ty = int> bool libcopp::util::lock::atomic_int_type< Ty >::compare_exchange_strong (value_type & expected, value_type desired, EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order order = ::libcopp::util::lock::memory_order_seq_cst) volatile inline
Definition at line 749 of file atomic_int_type.h.
compare_exchange_strong() [3/4]
template<typename Ty = int> bool libcopp::util::lock::atomic_int_type< Ty >::compare_exchange_strong (value_type & expected, value_type desired, EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order success, EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order failure) inline
Definition at line 671 of file atomic_int_type.h.
Referenced by copp::util::details::allocate_id_by_atomic(), copp::coroutine_context_base::set_runner(), copp::coroutine_context::start(), and copp::coroutine_context::yield().
compare_exchange_strong() [4/4]
template<typename Ty = int> bool libcopp::util::lock::atomic_int_type< Ty >::compare_exchange_strong (value_type & expected, value_type desired, EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order success, EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order failure) volatile inline
Definition at line 697 of file atomic_int_type.h.
compare_exchange_weak() [1/4]
template<typename Ty = int> bool libcopp::util::lock::atomic_int_type< Ty >::compare_exchange_weak (value_type & expected, value_type desired, EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order order = ::libcopp::util::lock::memory_order_seq_cst) inline
Definition at line 619 of file atomic_int_type.h.
compare_exchange_weak() [2/4]
template<typename Ty = int> bool libcopp::util::lock::atomic_int_type< Ty >::compare_exchange_weak (value_type & expected, value_type desired, EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order order = ::libcopp::util::lock::memory_order_seq_cst) volatile inline
Definition at line 645 of file atomic_int_type.h.
compare_exchange_weak() [3/4]
template<typename Ty = int> bool libcopp::util::lock::atomic_int_type< Ty >::compare_exchange_weak (value_type & expected, value_type desired, EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order success, EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order failure) inline
Definition at line 567 of file atomic_int_type.h.
Referenced by cotask::impl::task_impl::_cas_status(), and copp::util::details::allocate_id_by_atomic().
compare_exchange_weak() [4/4]
template<typename Ty = int> bool libcopp::util::lock::atomic_int_type< Ty >::compare_exchange_weak (value_type & expected, value_type desired, EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order success, EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order failure) volatile inline
Definition at line 593 of file atomic_int_type.h.
exchange() [1/2]
template<typename Ty = int> value_type libcopp::util::lock::atomic_int_type< Ty >::exchange (value_type desired, EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order order = ::libcopp::util::lock::memory_order_seq_cst) inline
Definition at line 527 of file atomic_int_type.h.
exchange() [2/2]
template<typename Ty = int> value_type libcopp::util::lock::atomic_int_type< Ty >::exchange (value_type desired, EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order order = ::libcopp::util::lock::memory_order_seq_cst) volatile inline
Definition at line 547 of file atomic_int_type.h.
fetch_add() [1/2]
template<typename Ty = int> value_type libcopp::util::lock::atomic_int_type< Ty >::fetch_add (value_type arg, EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order order = ::libcopp::util::lock::memory_order_seq_cst) inline
Definition at line 775 of file atomic_int_type.h.
fetch_add() [2/2]
template<typename Ty = int> value_type libcopp::util::lock::atomic_int_type< Ty >::fetch_add (value_type arg, EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order order = ::libcopp::util::lock::memory_order_seq_cst) volatile inline
Definition at line 788 of file atomic_int_type.h.
fetch_and() [1/2]
template<typename Ty = int> value_type libcopp::util::lock::atomic_int_type< Ty >::fetch_and (value_type arg, EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order order = ::libcopp::util::lock::memory_order_seq_cst) inline
Definition at line 831 of file atomic_int_type.h.
fetch_and() [2/2]
template<typename Ty = int> value_type libcopp::util::lock::atomic_int_type< Ty >::fetch_and (value_type arg, EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order order = ::libcopp::util::lock::memory_order_seq_cst) volatile inline
Definition at line 844 of file atomic_int_type.h.
fetch_or() [1/2]
template<typename Ty = int> value_type libcopp::util::lock::atomic_int_type< Ty >::fetch_or (value_type arg, EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order order = ::libcopp::util::lock::memory_order_seq_cst) inline
Definition at line 859 of file atomic_int_type.h.
fetch_or() [2/2]
template<typename Ty = int> value_type libcopp::util::lock::atomic_int_type< Ty >::fetch_or (value_type arg, EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order order = ::libcopp::util::lock::memory_order_seq_cst) volatile inline
Definition at line 872 of file atomic_int_type.h.
fetch_sub() [1/2]
template<typename Ty = int> value_type libcopp::util::lock::atomic_int_type< Ty >::fetch_sub (value_type arg, EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order order = ::libcopp::util::lock::memory_order_seq_cst) inline
Definition at line 803 of file atomic_int_type.h.
fetch_sub() [2/2]
template<typename Ty = int> value_type libcopp::util::lock::atomic_int_type< Ty >::fetch_sub (value_type arg, EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order order = ::libcopp::util::lock::memory_order_seq_cst) volatile inline
Definition at line 816 of file atomic_int_type.h.
fetch_xor() [1/2]
template<typename Ty = int> value_type libcopp::util::lock::atomic_int_type< Ty >::fetch_xor (value_type arg, EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order order = ::libcopp::util::lock::memory_order_seq_cst) inline
Definition at line 887 of file atomic_int_type.h.
fetch_xor() [2/2]
template<typename Ty = int> value_type libcopp::util::lock::atomic_int_type< Ty >::fetch_xor (value_type arg, EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order order = ::libcopp::util::lock::memory_order_seq_cst) volatile inline
Definition at line 900 of file atomic_int_type.h.
load() [1/2]
template<typename Ty = int> value_type libcopp::util::lock::atomic_int_type< Ty >::load (EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order order = ::libcopp::util::lock::memory_order_seq_cst) const inline
Definition at line 412 of file atomic_int_type.h.
Referenced by copp::util::details::allocate_id_by_atomic(), copp::coroutine_context_base::is_finished(), and copp::coroutine_context_container< TALLOC >::use_count().
load() [2/2]
template<typename Ty = int> value_type libcopp::util::lock::atomic_int_type< Ty >::load (EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order order = ::libcopp::util::lock::memory_order_seq_cst) const volatile inline
Definition at line 427 of file atomic_int_type.h.
operator value_type() [1/2]
template<typename Ty = int> libcopp::util::lock::atomic_int_type< Ty >::operator value_type () const inline
Definition at line 442 of file atomic_int_type.h.
operator value_type() [2/2]
template<typename Ty = int> libcopp::util::lock::atomic_int_type< Ty >::operator value_type () const volatile inline
Definition at line 443 of file atomic_int_type.h.
operator++() [1/4]
template<typename Ty = int> value_type libcopp::util::lock::atomic_int_type< Ty >::operator++ () inline
Definition at line 454 of file atomic_int_type.h.
operator++() [2/4]
template<typename Ty = int> value_type libcopp::util::lock::atomic_int_type< Ty >::operator++ () volatile inline
Definition at line 463 of file atomic_int_type.h.
operator++() [3/4]
template<typename Ty = int> value_type libcopp::util::lock::atomic_int_type< Ty >::operator++ (int) inline
Definition at line 472 of file atomic_int_type.h.
operator++() [4/4]
template<typename Ty = int> value_type libcopp::util::lock::atomic_int_type< Ty >::operator++ (int) volatile inline
Definition at line 481 of file atomic_int_type.h.
operator--() [1/4]
template<typename Ty = int> value_type libcopp::util::lock::atomic_int_type< Ty >::operator-- () inline
Definition at line 490 of file atomic_int_type.h.
operator--() [2/4]
template<typename Ty = int> value_type libcopp::util::lock::atomic_int_type< Ty >::operator-- () volatile inline
Definition at line 499 of file atomic_int_type.h.
operator--() [3/4]
template<typename Ty = int> value_type libcopp::util::lock::atomic_int_type< Ty >::operator-- (int) inline
Definition at line 508 of file atomic_int_type.h.
operator--() [4/4]
template<typename Ty = int> value_type libcopp::util::lock::atomic_int_type< Ty >::operator-- (int) volatile inline
Definition at line 517 of file atomic_int_type.h.
operator=() [1/4]
template<typename Ty = int> atomic_int_type& libcopp::util::lock::atomic_int_type< Ty >::operator= (const atomic_int_type< Ty > &) private
operator=() [2/4]
template<typename Ty = int> atomic_int_type& libcopp::util::lock::atomic_int_type< Ty >::operator= (const atomic_int_type< Ty > &) volatile private
operator=() [3/4]
template<typename Ty = int> value_type libcopp::util::lock::atomic_int_type< Ty >::operator= (value_type desired) inline
Definition at line 445 of file atomic_int_type.h.
operator=() [4/4]
template<typename Ty = int> value_type libcopp::util::lock::atomic_int_type< Ty >::operator= (value_type desired) volatile inline
Definition at line 449 of file atomic_int_type.h.
store() [1/2]
template<typename Ty = int> void libcopp::util::lock::atomic_int_type< Ty >::store (value_type desired, EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order order = ::libcopp::util::lock::memory_order_seq_cst) inline
Definition at line 383 of file atomic_int_type.h.
Referenced by copp::coroutine_context::start().
store() [2/2]
template<typename Ty = int> void libcopp::util::lock::atomic_int_type< Ty >::store (value_type desired, EXPLICIT_UNUSED_ATTR ::libcopp::util::lock::memory_order order = ::libcopp::util::lock::memory_order_seq_cst) volatile inline
Definition at line 397 of file atomic_int_type.h.
Field Documentation
data_
template<typename Ty = int> volatile value_type libcopp::util::lock::atomic_int_type< Ty >::data_ private
Definition at line 360 of file atomic_int_type.h.
The documentation for this class was generated from the following file:
/home/runner/work/libcopp/libcopp/include/libcopp/utils/atomic_int_type.h