libcopp: copp::coroutine_context_base Class Reference
copp::coroutine_context_base Class Reference
base type of all coroutine context
#include <coroutine_context_base.h>
Data Structures
struct flag_t
struct status_t
status of safe coroutine context base
Public Types
typedef std::function< int(void *)> callback_t
Public Member Functions
LIBCOPP_COPP_API ~coroutine_context_base ()
LIBCOPP_COPP_API bool set_flags (int flags) LIBCOPP_MACRO_NOEXCEPT
set all flags to true
LIBCOPP_COPP_API bool unset_flags (int flags) LIBCOPP_MACRO_NOEXCEPT
set all flags to false
LIBCOPP_COPP_API bool check_flags (int flags) const LIBCOPP_MACRO_NOEXCEPT
check flags
LIBCOPP_COPP_API int set_runner (const callback_t &runner)
set runner
const UTIL_FORCEINLINE std::function< int(void *)> & get_runner () const LIBCOPP_MACRO_NOEXCEPT
UTIL_FORCEINLINE int get_ret_code () const LIBCOPP_MACRO_NOEXCEPT
get runner return code
LIBCOPP_COPP_API bool is_finished () const LIBCOPP_MACRO_NOEXCEPT
get runner return code
UTIL_FORCEINLINE void * get_private_buffer () const LIBCOPP_MACRO_NOEXCEPT
get private buffer(raw pointer)
UTIL_FORCEINLINE size_t get_private_buffer_size () const LIBCOPP_MACRO_NOEXCEPT
get private buffer size
Static Public Member Functions
static UTIL_FORCEINLINE size_t align_private_data_size (size_t sz)
static size_t align_address_size (size_t sz)
static size_t align_stack_size (size_t sz)
static LIBCOPP_COPP_API coroutine_context_base * get_this_coroutine_base () LIBCOPP_MACRO_NOEXCEPT
get current coroutine
static LIBCOPP_COPP_API void set_this_coroutine_base (coroutine_context_base *ctx) LIBCOPP_MACRO_NOEXCEPT
set current coroutine
Protected Member Functions
LIBCOPP_COPP_API coroutine_context_base () LIBCOPP_MACRO_NOEXCEPT
UTIL_FORCEINLINE void run_and_recv_retcode (void *priv_data)
coroutine entrance function
Protected Attributes
int runner_ret_code_
int flags_
callback_t runner_
void * priv_data_
size_t private_buffer_size_
libcopp::util::lock::atomic_int_type< int > status_
Private Member Functions
coroutine_context_base (const coroutine_context_base &) UTIL_CONFIG_DELETED_FUNCTION
coroutine_context_base & operator= (const coroutine_context_base &) UTIL_CONFIG_DELETED_FUNCTION
Detailed Description
base type of all coroutine context
Definition at line 78 of file coroutine_context_base.h.
Member Typedef Documentation
callback_t
typedef std::function<int(void *)> copp::coroutine_context_base::callback_t
Definition at line 80 of file coroutine_context_base.h.
Constructor & Destructor Documentation
coroutine_context_base() [1/2]
LIBCOPP_COPP_API copp::coroutine_context_base::coroutine_context_base () protected
status
Definition at line 65 of file coroutine_context.cpp.
~coroutine_context_base()
LIBCOPP_COPP_API copp::coroutine_context_base::~coroutine_context_base ()
Definition at line 73 of file coroutine_context.cpp.
coroutine_context_base() [2/2]
copp::coroutine_context_base::coroutine_context_base (const coroutine_context_base &) private
Member Function Documentation
align_address_size()
static size_t copp::coroutine_context_base::align_address_size (size_t sz) inline static
Definition at line 225 of file coroutine_context_base.h.
References COROUTINE_CONTEXT_BASE_ALIGN_UNIT_SIZE.
Referenced by copp::coroutine_context_container< TALLOC >::create().
align_private_data_size()
static UTIL_FORCEINLINE size_t copp::coroutine_context_base::align_private_data_size (size_t sz) inline static
Definition at line 209 of file coroutine_context_base.h.
References COROUTINE_CONTEXT_BASE_ALIGN_UNIT_SIZE.
Referenced by copp::coroutine_context_container< TALLOC >::create().
align_stack_size()
static size_t copp::coroutine_context_base::align_stack_size (size_t sz) inline static
Definition at line 233 of file coroutine_context_base.h.
References COROUTINE_CONTEXT_STACK_ALIGN_UNIT_SIZE.
Referenced by copp::coroutine_context::create().
check_flags()
LIBCOPP_COPP_API bool copp::coroutine_context_base::check_flags (int flags) const
check flags
Parameters
flags flags to be checked
Returns
true if flags any flags is true
Definition at line 93 of file coroutine_context.cpp.
Referenced by copp::this_coroutine::get_coroutine(), copp::coroutine_context::start(), cotask::impl::task_impl::this_task(), and copp::coroutine_context::yield().
get_private_buffer()
UTIL_FORCEINLINE void* copp::coroutine_context_base::get_private_buffer () const inline
get private buffer(raw pointer)
Definition at line 201 of file coroutine_context_base.h.
References priv_data_.
Referenced by cotask::impl::task_impl::this_task().
get_private_buffer_size()
UTIL_FORCEINLINE size_t copp::coroutine_context_base::get_private_buffer_size () const inline
get private buffer size
Definition at line 206 of file coroutine_context_base.h.
References private_buffer_size_.
get_ret_code()
UTIL_FORCEINLINE int copp::coroutine_context_base::get_ret_code () const inline
get runner return code
Returns
Definition at line 190 of file coroutine_context_base.h.
References runner_ret_code_.
get_runner()
const UTIL_FORCEINLINE std::function<int(void *)>& copp::coroutine_context_base::get_runner () const inline
get runner of this coroutine context (const)
Returns
NULL of pointer of runner
Definition at line 184 of file coroutine_context_base.h.
References runner_.
get_this_coroutine_base()
LIBCOPP_COPP_API coroutine_context_base * copp::coroutine_context_base::get_this_coroutine_base () static
get current coroutine
See also
detail::coroutine_context_base
Returns
pointer of current coroutine, if not in coroutine, return NULL
Definition at line 122 of file coroutine_context.cpp.
References copp::detail::get_this_coroutine_context().
Referenced by cotask::impl::task_impl::this_task().
is_finished()
LIBCOPP_COPP_API bool copp::coroutine_context_base::is_finished () const
get runner return code
Returns
true if coroutine has run and finished
Definition at line 117 of file coroutine_context.cpp.
References copp::coroutine_context_base::status_t::EN_CRS_FINISHED, libcopp::util::lock::atomic_int_type< Ty >::load(), libcopp::util::lock::memory_order_acquire, and status_.
operator=()
coroutine_context_base& copp::coroutine_context_base::operator= (const coroutine_context_base &) private
run_and_recv_retcode()
UTIL_FORCEINLINE void copp::coroutine_context_base::run_and_recv_retcode (void * priv_data) inline protected
coroutine entrance function
Definition at line 162 of file coroutine_context_base.h.
References runner_, and runner_ret_code_.
Referenced by copp::libcopp_inner_api_helper::coroutine_context_callback().
set_flags()
LIBCOPP_COPP_API bool copp::coroutine_context_base::set_flags (int flags)
set all flags to true
Parameters
flags (flags & EN_CFT_MASK) must be 0
Returns
true if flags is available, or return false
Definition at line 75 of file coroutine_context.cpp.
set_runner()
LIBCOPP_COPP_API int copp::coroutine_context_base::set_runner (const callback_t & runner)
set runner
Parameters
runner
Returns
COPP_EC_SUCCESS or error code
Definition at line 100 of file coroutine_context.cpp.
References libcopp::util::lock::atomic_int_type< Ty >::compare_exchange_strong(), copp::COPP_EC_ALREADY_INITED, copp::COPP_EC_ARGS_ERROR, copp::COPP_EC_SUCCESS, copp::coroutine_context_base::status_t::EN_CRS_INVALID, copp::coroutine_context_base::status_t::EN_CRS_READY, libcopp::util::lock::memory_order_acq_rel, libcopp::util::lock::memory_order_acquire, runner_, and status_.
set_this_coroutine_base()
LIBCOPP_COPP_API void copp::coroutine_context_base::set_this_coroutine_base (coroutine_context_base * ctx) static
set current coroutine
See also
detail::coroutine_context_base
Parameters
ctx pointer of current coroutine, if not in coroutine, set NULL
Definition at line 126 of file coroutine_context.cpp.
References copp::detail::set_this_coroutine_context().
unset_flags()
LIBCOPP_COPP_API bool copp::coroutine_context_base::unset_flags (int flags)
set all flags to false
Parameters
flags (flags & EN_CFT_MASK) must be 0
Returns
true if flags is available, or return false
Definition at line 84 of file coroutine_context.cpp.
Field Documentation
flags_
int copp::coroutine_context_base::flags_ protected
coroutine return code
Definition at line 106 of file coroutine_context_base.h.
priv_data_
void* copp::coroutine_context_base::priv_data_ protected
coroutine runner
Definition at line 108 of file coroutine_context_base.h.
Referenced by get_private_buffer().
private_buffer_size_
size_t copp::coroutine_context_base::private_buffer_size_ protected
Definition at line 109 of file coroutine_context_base.h.
Referenced by get_private_buffer_size().
runner_
callback_t copp::coroutine_context_base::runner_ protected
flags
Definition at line 107 of file coroutine_context_base.h.
Referenced by get_runner(), run_and_recv_retcode(), and set_runner().
runner_ret_code_
int copp::coroutine_context_base::runner_ret_code_ protected
Definition at line 105 of file coroutine_context_base.h.
Referenced by get_ret_code(), and run_and_recv_retcode().
status_
libcopp::util::lock::atomic_int_type<int> copp::coroutine_context_base::status_ protected
Definition at line 114 of file coroutine_context_base.h.
Referenced by is_finished(), set_runner(), copp::coroutine_context::start(), and copp::coroutine_context::yield().
The documentation for this class was generated from the following files:
/home/runner/work/libcopp/libcopp/include/libcopp/coroutine/coroutine_context_base.h
/home/runner/work/libcopp/libcopp/src/libcopp/coroutine/coroutine_context.cpp