libcopp: /home/runner/work/libcopp/libcopp/sample/sample_readme_3.cpp File Reference
sample_readme_3.cpp File Reference
#include <inttypes.h>
#include <stdint.h>
#include <cstdio>
#include <cstring>
#include <ctime>
#include <iostream>
#include <libcotask/task.h>
#include <libcotask/task_manager.h>
Typedefs
typedef cotask::task my_task_t
typedef my_task_t::ptr_t task_ptr_type
typedef cotask::task_manager< my_task_t > mgr_t
Functions
void tick ()
int main ()
Variables
mgr_t::ptr_t task_mgr = mgr_t::create()
Typedef Documentation
mgr_t
typedef cotask::task_manager<my_task_t> mgr_t
Definition at line 15 of file sample_readme_3.cpp.
my_task_t
typedef cotask::task my_task_t
Definition at line 13 of file sample_readme_3.cpp.
task_ptr_type
typedef my_task_t::ptr_t task_ptr_type
Definition at line 14 of file sample_readme_3.cpp.
Function Documentation
main()
int main ()
Definition at line 25 of file sample_readme_3.cpp.
References cotask::task< TCO_MACRO >::create(), cotask::this_task::get_task(), task_mgr, and cotask::impl::task_impl::yield().
tick()
void tick ()
Definition at line 20 of file sample_readme_3.cpp.
References task_mgr.
Variable Documentation
task_mgr
mgr_t::ptr_t task_mgr = mgr_t::create()
Definition at line 16 of file sample_readme_3.cpp.
Referenced by main(), and tick().