libcopp: copp::allocator::stack_allocator_split_segment Class Reference
copp::allocator::stack_allocator_split_segment Class Reference
memory allocator this allocator will create buffer using gcc split segment api
#include <stack_allocator_split_segment.h>
Public Member Functions
stack_allocator_split_segment () LIBCOPP_MACRO_NOEXCEPT
~stack_allocator_split_segment ()
stack_allocator_split_segment (const stack_allocator_split_segment &other) LIBCOPP_MACRO_NOEXCEPT
stack_allocator_split_segment & operator= (const stack_allocator_split_segment &other) LIBCOPP_MACRO_NOEXCEPT
void allocate (stack_context &, std::size_t) LIBCOPP_MACRO_NOEXCEPT
void deallocate (stack_context &) LIBCOPP_MACRO_NOEXCEPT
Detailed Description
memory allocator this allocator will create buffer using gcc split segment api
Definition at line 25 of file stack_allocator_split_segment.h.
Constructor & Destructor Documentation
stack_allocator_split_segment() [1/2]
LIBCOPP_COPP_API copp::allocator::stack_allocator_split_segment::stack_allocator_split_segment ()
Definition at line 36 of file stack_allocator_split_segment.cpp.
Referenced by operator=().
~stack_allocator_split_segment()
LIBCOPP_COPP_API copp::allocator::stack_allocator_split_segment::~stack_allocator_split_segment ()
Definition at line 37 of file stack_allocator_split_segment.cpp.
References LIBCOPP_COPP_API.
stack_allocator_split_segment() [2/2]
LIBCOPP_COPP_API copp::allocator::stack_allocator_split_segment::stack_allocator_split_segment (const stack_allocator_split_segment & other)
Definition at line 39 of file stack_allocator_split_segment.cpp.
References LIBCOPP_COPP_API, and operator=().
Member Function Documentation
allocate()
LIBCOPP_COPP_API void copp::allocator::stack_allocator_split_segment::allocate (stack_context & ctx, std::size_t size)
allocate memory and attach to stack context [standard function]
Parameters
ctx stack context
size stack size of unit
Definition at line 53 of file stack_allocator_split_segment.cpp.
deallocate()
LIBCOPP_COPP_API void copp::allocator::stack_allocator_split_segment::deallocate (stack_context & ctx)
deallocate memory from stack context [standard function]
Parameters
ctx stack context
Definition at line 67 of file stack_allocator_split_segment.cpp.
operator=()
LIBCOPP_COPP_API stack_allocator_split_segment & copp::allocator::stack_allocator_split_segment::operator= (const stack_allocator_split_segment & other)
Definition at line 41 of file stack_allocator_split_segment.cpp.
References LIBCOPP_COPP_API, LIBCOPP_MACRO_NOEXCEPT, and stack_allocator_split_segment().
Referenced by stack_allocator_split_segment().
The documentation for this class was generated from the following files:
/home/travis/build/owt5008137/libcopp/include/libcopp/stack/allocator/stack_allocator_split_segment.h
/home/travis/build/owt5008137/libcopp/src/libcopp/stack/allocator/stack_allocator_split_segment.cpp