libcopp: custom_waker_t Struct Reference
custom_waker_t Struct Reference
Public Member Functions
void operator() (custom_future_t &fut, custom_context_t &)
custom_waker_t ()
custom_waker_t (const custom_waker_t &other)
custom_waker_t (custom_waker_t &&other)
~custom_waker_t ()
void operator() (custom_future_t &fut, custom_context_t &)
Data Fields
int left_count
Detailed Description
Definition at line 41 of file sample_benchmark_future_poll.cpp.
Constructor & Destructor Documentation
custom_waker_t() [1/3]
custom_waker_t::custom_waker_t () inline
Definition at line 50 of file sample_benchmark_future_poll_no_trivial.cpp.
custom_waker_t() [2/3]
custom_waker_t::custom_waker_t (const custom_waker_t & other) inline
Definition at line 51 of file sample_benchmark_future_poll_no_trivial.cpp.
custom_waker_t() [3/3]
custom_waker_t::custom_waker_t (custom_waker_t && other) inline
Definition at line 52 of file sample_benchmark_future_poll_no_trivial.cpp.
~custom_waker_t()
custom_waker_t::~custom_waker_t () inline
Definition at line 53 of file sample_benchmark_future_poll_no_trivial.cpp.
Member Function Documentation
operator()() [1/2]
void custom_waker_t::operator() (custom_future_t & fut, custom_context_t &) inline
Definition at line 43 of file sample_benchmark_future_poll.cpp.
References left_count, copp::future::result_t< TOK, TERR >::make_error(), copp::future::result_t< TOK, TERR >::make_success(), and copp::future::future_t< T, TPTR >::poll_data().
operator()() [2/2]
void custom_waker_t::operator() (custom_future_t & fut, custom_context_t &) inline
Definition at line 55 of file sample_benchmark_future_poll_no_trivial.cpp.
References copp::future::result_t< TOK, TERR >::make_error(), copp::future::result_t< TOK, TERR >::make_success(), and copp::future::future_t< T, TPTR >::poll_data().
Field Documentation
left_count
int custom_waker_t::left_count
Definition at line 42 of file sample_benchmark_future_poll.cpp.
Referenced by operator()().
The documentation for this struct was generated from the following files:
/home/travis/build/owt5008137/libcopp/sample/sample_benchmark_future_poll.cpp
/home/travis/build/owt5008137/libcopp/sample/sample_benchmark_future_poll_no_trivial.cpp