libcopp: copp::stack_pool< TAlloc > Class Template Reference
copp::stack_pool< TAlloc > Class Template Reference
#include <stack_pool.h>
Data Structures
struct configure_t
struct constructor_delegator
struct limit_t
Public Types
typedef TAlloc allocator_t
typedef std::shared_ptr< stack_pool< TAlloc > > ptr_t
Public Member Functions
stack_pool (constructor_delegator)
~stack_pool ()
const limit_t & get_limit () const
allocator_t & get_origin_allocator () LIBCOPP_MACRO_NOEXCEPT
const allocator_t & get_origin_allocator () const LIBCOPP_MACRO_NOEXCEPT
size_t set_stack_size (size_t sz)
size_t get_stack_size () const
size_t get_stack_size_offset () const
void set_max_stack_size (size_t sz) LIBCOPP_MACRO_NOEXCEPT
size_t get_max_stack_size () const LIBCOPP_MACRO_NOEXCEPT
void set_max_stack_number (size_t sz) LIBCOPP_MACRO_NOEXCEPT
size_t get_max_stack_number () const LIBCOPP_MACRO_NOEXCEPT
void set_min_stack_size (size_t sz) LIBCOPP_MACRO_NOEXCEPT
size_t get_min_stack_size () const LIBCOPP_MACRO_NOEXCEPT
void set_min_stack_number (size_t sz) LIBCOPP_MACRO_NOEXCEPT
size_t get_min_stack_number () const LIBCOPP_MACRO_NOEXCEPT
void set_auto_gc (bool v) LIBCOPP_MACRO_NOEXCEPT
bool is_auto_gc () const LIBCOPP_MACRO_NOEXCEPT
void set_gc_once_number (size_t v) LIBCOPP_MACRO_NOEXCEPT
size_t get_gc_once_number () const LIBCOPP_MACRO_NOEXCEPT
void allocate (stack_context &ctx) LIBCOPP_MACRO_NOEXCEPT
void deallocate (stack_context &ctx) LIBCOPP_MACRO_NOEXCEPT
size_t gc ()
void clear ()
Static Public Member Functions
static ptr_t create ()
Private Member Functions
stack_pool () UTIL_CONFIG_DELETED_FUNCTION
stack_pool (const stack_pool &) UTIL_CONFIG_DELETED_FUNCTION
Private Attributes
limit_t limits_
configure_t conf_
allocator_t alloc_
libcopp::util::lock::spin_lock action_lock_
std::list< stack_context > free_list_
Detailed Description
template<typename TAlloc>
class copp::stack_pool< TAlloc >
Definition at line 22 of file stack_pool.h.
Member Typedef Documentation
allocator_t
template<typename TAlloc > typedef TAlloc copp::stack_pool< TAlloc >::allocator_t
Definition at line 24 of file stack_pool.h.
ptr_t
template<typename TAlloc > typedef std::shared_ptr<stack_pool<TAlloc> > copp::stack_pool< TAlloc >::ptr_t
Definition at line 25 of file stack_pool.h.
Constructor & Destructor Documentation
stack_pool() [1/3]
template<typename TAlloc > copp::stack_pool< TAlloc >::stack_pool () private
stack_pool() [2/3]
template<typename TAlloc > copp::stack_pool< TAlloc >::stack_pool (const stack_pool< TAlloc > &) private
stack_pool() [3/3]
template<typename TAlloc > copp::stack_pool< TAlloc >::stack_pool (constructor_delegator) inline
Definition at line 54 of file stack_pool.h.
References copp::stack_traits::default_size().
~stack_pool()
template<typename TAlloc > copp::stack_pool< TAlloc >::~stack_pool () inline
Definition at line 60 of file stack_pool.h.
Member Function Documentation
allocate()
template<typename TAlloc > void copp::stack_pool< TAlloc >::allocate (stack_context & ctx) inline
allocate memory and attach to stack context [standard function]
Parameters
ctx stack context
size stack size
Note
size must less or equal than attached
Definition at line 108 of file stack_pool.h.
References likely.
clear()
template<typename TAlloc > void copp::stack_pool< TAlloc >::clear () inline
Definition at line 280 of file stack_pool.h.
References LIBCOPP_UTIL_LOCK_ATOMIC_THREAD_FENCE, and libcopp::util::lock::memory_order_release.
create()
template<typename TAlloc > static ptr_t copp::stack_pool< TAlloc >::create () inline static
Definition at line 52 of file stack_pool.h.
Referenced by CASE_TEST(), and main().
deallocate()
template<typename TAlloc > void copp::stack_pool< TAlloc >::deallocate (stack_context & ctx) inline
deallocate memory from stack context [standard function]
Parameters
ctx stack context
Definition at line 173 of file stack_pool.h.
References likely.
gc()
template<typename TAlloc > size_t copp::stack_pool< TAlloc >::gc () inline
Definition at line 215 of file stack_pool.h.
References LIBCOPP_UTIL_LOCK_ATOMIC_THREAD_FENCE, likely, and libcopp::util::lock::memory_order_release.
get_gc_once_number()
template<typename TAlloc > size_t copp::stack_pool< TAlloc >::get_gc_once_number () const inline
Definition at line 98 of file stack_pool.h.
get_limit()
template<typename TAlloc > const limit_t& copp::stack_pool< TAlloc >::get_limit () const inline
Definition at line 62 of file stack_pool.h.
get_max_stack_number()
template<typename TAlloc > size_t copp::stack_pool< TAlloc >::get_max_stack_number () const inline
Definition at line 87 of file stack_pool.h.
get_max_stack_size()
template<typename TAlloc > size_t copp::stack_pool< TAlloc >::get_max_stack_size () const inline
Definition at line 85 of file stack_pool.h.
get_min_stack_number()
template<typename TAlloc > size_t copp::stack_pool< TAlloc >::get_min_stack_number () const inline
Definition at line 92 of file stack_pool.h.
get_min_stack_size()
template<typename TAlloc > size_t copp::stack_pool< TAlloc >::get_min_stack_size () const inline
Definition at line 90 of file stack_pool.h.
get_origin_allocator() [1/2]
template<typename TAlloc > allocator_t& copp::stack_pool< TAlloc >::get_origin_allocator () inline
Definition at line 65 of file stack_pool.h.
get_origin_allocator() [2/2]
template<typename TAlloc > const allocator_t& copp::stack_pool< TAlloc >::get_origin_allocator () const inline
Definition at line 66 of file stack_pool.h.
get_stack_size()
template<typename TAlloc > size_t copp::stack_pool< TAlloc >::get_stack_size () const inline
Definition at line 81 of file stack_pool.h.
get_stack_size_offset()
template<typename TAlloc > size_t copp::stack_pool< TAlloc >::get_stack_size_offset () const inline
Definition at line 82 of file stack_pool.h.
is_auto_gc()
template<typename TAlloc > bool copp::stack_pool< TAlloc >::is_auto_gc () const inline
Definition at line 95 of file stack_pool.h.
set_auto_gc()
template<typename TAlloc > void copp::stack_pool< TAlloc >::set_auto_gc (bool v) inline
Definition at line 94 of file stack_pool.h.
set_gc_once_number()
template<typename TAlloc > void copp::stack_pool< TAlloc >::set_gc_once_number (size_t v) inline
Definition at line 97 of file stack_pool.h.
set_max_stack_number()
template<typename TAlloc > void copp::stack_pool< TAlloc >::set_max_stack_number (size_t sz) inline
Definition at line 86 of file stack_pool.h.
set_max_stack_size()
template<typename TAlloc > void copp::stack_pool< TAlloc >::set_max_stack_size (size_t sz) inline
Definition at line 84 of file stack_pool.h.
set_min_stack_number()
template<typename TAlloc > void copp::stack_pool< TAlloc >::set_min_stack_number (size_t sz) inline
Definition at line 91 of file stack_pool.h.
set_min_stack_size()
template<typename TAlloc > void copp::stack_pool< TAlloc >::set_min_stack_size (size_t sz) inline
Definition at line 89 of file stack_pool.h.
set_stack_size()
template<typename TAlloc > size_t copp::stack_pool< TAlloc >::set_stack_size (size_t sz) inline
Definition at line 68 of file stack_pool.h.
References copp::stack_traits::minimum_size(), and copp::stack_traits::round_to_page_size().
Field Documentation
action_lock_
template<typename TAlloc > libcopp::util::lock::spin_lock copp::stack_pool< TAlloc >::action_lock_ private
Definition at line 300 of file stack_pool.h.
alloc_
template<typename TAlloc > allocator_t copp::stack_pool< TAlloc >::alloc_ private
Definition at line 298 of file stack_pool.h.
conf_
template<typename TAlloc > configure_t copp::stack_pool< TAlloc >::conf_ private
Definition at line 297 of file stack_pool.h.
free_list_
template<typename TAlloc > std::list<stack_context> copp::stack_pool< TAlloc >::free_list_ private
Definition at line 302 of file stack_pool.h.
limits_
template<typename TAlloc > limit_t copp::stack_pool< TAlloc >::limits_ private
Definition at line 296 of file stack_pool.h.
The documentation for this class was generated from the following file:
/home/travis/build/owt5008137/libcopp/include/libcopp/stack/stack_pool.h