libcopp: /home/travis/build/owt5008137/libcopp/test/case/stack_pool_test.cpp File Reference
stack_pool_test.cpp File Reference
#include <cstdio>
#include <cstring>
#include <iostream>
#include <vector>
#include <libcopp/stack/stack_pool.h>
#include <libcotask/task.h>
#include "frame/test_macros.h"
Data Structures
struct stack_pool_test_macro_coroutine
Typedefs
typedef copp::stack_pool< copp::allocator::stack_allocator_malloc > stack_pool_t
typedef cotask::task< stack_pool_test_macro_coroutine > stack_pool_test_task_t
Functions
static int stack_pool_test_task_action (void *)
CASE_TEST (stack_pool_test, stack_context)
CASE_TEST (stack_pool_test, basic)
CASE_TEST (stack_pool_test, full_number)
CASE_TEST (stack_pool_test, custom_gc)
CASE_TEST (stack_pool_test, gc_once)
CASE_TEST (stack_pool_test, full_size)
Variables
static stack_pool_t::ptr_t global_stack_pool
Typedef Documentation
stack_pool_t
typedef copp::stack_pool<copp::allocator::stack_allocator_malloc> stack_pool_t
Definition at line 11 of file stack_pool_test.cpp.
stack_pool_test_task_t
typedef cotask::task<stack_pool_test_macro_coroutine> stack_pool_test_task_t
Definition at line 19 of file stack_pool_test.cpp.
Function Documentation
CASE_TEST() [1/6]
CASE_TEST (stack_pool_test , stack_context)
Definition at line 23 of file stack_pool_test.cpp.
References CASE_EXPECT_EQ, copp::stack_context::reset(), copp::stack_context::size, and copp::stack_context::sp.
CASE_TEST() [2/6]
CASE_TEST (stack_pool_test , basic)
Definition at line 37 of file stack_pool_test.cpp.
References CASE_EXPECT_EQ, copp::stack_pool< TAlloc >::create(), cotask::task< TCO_MACRO >::create(), global_stack_pool, stack_pool_test_task_action(), and task_arr.
CASE_TEST() [3/6]
CASE_TEST (stack_pool_test , full_number)
Definition at line 75 of file stack_pool_test.cpp.
References CASE_EXPECT_TRUE, copp::stack_pool< TAlloc >::create(), cotask::task< TCO_MACRO >::create(), global_stack_pool, stack_pool_test_task_action(), and task_arr.
CASE_TEST() [4/6]
CASE_TEST (stack_pool_test , custom_gc)
Definition at line 99 of file stack_pool_test.cpp.
References CASE_EXPECT_EQ, copp::stack_pool< TAlloc >::create(), cotask::task< TCO_MACRO >::create(), global_stack_pool, stack_pool_test_task_action(), and task_arr.
CASE_TEST() [5/6]
CASE_TEST (stack_pool_test , gc_once)
Definition at line 135 of file stack_pool_test.cpp.
References CASE_EXPECT_EQ, copp::stack_pool< TAlloc >::create(), cotask::task< TCO_MACRO >::create(), global_stack_pool, stack_pool_test_task_action(), and task_arr.
CASE_TEST() [6/6]
CASE_TEST (stack_pool_test , full_size)
Definition at line 178 of file stack_pool_test.cpp.
References CASE_EXPECT_TRUE, copp::stack_pool< TAlloc >::create(), cotask::task< TCO_MACRO >::create(), global_stack_pool, stack_pool_test_task_action(), and task_arr.
stack_pool_test_task_action()
static int stack_pool_test_task_action (void *) static
Definition at line 21 of file stack_pool_test.cpp.
Referenced by CASE_TEST().
Variable Documentation
global_stack_pool
stack_pool_t::ptr_t global_stack_pool static
Definition at line 17 of file stack_pool_test.cpp.
Referenced by CASE_TEST().