libcopp: copp::future::result_t< TOK, TERR > Class Template Reference
copp::future::result_t< TOK, TERR > Class Template Reference
#include <storage.h>
Public Types
typedef result_base_t< TOK, TERR, default_compact_storage_t< TOK >::value &&default_compact_storage_t< TERR >::value > base_type
typedef result_t< TOK, TERR > self_type
typedef _make_instance_type::type storage_type
Static Public Member Functions
template<class... TARGS>
static self_type create_success (TARGS &&...args)
template<class... TARGS>
static self_type create_error (TARGS &&...args)
template<class... TARGS>
static storage_type make_success (TARGS &&...args)
template<class... TARGS>
static storage_type make_error (TARGS &&...args)
Private Types
typedef _make_result_instance_helper< self_type, poll_storage_base_t< base_type, typename poll_storage_select_ptr_t< base_type >::type >::value > _make_instance_type
Detailed Description
template<class TOK, class TERR>
class copp::future::result_t< TOK, TERR >
Definition at line 607 of file storage.h.
Member Typedef Documentation
_make_instance_type
template<class TOK , class TERR > typedef _make_result_instance_helper< self_type, poll_storage_base_t<base_type, typename poll_storage_select_ptr_t<base_type>::type>::value> copp::future::result_t< TOK, TERR >::_make_instance_type private
Definition at line 617 of file storage.h.
base_type
template<class TOK , class TERR > typedef result_base_t<TOK, TERR, default_compact_storage_t<TOK>::value && default_compact_storage_t<TERR>::value> copp::future::result_t< TOK, TERR >::base_type
Definition at line 611 of file storage.h.
self_type
template<class TOK , class TERR > typedef result_t<TOK, TERR> copp::future::result_t< TOK, TERR >::self_type
Definition at line 612 of file storage.h.
storage_type
template<class TOK , class TERR > typedef _make_instance_type::type copp::future::result_t< TOK, TERR >::storage_type
Definition at line 620 of file storage.h.
Member Function Documentation
create_error()
template<class TOK , class TERR > template<class... TARGS> static self_type copp::future::result_t< TOK, TERR >::create_error (TARGS &&... args) inline static
Definition at line 630 of file storage.h.
Referenced by CASE_TEST().
create_success()
template<class TOK , class TERR > template<class... TARGS> static self_type copp::future::result_t< TOK, TERR >::create_success (TARGS &&... args) inline static
Definition at line 623 of file storage.h.
Referenced by CASE_TEST().
make_error()
template<class TOK , class TERR > template<class... TARGS> static storage_type copp::future::result_t< TOK, TERR >::make_error (TARGS &&... args) inline static
Definition at line 643 of file storage.h.
Referenced by custom_waker_t::operator()().
make_success()
template<class TOK , class TERR > template<class... TARGS> static storage_type copp::future::result_t< TOK, TERR >::make_success (TARGS &&... args) inline static
Definition at line 638 of file storage.h.
Referenced by custom_poller_function(), custom_waker_t::operator()(), and run_with_custom_context().
The documentation for this class was generated from the following file:
/home/runner/work/libcopp/libcopp/include/libcopp/future/storage.h