libcopp: /home/runner/work/libcopp/libcopp/sample/sample_readme_6.cpp File Reference
sample_readme_6.cpp File Reference
#include <assert.h>
#include <iostream>
#include <list>
#include <libcopp/future/context.h>
#include <libcopp/future/future.h>
Data Structures
struct example_result_message_t
struct example_poller
Typedefs
typedef copp::future::result_t< example_result_message_t, int > example_result_t
typedef copp::future::future_t< example_result_t > example_future_t
typedef copp::future::context_t< example_poller > example_context_t
Functions
void run_with_custom_context ()
static void custom_poller_function (copp::future::context_t< void > &, copp::future::context_t< void >::poll_event_data_t evt_data)
void run_with_void_context ()
int main ()
Variables
std::list< example_context_t * > g_executor
Typedef Documentation
example_context_t
typedef copp::future::context_t<example_poller> example_context_t
Definition at line 29 of file sample_readme_6.cpp.
example_future_t
typedef copp::future::future_t<example_result_t> example_future_t
Definition at line 28 of file sample_readme_6.cpp.
example_result_t
typedef copp::future::result_t<example_result_message_t, int > example_result_t
Definition at line 22 of file sample_readme_6.cpp.
Function Documentation
custom_poller_function()
static void custom_poller_function (copp::future::context_t< void > & , copp::future::context_t< void >::poll_event_data_t evt_data) static
Definition at line 98 of file sample_readme_6.cpp.
References copp::future::result_t< TOK, TERR >::make_success(), and copp::future::future_t< T, TPTR >::poll_data().
Referenced by run_with_void_context().
main()
int main ()
Definition at line 151 of file sample_readme_6.cpp.
References run_with_custom_context(), and run_with_void_context().
run_with_custom_context()
void run_with_custom_context ()
Definition at line 61 of file sample_readme_6.cpp.
References copp::future::future_t< T, TPTR >::data(), g_executor, copp::future::future_t< T, TPTR >::is_ready(), copp::future::result_t< TOK, TERR >::make_success(), copp::future::future_t< T, TPTR >::poll(), example_result_message_t::response_code, and example_result_message_t::return_code.
Referenced by main().
run_with_void_context()
void run_with_void_context ()
Definition at line 114 of file sample_readme_6.cpp.
References custom_poller_function(), copp::future::future_t< T, TPTR >::data(), copp::future::future_t< T, TPTR >::is_ready(), copp::future::future_t< T, TPTR >::poll(), example_result_message_t::response_code, example_result_message_t::return_code, copp::future::context_t< void >::set_private_data(), and copp::future::context_t< void >::wake().
Referenced by main().
Variable Documentation
g_executor
std::list<example_context_t*> g_executor
Definition at line 31 of file sample_readme_6.cpp.
Referenced by example_poller::example_poller(), example_poller::operator()(), run_with_custom_context(), and example_poller::~example_poller().