libcopp: cotask::task< TCO_MACRO > Class Template Reference
cotask::task< TCO_MACRO > Class Template Reference
#include <task.h>
Data Structures
struct task_group
Public Types
typedef task< TCO_MACRO > self_t
typedef libcopp::util::intrusive_ptr< self_t > ptr_t
typedef TCO_MACRO macro_coroutine_t
typedef macro_coroutine_t::coroutine_t coroutine_t
typedef macro_coroutine_t::stack_allocator_t stack_allocator_t
typedef impl::task_impl::id_t id_t
typedef impl::task_impl::id_allocator_t id_allocator_t
Public Member Functions
task (size_t stack_sz)
constuctor
ptr_t next (ptr_t next_task, void *priv_data=UTIL_CONFIG_NULLPTR)
add next task to run when task finished
template<typename Ty >
ptr_t next (const Ty &functor, void *priv_data=UTIL_CONFIG_NULLPTR, size_t stack_size=0, size_t private_buffer_size=0)
create next task with functor
template<typename Ty >
ptr_t next (const Ty &functor, typename coroutine_t::allocator_type &alloc, void *priv_data=UTIL_CONFIG_NULLPTR, size_t stack_size=0, size_t private_buffer_size=0)
template<typename Ty >
ptr_t next (Ty(*func)(void *), void *priv_data=UTIL_CONFIG_NULLPTR, size_t stack_size=0, size_t private_buffer_size=0)
create next task with function
template<typename Ty >
ptr_t next (Ty(*func)(void *), typename coroutine_t::allocator_type &alloc, void *priv_data=UTIL_CONFIG_NULLPTR, size_t stack_size=0, size_t private_buffer_size=0)
template<typename Ty , typename TInst >
ptr_t next (Ty(TInst::*func), TInst *instance, void *priv_data=UTIL_CONFIG_NULLPTR, size_t stack_size=0, size_t private_buffer_size=0)
create next task with function
template<typename Ty , typename TInst >
ptr_t next (Ty(TInst::*func), TInst *instance, typename coroutine_t::allocator_type &alloc, void *priv_data=UTIL_CONFIG_NULLPTR, size_t stack_size=0, size_t private_buffer_size=0)
int await_task (ptr_t wait_task)
await_task another cotask to finish
template<typename TTask >
int await_task (TTask *wait_task)
ptr_t then (ptr_t next_task, void *priv_data=UTIL_CONFIG_NULLPTR)
add task to run when task finished
template<typename Ty >
ptr_t then (const Ty &functor, typename coroutine_t::allocator_type &alloc, void *priv_data=UTIL_CONFIG_NULLPTR, size_t stack_size=0, size_t private_buffer_size=0)
create next task with functor using the same allocator and private buffer size as this task
template<typename Ty >
ptr_t then (Ty(*func)(void *), void *priv_data=UTIL_CONFIG_NULLPTR)
virtual ~task ()
coroutine_t::ptr_t & get_coroutine_context () LIBCOPP_MACRO_NOEXCEPT
const coroutine_t::ptr_t & get_coroutine_context () const LIBCOPP_MACRO_NOEXCEPT
virtual int get_ret_code () const UTIL_CONFIG_OVERRIDE
virtual int start (void *priv_data, EN_TASK_STATUS expected_status=EN_TS_CREATED) UTIL_CONFIG_OVERRIDE
virtual int resume (void *priv_data, EN_TASK_STATUS expected_status=EN_TS_WAITING) UTIL_CONFIG_OVERRIDE
virtual int yield (void **priv_data) UTIL_CONFIG_OVERRIDE
virtual int cancel (void *priv_data) UTIL_CONFIG_OVERRIDE
virtual int kill (enum EN_TASK_STATUS status, void *priv_data) UTIL_CONFIG_OVERRIDE
virtual bool is_completed () const LIBCOPP_MACRO_NOEXCEPT UTIL_CONFIG_OVERRIDE
void * get_private_buffer ()
size_t get_private_buffer_size ()
size_t use_count () const
UTIL_FORCEINLINE id_t get_id () const LIBCOPP_MACRO_NOEXCEPT
UTIL_FORCEINLINE EN_TASK_STATUS get_status () const LIBCOPP_MACRO_NOEXCEPT
virtual LIBCOPP_COTASK_API bool is_canceled () const LIBCOPP_MACRO_NOEXCEPT
virtual LIBCOPP_COTASK_API bool is_faulted () const LIBCOPP_MACRO_NOEXCEPT
virtual LIBCOPP_COTASK_API bool is_timeout () const LIBCOPP_MACRO_NOEXCEPT
LIBCOPP_COTASK_API bool is_exiting () const LIBCOPP_MACRO_NOEXCEPT
check if a cotask is exiting
UTIL_FORCEINLINE int start ()
UTIL_FORCEINLINE int resume ()
UTIL_FORCEINLINE int yield ()
UTIL_FORCEINLINE int cancel ()
UTIL_FORCEINLINE int kill (void *priv_data)
UTIL_FORCEINLINE int kill (enum EN_TASK_STATUS status)
UTIL_FORCEINLINE int kill ()
virtual LIBCOPP_COTASK_API int on_finished ()
UTIL_FORCEINLINE action_ptr_t get_raw_action () const LIBCOPP_MACRO_NOEXCEPT
get raw action pointer
Static Public Member Functions
template<typename TAct , typename Ty >
static LIBCOPP_COTASK_API_HEAD_ONLY ptr_t create_with_delegate (const Ty &callable, typename coroutine_t::allocator_type &alloc, size_t stack_size=0, size_t private_buffer_size=0)
create task with functor
template<typename Ty >
static ptr_t create (const Ty &functor, size_t stack_size=0, size_t private_buffer_size=0)
create task with functor
template<typename Ty >
static LIBCOPP_COTASK_API_HEAD_ONLY ptr_t create (const Ty &functor, typename coroutine_t::allocator_type &alloc, size_t stack_size=0, size_t private_buffer_size=0)
template<typename Ty >
static ptr_t create (Ty(*func)(void *), typename coroutine_t::allocator_type &alloc, size_t stack_size=0, size_t private_buffer_size=0)
create task with function
template<typename Ty >
static ptr_t create (Ty(*func)(void *), size_t stack_size=0, size_t private_buffer_size=0)
template<typename Ty , typename TInst >
static LIBCOPP_COTASK_API_HEAD_ONLY ptr_t create (Ty(TInst::*func), TInst *instance, typename coroutine_t::allocator_type &alloc, size_t stack_size=0, size_t private_buffer_size=0)
create task with function
template<typename Ty , typename TInst >
static ptr_t create (Ty(TInst::*func), TInst *instance, size_t stack_size=0, size_t private_buffer_size=0)
static self_t * this_task ()
static void * add_buffer_offset (void *in, size_t off)
static void * sub_buffer_offset (void *in, size_t off)
Protected Member Functions
LIBCOPP_COTASK_API void _set_action (action_ptr_t action)
LIBCOPP_COTASK_API action_ptr_t _get_action ()
LIBCOPP_COTASK_API bool _cas_status (EN_TASK_STATUS &expected, EN_TASK_STATUS desired)
Protected Attributes
void * finish_priv_data_
Private Types
typedef impl::task_impl::action_ptr_t action_ptr_t
Private Member Functions
task (const task &) UTIL_CONFIG_DELETED_FUNCTION
void active_next_tasks ()
int _notify_finished (void *priv_data)
Private Attributes
size_t stack_size_
coroutine_t::ptr_t coroutine_obj_
task_group next_list_
void(* action_destroy_fn_)(void *)
libcopp::util::lock::atomic_int_type< size_t > ref_count_
libcopp::util::lock::spin_lock inner_action_lock_
Friends
void intrusive_ptr_add_ref (self_t *p)
void intrusive_ptr_release (self_t *p)
Detailed Description
template<typename TCO_MACRO = macro_coroutine>
class cotask::task< TCO_MACRO >
Definition at line 39 of file task.h.
Member Typedef Documentation
action_ptr_t
template<typename TCO_MACRO = macro_coroutine> typedef impl::task_impl::action_ptr_t cotask::task< TCO_MACRO >::action_ptr_t private
Definition at line 68 of file task.h.
coroutine_t
template<typename TCO_MACRO = macro_coroutine> typedef macro_coroutine_t::coroutine_t cotask::task< TCO_MACRO >::coroutine_t
Definition at line 61 of file task.h.
id_allocator_t
template<typename TCO_MACRO = macro_coroutine> typedef impl::task_impl::id_allocator_t cotask::task< TCO_MACRO >::id_allocator_t
Definition at line 65 of file task.h.
id_t
template<typename TCO_MACRO = macro_coroutine> typedef impl::task_impl::id_t cotask::task< TCO_MACRO >::id_t
Definition at line 64 of file task.h.
macro_coroutine_t
template<typename TCO_MACRO = macro_coroutine> typedef TCO_MACRO cotask::task< TCO_MACRO >::macro_coroutine_t
Definition at line 59 of file task.h.
ptr_t
template<typename TCO_MACRO = macro_coroutine> typedef libcopp::util::intrusive_ptr<self_t> cotask::task< TCO_MACRO >::ptr_t
Definition at line 58 of file task.h.
self_t
template<typename TCO_MACRO = macro_coroutine> typedef task<TCO_MACRO> cotask::task< TCO_MACRO >::self_t
Definition at line 57 of file task.h.
stack_allocator_t
template<typename TCO_MACRO = macro_coroutine> typedef macro_coroutine_t::stack_allocator_t cotask::task< TCO_MACRO >::stack_allocator_t
Definition at line 62 of file task.h.
Constructor & Destructor Documentation
task() [1/2]
template<typename TCO_MACRO = macro_coroutine> cotask::task< TCO_MACRO >::task (size_t stack_sz) inline
constuctor
Note
should not be called directly
Definition at line 79 of file task.h.
References LIBCOPP_COTASK_API_HEAD_ONLY.
~task()
template<typename TCO_MACRO = macro_coroutine> virtual cotask::task< TCO_MACRO >::~task () inline virtual
Definition at line 498 of file task.h.
References cotask::EN_TS_CREATED, and cotask::EN_TS_TIMEOUT.
task() [2/2]
template<typename TCO_MACRO = macro_coroutine> cotask::task< TCO_MACRO >::task (const task< TCO_MACRO > &) private
Member Function Documentation
_cas_status()
LIBCOPP_COTASK_API bool cotask::impl::task_impl::_cas_status (EN_TASK_STATUS & expected, EN_TASK_STATUS desired) protected inherited
Definition at line 70 of file task_impl.cpp.
References cotask::impl::task_impl::_notify_finished(), libcopp::util::lock::atomic_int_type< Ty >::compare_exchange_weak(), LIBCOPP_COTASK_API, libcopp::util::lock::memory_order_acq_rel, libcopp::util::lock::memory_order_acquire, and cotask::impl::task_impl::status_.
_get_action()
LIBCOPP_COTASK_API task_impl::action_ptr_t cotask::impl::task_impl::_get_action () protected inherited
Definition at line 68 of file task_impl.cpp.
References cotask::impl::task_impl::action_.
Referenced by cotask::impl::task_impl::_notify_finished().
_notify_finished()
template<typename TCO_MACRO = macro_coroutine> int cotask::task< TCO_MACRO >::_notify_finished (void * priv_data) inline private
Definition at line 819 of file task.h.
References cotask::impl::task_impl::_notify_finished().
_set_action()
LIBCOPP_COTASK_API void cotask::impl::task_impl::_set_action (action_ptr_t action) protected inherited
Definition at line 66 of file task_impl.cpp.
References print_color::action, and cotask::impl::task_impl::action_.
active_next_tasks()
template<typename TCO_MACRO = macro_coroutine> void cotask::task< TCO_MACRO >::active_next_tasks () inline private
Definition at line 749 of file task.h.
References cotask::EN_TS_INVALID, cotask::EN_TS_RUNNING, and LIBCOPP_MACRO_NOEXCEPT.
add_buffer_offset()
template<typename TCO_MACRO = macro_coroutine> static void* cotask::task< TCO_MACRO >::add_buffer_offset (void * in, size_t off) inline static
Definition at line 709 of file task.h.
await_task() [1/2]
template<typename TCO_MACRO = macro_coroutine> int cotask::task< TCO_MACRO >::await_task (ptr_t wait_task) inline
await_task another cotask to finish
Note
please not to make tasks refer to each other. [it will lead to memory leak]
[don't do that] ptr_t a = ..., b = ...; a.await_task(b); b.await_task(a);
Parameters
wait_task which stack to wait for
Note
we will loop wait and ignore any resume(...) call
Returns
0 or error code
Definition at line 398 of file task.h.
References copp::COPP_EC_ARGS_ERROR, copp::COPP_EC_TASK_ADD_NEXT_FAILED, copp::COPP_EC_TASK_CAN_NOT_WAIT_SELF, copp::COPP_EC_TASK_IS_EXITING, copp::COPP_EC_TASK_NOT_IN_ACTION, libcopp::util::intrusive_ptr< T >::get(), and copp::this_coroutine::yield().
await_task() [2/2]
template<typename TCO_MACRO = macro_coroutine> template<typename TTask > int cotask::task< TCO_MACRO >::await_task (TTask * wait_task) inline
Definition at line 438 of file task.h.
cancel() [1/2]
UTIL_FORCEINLINE int cotask::impl::task_impl::cancel () inline inherited
Definition at line 118 of file task_impl.h.
References cotask::impl::task_impl::cancel().
Referenced by cotask::impl::task_impl::cancel(), and cotask::task< TCO_MACRO >::kill().
cancel() [2/2]
template<typename TCO_MACRO = macro_coroutine> virtual int cotask::task< TCO_MACRO >::cancel (void * priv_data) inline virtual
Implements cotask::impl::task_impl.
Definition at line 634 of file task.h.
References copp::COPP_EC_IS_RUNNING, copp::COPP_EC_SUCCESS, cotask::EN_TS_CANCELED, cotask::EN_TS_RUNNING, LIBCOPP_MACRO_NOEXCEPT, and likely.
create() [1/6]
template<typename TCO_MACRO = macro_coroutine> template<typename Ty > static ptr_t cotask::task< TCO_MACRO >::create (const Ty & functor, size_t stack_size = 0, size_t private_buffer_size = 0) inline static
create task with functor
Parameters
action
stack_size stack size
private_buffer_size buffer size to store private data
Returns
task smart pointer
Definition at line 200 of file task.h.
Referenced by CASE_TEST(), and main().
create() [2/6]
template<typename TCO_MACRO = macro_coroutine> template<typename Ty > static LIBCOPP_COTASK_API_HEAD_ONLY ptr_t cotask::task< TCO_MACRO >::create (const Ty & functor, typename coroutine_t::allocator_type & alloc, size_t stack_size = 0, size_t private_buffer_size = 0) inline static
Definition at line 206 of file task.h.
create() [3/6]
template<typename TCO_MACRO = macro_coroutine> template<typename Ty > static ptr_t cotask::task< TCO_MACRO >::create (Ty(*)(void *) func, typename coroutine_t::allocator_type & alloc, size_t stack_size = 0, size_t private_buffer_size = 0) inline static
create task with function
Parameters
action
stack_size stack size
Returns
task smart pointer
Definition at line 222 of file task.h.
create() [4/6]
template<typename TCO_MACRO = macro_coroutine> template<typename Ty > static ptr_t cotask::task< TCO_MACRO >::create (Ty(*)(void *) func, size_t stack_size = 0, size_t private_buffer_size = 0) inline static
Definition at line 234 of file task.h.
create() [5/6]
template<typename TCO_MACRO = macro_coroutine> template<typename Ty , typename TInst > static LIBCOPP_COTASK_API_HEAD_ONLY ptr_t cotask::task< TCO_MACRO >::create (TyTInst::* func, TInst * instance, typename coroutine_t::allocator_type & alloc, size_t stack_size = 0, size_t private_buffer_size = 0) inline static
create task with function
Parameters
action
stack_size stack size
Returns
task smart pointer
Definition at line 246 of file task.h.
create() [6/6]
template<typename TCO_MACRO = macro_coroutine> template<typename Ty , typename TInst > static ptr_t cotask::task< TCO_MACRO >::create (TyTInst::* func, TInst * instance, size_t stack_size = 0, size_t private_buffer_size = 0) inline static
Definition at line 258 of file task.h.
References LIBCOPP_COTASK_API_HEAD_ONLY.
create_with_delegate()
template<typename TCO_MACRO = macro_coroutine> template<typename TAct , typename Ty > static LIBCOPP_COTASK_API_HEAD_ONLY ptr_t cotask::task< TCO_MACRO >::create_with_delegate (const Ty & callable, typename coroutine_t::allocator_type & alloc, size_t stack_size = 0, size_t private_buffer_size = 0) inline static
create task with functor
Parameters
action
stack_size stack size
private_buffer_size buffer size to store private data
Returns
task smart pointer
Definition at line 102 of file task.h.
References print_color::action, COPP_MACRO_STD_FORWARD, copp::stack_traits::default_size(), cotask::impl::task_impl::ext_coroutine_flag_t::EN_ECFT_COTASK, libcopp::util::intrusive_ptr< T >::get(), and cotask::get_placement_destroy().
get_coroutine_context() [1/2]
template<typename TCO_MACRO = macro_coroutine> coroutine_t::ptr_t& cotask::task< TCO_MACRO >::get_coroutine_context () inline
Definition at line 506 of file task.h.
get_coroutine_context() [2/2]
template<typename TCO_MACRO = macro_coroutine> const coroutine_t::ptr_t& cotask::task< TCO_MACRO >::get_coroutine_context () const inline
Definition at line 507 of file task.h.
get_id()
UTIL_FORCEINLINE id_t cotask::impl::task_impl::get_id () const inline inherited
Definition at line 82 of file task_impl.h.
get_private_buffer()
template<typename TCO_MACRO = macro_coroutine> void* cotask::task< TCO_MACRO >::get_private_buffer () inline
Definition at line 717 of file task.h.
get_private_buffer_size()
template<typename TCO_MACRO = macro_coroutine> size_t cotask::task< TCO_MACRO >::get_private_buffer_size () inline
Definition at line 725 of file task.h.
get_raw_action()
UTIL_FORCEINLINE action_ptr_t cotask::impl::task_impl::get_raw_action () const inline inherited
get raw action pointer
Note
this function is provided just for debug or show some information, it may return the inner type created by cotask
Returns
pointer to task_action instance
Definition at line 143 of file task_impl.h.
References print_color::action, and LIBCOPP_COTASK_API.
get_ret_code()
template<typename TCO_MACRO = macro_coroutine> virtual int cotask::task< TCO_MACRO >::get_ret_code () const inline virtual
Implements cotask::impl::task_impl.
Definition at line 510 of file task.h.
References cotask::EN_TS_CREATED, and LIBCOPP_MACRO_NOEXCEPT.
get_status()
UTIL_FORCEINLINE EN_TASK_STATUS cotask::impl::task_impl::get_status () const inline inherited
get task status
Returns
task status
Definition at line 88 of file task_impl.h.
References cotask::EN_TS_CREATED, cotask::EN_TS_WAITING, LIBCOPP_COTASK_API, LIBCOPP_MACRO_NOEXCEPT, libcopp::util::lock::memory_order_acquire, and copp::this_coroutine::yield().
Referenced by cotask::impl::task_impl::is_canceled(), cotask::impl::task_impl::is_exiting(), cotask::impl::task_impl::is_faulted(), and cotask::impl::task_impl::is_timeout().
is_canceled()
LIBCOPP_COTASK_API bool cotask::impl::task_impl::is_canceled () const virtual inherited
Definition at line 41 of file task_impl.cpp.
References cotask::EN_TS_CANCELED, and cotask::impl::task_impl::get_status().
is_completed()
template<typename TCO_MACRO = macro_coroutine> virtual bool cotask::task< TCO_MACRO >::is_completed () const inline virtual
Reimplemented from cotask::impl::task_impl.
Definition at line 697 of file task.h.
References LIBCOPP_MACRO_NOEXCEPT.
is_exiting()
LIBCOPP_COTASK_API bool cotask::impl::task_impl::is_exiting () const inherited
check if a cotask is exiting
Note
cotask is exiting means the cotask is is_completed() or is killed. if a cotask is killed and is running, then is_completed() == false but is_exiting() == true, and after the cotask finished, is_completed() == true
Returns
return true if a cotask is exiting.
Definition at line 49 of file task_impl.cpp.
References cotask::EN_TS_DONE, and cotask::impl::task_impl::get_status().
Referenced by cotask::impl::task_impl::is_completed().
is_faulted()
LIBCOPP_COTASK_API bool cotask::impl::task_impl::is_faulted () const virtual inherited
Definition at line 45 of file task_impl.cpp.
References cotask::EN_TS_KILLED, and cotask::impl::task_impl::get_status().
is_timeout()
LIBCOPP_COTASK_API bool cotask::impl::task_impl::is_timeout () const virtual inherited
Definition at line 47 of file task_impl.cpp.
References cotask::EN_TS_TIMEOUT, and cotask::impl::task_impl::get_status().
kill() [1/4]
UTIL_FORCEINLINE int cotask::impl::task_impl::kill (void * priv_data) inline inherited
Definition at line 113 of file task_impl.h.
References cotask::EN_TS_KILLED, and cotask::impl::task_impl::kill().
Referenced by cotask::impl::task_impl::kill().
kill() [2/4]
UTIL_FORCEINLINE int cotask::impl::task_impl::kill (enum EN_TASK_STATUS status) inline inherited
Definition at line 119 of file task_impl.h.
References cotask::impl::task_impl::kill().
Referenced by cotask::impl::task_impl::kill().
kill() [3/4]
UTIL_FORCEINLINE int cotask::impl::task_impl::kill () inline inherited
Definition at line 120 of file task_impl.h.
References cotask::impl::task_impl::kill(), and LIBCOPP_COTASK_API.
Referenced by cotask::impl::task_impl::kill(), and cotask::task< TCO_MACRO >::kill().
kill() [4/4]
template<typename TCO_MACRO = macro_coroutine> virtual int cotask::task< TCO_MACRO >::kill (enum EN_TASK_STATUS status, void * priv_data) inline virtual
Implements cotask::impl::task_impl.
Definition at line 667 of file task.h.
References cotask::impl::task_impl::cancel(), copp::COPP_EC_SUCCESS, cotask::EN_TS_RUNNING, cotask::impl::task_impl::kill(), likely, cotask::impl::task_impl::resume(), cotask::impl::task_impl::start(), and cotask::impl::task_impl::yield().
next() [1/7]
template<typename TCO_MACRO = macro_coroutine> ptr_t cotask::task< TCO_MACRO >::next (ptr_t next_task, void * priv_data = UTIL_CONFIG_NULLPTR) inline
add next task to run when task finished
Note
please not to make tasks refer to each other. [it will lead to memory leak]
[don't do that] ptr_t a = ..., b = ...; a.next(b); b.next(a);
Parameters
next_task next stack
priv_data priv_data passed to resume or start next stack
Returns
next_task if success , or self if failed
Definition at line 291 of file task.h.
References cotask::EN_TS_CREATED, cotask::EN_TS_WAITING, and libcopp::util::intrusive_ptr< T >::get().
next() [2/7]
template<typename TCO_MACRO = macro_coroutine> template<typename Ty > ptr_t cotask::task< TCO_MACRO >::next (const Ty & functor, void * priv_data = UTIL_CONFIG_NULLPTR, size_t stack_size = 0, size_t private_buffer_size = 0) inline
create next task with functor
See also
next
Parameters
functor
priv_data priv_data passed to start functor
stack_size stack size
Returns
the created task if success , or self if failed
Definition at line 338 of file task.h.
next() [3/7]
template<typename TCO_MACRO = macro_coroutine> template<typename Ty > ptr_t cotask::task< TCO_MACRO >::next (const Ty & functor, typename coroutine_t::allocator_type & alloc, void * priv_data = UTIL_CONFIG_NULLPTR, size_t stack_size = 0, size_t private_buffer_size = 0) inline
Definition at line 343 of file task.h.
next() [4/7]
template<typename TCO_MACRO = macro_coroutine> template<typename Ty > ptr_t cotask::task< TCO_MACRO >::next (Ty(*)(void *) func, void * priv_data = UTIL_CONFIG_NULLPTR, size_t stack_size = 0, size_t private_buffer_size = 0) inline
create next task with function
See also
next
Parameters
func function
priv_data priv_data passed to start function
stack_size stack size
Returns
the created task if success , or self if failed
Definition at line 358 of file task.h.
next() [5/7]
template<typename TCO_MACRO = macro_coroutine> template<typename Ty > ptr_t cotask::task< TCO_MACRO >::next (Ty(*)(void *) func, typename coroutine_t::allocator_type & alloc, void * priv_data = UTIL_CONFIG_NULLPTR, size_t stack_size = 0, size_t private_buffer_size = 0) inline
Definition at line 364 of file task.h.
next() [6/7]
template<typename TCO_MACRO = macro_coroutine> template<typename Ty , typename TInst > ptr_t cotask::task< TCO_MACRO >::next (TyTInst::* func, TInst * instance, void * priv_data = UTIL_CONFIG_NULLPTR, size_t stack_size = 0, size_t private_buffer_size = 0) inline
create next task with function
See also
next
Parameters
func member function
instance instance
priv_data priv_data passed to start (instance->*func)(priv_data)
stack_size stack size
Returns
the created task if success , or self if failed
Definition at line 379 of file task.h.
next() [7/7]
template<typename TCO_MACRO = macro_coroutine> template<typename Ty , typename TInst > ptr_t cotask::task< TCO_MACRO >::next (TyTInst::* func, TInst * instance, typename coroutine_t::allocator_type & alloc, void * priv_data = UTIL_CONFIG_NULLPTR, size_t stack_size = 0, size_t private_buffer_size = 0) inline
Definition at line 385 of file task.h.
on_finished()
LIBCOPP_COTASK_API int cotask::impl::task_impl::on_finished () virtual inherited
Definition at line 51 of file task_impl.cpp.
Referenced by cotask::impl::task_impl::_notify_finished().
resume() [1/2]
UTIL_FORCEINLINE int cotask::impl::task_impl::resume () inline inherited
Definition at line 116 of file task_impl.h.
References cotask::impl::task_impl::resume().
Referenced by cotask::task< TCO_MACRO >::kill(), and cotask::impl::task_impl::resume().
resume() [2/2]
template<typename TCO_MACRO = macro_coroutine> virtual int cotask::task< TCO_MACRO >::resume (void * priv_data, EN_TASK_STATUS expected_status = EN_TS_WAITING) inline virtual
Implements cotask::impl::task_impl.
Definition at line 610 of file task.h.
start() [1/2]
UTIL_FORCEINLINE int cotask::impl::task_impl::start () inline inherited
Definition at line 115 of file task_impl.h.
References cotask::impl::task_impl::start().
Referenced by cotask::task< TCO_MACRO >::kill(), and cotask::impl::task_impl::start().
start() [2/2]
template<typename TCO_MACRO = macro_coroutine> virtual int cotask::task< TCO_MACRO >::start (void * priv_data, EN_TASK_STATUS expected_status = EN_TS_CREATED) inline virtual
Implements cotask::impl::task_impl.
Definition at line 529 of file task.h.
References copp::COPP_EC_ALREADY_FINISHED, copp::COPP_EC_IS_RUNNING, copp::COPP_EC_NOT_INITED, cotask::EN_TS_DONE, cotask::EN_TS_RUNNING, cotask::EN_TS_WAITING, LIBCOPP_MACRO_NOEXCEPT, likely, and unlikely.
sub_buffer_offset()
template<typename TCO_MACRO = macro_coroutine> static void* cotask::task< TCO_MACRO >::sub_buffer_offset (void * in, size_t off) inline static
Definition at line 713 of file task.h.
then() [1/3]
template<typename TCO_MACRO = macro_coroutine> ptr_t cotask::task< TCO_MACRO >::then (ptr_t next_task, void * priv_data = UTIL_CONFIG_NULLPTR) inline
add task to run when task finished
Note
please not to make tasks refer to each other. [it will lead to memory leak]
[don't do that] ptr_t a = ..., b = ...; a.then(b); b.then(a);
Parameters
next_task then stack
priv_data priv_data passed to resume or start the stack
Returns
next_task if success , or self if failed
Definition at line 450 of file task.h.
then() [2/3]
template<typename TCO_MACRO = macro_coroutine> template<typename Ty > ptr_t cotask::task< TCO_MACRO >::then (const Ty & functor, typename coroutine_t::allocator_type & alloc, void * priv_data = UTIL_CONFIG_NULLPTR, size_t stack_size = 0, size_t private_buffer_size = 0) inline
create next task with functor using the same allocator and private buffer size as this task
See also
next
Parameters
functor
priv_data priv_data passed to start functor
Returns
the created task if success , or self if failed
Definition at line 471 of file task.h.
then() [3/3]
template<typename TCO_MACRO = macro_coroutine> template<typename Ty > ptr_t cotask::task< TCO_MACRO >::then (Ty(*)(void *) func, void * priv_data = UTIL_CONFIG_NULLPTR) inline
Definition at line 482 of file task.h.
this_task()
template<typename TCO_MACRO = macro_coroutine> static self_t* cotask::task< TCO_MACRO >::this_task () inline static
get current running task and convert to task object
Returns
task smart pointer
Definition at line 495 of file task.h.
References cotask::impl::task_impl::this_task().
use_count()
template<typename TCO_MACRO = macro_coroutine> size_t cotask::task< TCO_MACRO >::use_count () const inline
Definition at line 734 of file task.h.
References LIBCOPP_MACRO_NOEXCEPT, and UTIL_FORCEINLINE.
yield() [1/2]
UTIL_FORCEINLINE int cotask::impl::task_impl::yield () inline inherited
Definition at line 117 of file task_impl.h.
References cotask::impl::task_impl::yield().
Referenced by cotask::task< TCO_MACRO >::kill(), and cotask::impl::task_impl::yield().
yield() [2/2]
template<typename TCO_MACRO = macro_coroutine> virtual int cotask::task< TCO_MACRO >::yield (void ** priv_data) inline virtual
Implements cotask::impl::task_impl.
Definition at line 615 of file task.h.
References copp::COPP_EC_NOT_INITED, and LIBCOPP_MACRO_NOEXCEPT.
Friends And Related Function Documentation
intrusive_ptr_add_ref
template<typename TCO_MACRO = macro_coroutine> void intrusive_ptr_add_ref (self_t * p) friend
Definition at line 850 of file task.h.
intrusive_ptr_release
template<typename TCO_MACRO = macro_coroutine> void intrusive_ptr_release (self_t * p) friend
Definition at line 858 of file task.h.
Field Documentation
action_destroy_fn_
template<typename TCO_MACRO = macro_coroutine> void(* cotask::task< TCO_MACRO >::action_destroy_fn_) (void *) private
Definition at line 976 of file task.h.
coroutine_obj_
template<typename TCO_MACRO = macro_coroutine> coroutine_t::ptr_t cotask::task< TCO_MACRO >::coroutine_obj_ private
Definition at line 972 of file task.h.
finish_priv_data_
void* cotask::impl::task_impl::finish_priv_data_ protected inherited
Definition at line 162 of file task_impl.h.
Referenced by cotask::impl::task_impl::_notify_finished().
inner_action_lock_
template<typename TCO_MACRO = macro_coroutine> libcopp::util::lock::spin_lock cotask::task< TCO_MACRO >::inner_action_lock_ private
ref_count
Definition at line 980 of file task.h.
next_list_
template<typename TCO_MACRO = macro_coroutine> task_group cotask::task< TCO_MACRO >::next_list_ private
Definition at line 973 of file task.h.
ref_count_
template<typename TCO_MACRO = macro_coroutine> libcopp::util::lock::atomic_int_type<size_t> cotask::task< TCO_MACRO >::ref_count_ private
Definition at line 979 of file task.h.
stack_size_
template<typename TCO_MACRO = macro_coroutine> size_t cotask::task< TCO_MACRO >::stack_size_ private
Definition at line 971 of file task.h.
The documentation for this class was generated from the following file:
/home/travis/build/owt5008137/libcopp/include/libcotask/task.h