libcopp: copp::future::result_base_t< TOK, TERR, false > Class Template Reference
copp::future::result_base_t< TOK, TERR, false > Class Template Reference
#include <storage.h>
Public Types
enum mode_t { EN_RESULT_SUCCESS = 0, EN_RESULT_ERROR = 1, EN_RESULT_NONE = 2 }
typedef TOK success_type
typedef TERR error_type
Public Member Functions
UTIL_FORCEINLINE bool is_success () const LIBCOPP_MACRO_NOEXCEPT
UTIL_FORCEINLINE bool is_error () const LIBCOPP_MACRO_NOEXCEPT
UTIL_FORCEINLINE const success_type * get_success () const LIBCOPP_MACRO_NOEXCEPT
UTIL_FORCEINLINE success_type * get_success () LIBCOPP_MACRO_NOEXCEPT
UTIL_FORCEINLINE const error_type * get_error () const LIBCOPP_MACRO_NOEXCEPT
UTIL_FORCEINLINE error_type * get_error () LIBCOPP_MACRO_NOEXCEPT
result_base_t ()
~result_base_t ()
result_base_t (result_base_t &&other)
result_base_t & operator= (result_base_t &&other)
void swap (result_base_t &other) LIBCOPP_MACRO_NOEXCEPT
Private Types
typedef default_compact_storage_t< success_type >::type success_storage_type
typedef default_compact_storage_t< error_type >::type error_storage_type
Private Member Functions
template<class... TARGS>
void construct_success (TARGS &&... args)
template<class... TARGS>
void construct_error (TARGS &&... args)
template<class... TARGS>
void make_success_base (TARGS &&... args)
template<class... TARGS>
void make_error_base (TARGS &&... args)
void reset ()
Static Private Member Functions
template<class TSTORAGE , class... TARGS>
static void make_object (typename TSTORAGE::storage_type &out, TARGS &&... args)
template<class TSTORAGE , class... TARGS>
static void make_object (std::shared_ptr< typename TSTORAGE::storage_type > &out, TARGS &&... args)
Private Attributes
success_storage_type::storage_type success_data_
error_storage_type::storage_type error_data_
mode_t mode_
Friends
template<class UOK , class UERR >
class result_t
template<class TRESULT , bool >
struct _make_result_instance_helper
UTIL_FORCEINLINE void swap (result_base_t &l, result_base_t &r) LIBCOPP_MACRO_NOEXCEPT
Detailed Description
template<class TOK, class TERR>
class copp::future::result_base_t< TOK, TERR, false >
Definition at line 419 of file storage.h.
Member Typedef Documentation
error_storage_type
template<class TOK , class TERR > typedef default_compact_storage_t<error_type>::type copp::future::result_base_t< TOK, TERR, false >::error_storage_type private
Definition at line 527 of file storage.h.
error_type
template<class TOK , class TERR > typedef TERR copp::future::result_base_t< TOK, TERR, false >::error_type
Definition at line 422 of file storage.h.
success_storage_type
template<class TOK , class TERR > typedef default_compact_storage_t<success_type>::type copp::future::result_base_t< TOK, TERR, false >::success_storage_type private
Definition at line 526 of file storage.h.
success_type
template<class TOK , class TERR > typedef TOK copp::future::result_base_t< TOK, TERR, false >::success_type
Definition at line 421 of file storage.h.
Member Enumeration Documentation
mode_t
template<class TOK , class TERR > enum copp::future::result_base_t< TOK, TERR, false >::mode_t
Enumerator
EN_RESULT_SUCCESS
EN_RESULT_ERROR
EN_RESULT_NONE
Definition at line 423 of file storage.h.
Constructor & Destructor Documentation
result_base_t() [1/2]
template<class TOK , class TERR > copp::future::result_base_t< TOK, TERR, false >::result_base_t () inline
Definition at line 443 of file storage.h.
~result_base_t()
template<class TOK , class TERR > copp::future::result_base_t< TOK, TERR, false >::~result_base_t () inline
Definition at line 447 of file storage.h.
result_base_t() [2/2]
template<class TOK , class TERR > copp::future::result_base_t< TOK, TERR, false >::result_base_t (result_base_t< TOK, TERR, false > && other) inline
Definition at line 449 of file storage.h.
References libcopp::util::swap().
Member Function Documentation
construct_error()
template<class TOK , class TERR > template<class... TARGS> void copp::future::result_base_t< TOK, TERR, false >::construct_error (TARGS &&... args) inline private
Definition at line 485 of file storage.h.
construct_success()
template<class TOK , class TERR > template<class... TARGS> void copp::future::result_base_t< TOK, TERR, false >::construct_success (TARGS &&... args) inline private
Definition at line 478 of file storage.h.
get_error() [1/2]
template<class TOK , class TERR > UTIL_FORCEINLINE const error_type* copp::future::result_base_t< TOK, TERR, false >::get_error () const inline
Definition at line 438 of file storage.h.
get_error() [2/2]
template<class TOK , class TERR > UTIL_FORCEINLINE error_type* copp::future::result_base_t< TOK, TERR, false >::get_error () inline
Definition at line 441 of file storage.h.
get_success() [1/2]
template<class TOK , class TERR > UTIL_FORCEINLINE const success_type* copp::future::result_base_t< TOK, TERR, false >::get_success () const inline
Definition at line 432 of file storage.h.
get_success() [2/2]
template<class TOK , class TERR > UTIL_FORCEINLINE success_type* copp::future::result_base_t< TOK, TERR, false >::get_success () inline
Definition at line 435 of file storage.h.
is_error()
template<class TOK , class TERR > UTIL_FORCEINLINE bool copp::future::result_base_t< TOK, TERR, false >::is_error () const inline
Definition at line 430 of file storage.h.
is_success()
template<class TOK , class TERR > UTIL_FORCEINLINE bool copp::future::result_base_t< TOK, TERR, false >::is_success () const inline
Definition at line 429 of file storage.h.
make_error_base()
template<class TOK , class TERR > template<class... TARGS> void copp::future::result_base_t< TOK, TERR, false >::make_error_base (TARGS &&... args) inline private
Definition at line 499 of file storage.h.
make_object() [1/2]
template<class TOK , class TERR > template<class TSTORAGE , class... TARGS> static void copp::future::result_base_t< TOK, TERR, false >::make_object (typename TSTORAGE::storage_type & out, TARGS &&... args) inline static private
Definition at line 517 of file storage.h.
make_object() [2/2]
template<class TOK , class TERR > template<class TSTORAGE , class... TARGS> static void copp::future::result_base_t< TOK, TERR, false >::make_object (std::shared_ptr< typename TSTORAGE::storage_type > & out, TARGS &&... args) inline static private
Definition at line 522 of file storage.h.
make_success_base()
template<class TOK , class TERR > template<class... TARGS> void copp::future::result_base_t< TOK, TERR, false >::make_success_base (TARGS &&... args) inline private
Definition at line 492 of file storage.h.
operator=()
template<class TOK , class TERR > result_base_t& copp::future::result_base_t< TOK, TERR, false >::operator= (result_base_t< TOK, TERR, false > && other) inline
Definition at line 456 of file storage.h.
References libcopp::util::swap().
reset()
template<class TOK , class TERR > void copp::future::result_base_t< TOK, TERR, false >::reset () inline private
Definition at line 505 of file storage.h.
swap()
template<class TOK , class TERR > void copp::future::result_base_t< TOK, TERR, false >::swap (result_base_t< TOK, TERR, false > & other) inline
Definition at line 462 of file storage.h.
References libcopp::util::swap().
Friends And Related Function Documentation
_make_result_instance_helper
template<class TOK , class TERR > template<class TRESULT , bool > friend struct _make_result_instance_helper friend
Definition at line 475 of file storage.h.
result_t
template<class TOK , class TERR > template<class UOK , class UERR > friend class result_t friend
Definition at line 473 of file storage.h.
swap
template<class TOK , class TERR > UTIL_FORCEINLINE void swap (result_base_t< TOK, TERR, false > & l, result_base_t< TOK, TERR, false > & r) friend
Definition at line 469 of file storage.h.
Field Documentation
error_data_
template<class TOK , class TERR > error_storage_type::storage_type copp::future::result_base_t< TOK, TERR, false >::error_data_ private
Definition at line 530 of file storage.h.
mode_
template<class TOK , class TERR > mode_t copp::future::result_base_t< TOK, TERR, false >::mode_ private
Definition at line 531 of file storage.h.
success_data_
template<class TOK , class TERR > success_storage_type::storage_type copp::future::result_base_t< TOK, TERR, false >::success_data_ private
Definition at line 529 of file storage.h.
The documentation for this class was generated from the following file:
/home/travis/build/owt5008137/libcopp/include/libcopp/future/storage.h