libcopp: /home/travis/build/owt5008137/libcopp/sample/sample_default_coroutine_context.cpp File Reference
sample_default_coroutine_context.cpp File Reference
#include <cstdio>
#include <cstring>
#include <inttypes.h>
#include <iostream>
#include <stdint.h>
#include <libcopp/coroutine/coroutine_context_container.h>
Data Structures
class my_runner
Functions
int main ()
Function Documentation
main()
int main ()
Definition at line 35 of file sample_default_coroutine_context.cpp.
References copp::coroutine_context_container< TALLOC >::create(), libcopp::util::intrusive_ptr< T >::get(), and my_runner().