libcopp: /home/travis/build/owt5008137/libcopp/test/case/coroutine_context_base_test.cpp File Reference
coroutine_context_base_test.cpp File Reference
#include <cstdio>
#include <cstring>
#include <iostream>
#include "frame/test_macros.h"
#include <libcopp/coroutine/coroutine_context_container.h>
Data Structures
class test_context_base_foo_runner
Typedefs
typedef copp::coroutine_context_container< copp::allocator::stack_allocator_memory > test_context_base_coroutine_context_test_type
Functions
CASE_TEST (coroutine, context_base)
CASE_TEST (coroutine, shared_runner)
CASE_TEST (coroutine, coroutine_context_container_create_failed)
CASE_TEST (coroutine, coroutine_context_create_failed)
Variables
static int g_test_coroutine_base_status = 0
Typedef Documentation
test_context_base_coroutine_context_test_type
typedef copp::coroutine_context_container<copp::allocator::stack_allocator_memory> test_context_base_coroutine_context_test_type
Definition at line 9 of file coroutine_context_base_test.cpp.
Function Documentation
CASE_TEST() [1/4]
CASE_TEST (coroutine , context_base)
Definition at line 27 of file coroutine_context_base_test.cpp.
References copp::allocator::stack_allocator_memory::allocate(), copp::allocator::stack_allocator_memory::attach(), test_context_base_foo_runner::call_times, CASE_EXPECT_EQ, CASE_EXPECT_TRUE, copp::COPP_EC_ALREADY_EXIST, copp::COPP_EC_NOT_READY, copp::COPP_EC_NOT_RUNNING, copp::coroutine_context_container< TALLOC >::create(), g_test_coroutine_base_status, and copp::stack_context::sp.
Referenced by CASE_TEST().
CASE_TEST() [2/4]
CASE_TEST (coroutine , shared_runner)
Definition at line 100 of file coroutine_context_base_test.cpp.
References test_context_base_foo_runner::call_times, CASE_EXPECT_EQ, copp::coroutine_context_container< TALLOC >::create(), and g_test_coroutine_base_status.
CASE_TEST() [3/4]
CASE_TEST (coroutine , coroutine_context_container_create_failed)
Definition at line 132 of file coroutine_context_base_test.cpp.
References copp::allocator::stack_allocator_memory::allocate(), CASE_EXPECT_EQ, CASE_EXPECT_TRUE, copp::coroutine_context_container< TALLOC >::create(), and copp::stack_context::sp.
CASE_TEST() [4/4]
CASE_TEST (coroutine , coroutine_context_create_failed)
Definition at line 154 of file coroutine_context_base_test.cpp.
References copp::allocator::stack_allocator_memory::allocate(), CASE_EXPECT_EQ, CASE_EXPECT_TRUE, CASE_MSG_INFO, CASE_TEST(), copp::COPP_EC_ARGS_ERROR, copp::COPP_EC_NOT_RUNNING, copp::coroutine_context_container< TALLOC >::create(), copp::coroutine_context::create(), copp::stack_context::size, and copp::stack_context::sp.
Variable Documentation
g_test_coroutine_base_status
int g_test_coroutine_base_status = 0 static
Definition at line 11 of file coroutine_context_base_test.cpp.
Referenced by CASE_TEST(), and test_context_base_foo_runner::operator()().