libcopp: copp::detail Namespace Reference
copp::detail Namespace Reference
Functions
static void init_pthread_this_coroutine_context ()
static void set_this_coroutine_context (coroutine_context_base *p)
static coroutine_context_base * get_this_coroutine_context ()
static std::size_t pagesize ()
static rlimit stacksize_limit_ ()
static rlimit stacksize_limit ()
static void system_info_ (SYSTEM_INFO *si)
static SYSTEM_INFO system_info ()
static std::size_t pagesize ()
Variables
static pthread_once_t gt_coroutine_init_once = PTHREAD_ONCE_INIT
static pthread_key_t gt_coroutine_tls_key
Function Documentation
get_this_coroutine_context()
static coroutine_context_base* copp::detail::get_this_coroutine_context () inline static
Definition at line 53 of file coroutine_context.cpp.
References init_pthread_this_coroutine_context().
Referenced by copp::this_coroutine::get_coroutine(), copp::coroutine_context_base::get_this_coroutine_base(), copp::coroutine_context::start(), and copp::this_coroutine::yield().
init_pthread_this_coroutine_context()
static void copp::detail::init_pthread_this_coroutine_context () static
Definition at line 41 of file coroutine_context.cpp.
Referenced by get_this_coroutine_context(), and set_this_coroutine_context().
pagesize() [1/2]
static std::size_t copp::detail::pagesize () static
Definition at line 32 of file stack_traits_posix.cpp.
Referenced by copp::stack_traits::page_size(), pagesize(), and copp::stack_traits::round_to_page_size().
pagesize() [2/2]
static std::size_t copp::detail::pagesize () static
Definition at line 74 of file stack_traits_windows.cpp.
References copp::stack_traits::default_size(), copp::stack_traits::is_unbounded(), LIBCOPP_COPP_API, LIBCOPP_MACRO_NOEXCEPT, copp::stack_traits::maximum_size(), MIN_STACKSIZE, copp::stack_traits::minimum_size(), copp::stack_traits::page_size(), pagesize(), copp::stack_traits::round_to_page_size(), and system_info().
set_this_coroutine_context()
static void copp::detail::set_this_coroutine_context (coroutine_context_base * p) inline static
Definition at line 44 of file coroutine_context.cpp.
References init_pthread_this_coroutine_context().
Referenced by copp::libcopp_inner_api_helper::coroutine_context_callback(), copp::jump_to(), and copp::coroutine_context_base::set_this_coroutine_base().
stacksize_limit()
static rlimit copp::detail::stacksize_limit () static
Definition at line 44 of file stack_traits_posix.cpp.
References stacksize_limit_().
Referenced by copp::stack_traits::is_unbounded(), and copp::stack_traits::maximum_size().
stacksize_limit_()
static rlimit copp::detail::stacksize_limit_ () static
Definition at line 37 of file stack_traits_posix.cpp.
Referenced by stacksize_limit().
system_info()
static SYSTEM_INFO copp::detail::system_info () static
Definition at line 52 of file stack_traits_windows.cpp.
References system_info_().
Referenced by pagesize().
system_info_()
static void copp::detail::system_info_ (SYSTEM_INFO * si) static
Definition at line 50 of file stack_traits_windows.cpp.
Referenced by system_info().
Variable Documentation
gt_coroutine_init_once
pthread_once_t copp::detail::gt_coroutine_init_once = PTHREAD_ONCE_INIT static
Definition at line 39 of file coroutine_context.cpp.
gt_coroutine_tls_key
pthread_key_t copp::detail::gt_coroutine_tls_key static
Definition at line 40 of file coroutine_context.cpp.