libcopp: copp::allocator::stack_allocator_memory Class Reference
copp::allocator::stack_allocator_memory Class Reference
memory allocator this allocator will return address of specified memory section
#include <stack_allocator_memory.h>
Public Member Functions
stack_allocator_memory () LIBCOPP_MACRO_NOEXCEPT
stack_allocator_memory (void *start_ptr, std::size_t max_size) LIBCOPP_MACRO_NOEXCEPT
stack_allocator_memory (stack_allocator_memory &other) LIBCOPP_MACRO_NOEXCEPT
~stack_allocator_memory ()
stack_allocator_memory & operator= (stack_allocator_memory &other) LIBCOPP_MACRO_NOEXCEPT
void swap (stack_allocator_memory &other)
void attach (void *start_ptr, std::size_t max_size) LIBCOPP_MACRO_NOEXCEPT
void allocate (stack_context &ctx, std::size_t size) LIBCOPP_MACRO_NOEXCEPT
void deallocate (stack_context &ctx) LIBCOPP_MACRO_NOEXCEPT
Private Attributes
void * start_ptr_
std::size_t memory_size_
bool is_used_
Detailed Description
memory allocator this allocator will return address of specified memory section
Definition at line 25 of file stack_allocator_memory.h.
Constructor & Destructor Documentation
stack_allocator_memory() [1/3]
LIBCOPP_COPP_API copp::allocator::stack_allocator_memory::stack_allocator_memory ()
Definition at line 25 of file stack_allocator_memory.cpp.
stack_allocator_memory() [2/3]
LIBCOPP_COPP_API copp::allocator::stack_allocator_memory::stack_allocator_memory (void * start_ptr, std::size_t max_size)
construct and attach to start_ptr with size of max_size
Parameters
start_ptr buffer start address
max_size buffer size
Definition at line 30 of file stack_allocator_memory.cpp.
stack_allocator_memory() [3/3]
LIBCOPP_COPP_API copp::allocator::stack_allocator_memory::stack_allocator_memory (stack_allocator_memory & other)
Definition at line 36 of file stack_allocator_memory.cpp.
References libcopp::util::swap().
~stack_allocator_memory()
LIBCOPP_COPP_API copp::allocator::stack_allocator_memory::~stack_allocator_memory ()
Definition at line 56 of file stack_allocator_memory.cpp.
Member Function Documentation
allocate()
LIBCOPP_COPP_API void copp::allocator::stack_allocator_memory::allocate (stack_context & ctx, std::size_t size)
allocate memory and attach to stack context [standard function]
Parameters
ctx stack context
size stack size
Note
size must less or equal than attached
Definition at line 88 of file stack_allocator_memory.cpp.
References copp::stack_traits::maximum_size(), copp::stack_traits::minimum_size(), and copp::stack_traits::round_to_page_size().
Referenced by CASE_TEST().
attach()
LIBCOPP_COPP_API void copp::allocator::stack_allocator_memory::attach (void * start_ptr, std::size_t max_size)
specify memory section allocated
Parameters
start_ptr buffer start address
max_size buffer size
Note
must be called before allocate operation
Definition at line 82 of file stack_allocator_memory.cpp.
Referenced by CASE_TEST().
deallocate()
LIBCOPP_COPP_API void copp::allocator::stack_allocator_memory::deallocate (stack_context & ctx)
deallocate memory from stack context [standard function]
Parameters
ctx stack context
Definition at line 110 of file stack_allocator_memory.cpp.
References copp::stack_traits::is_unbounded(), copp::stack_traits::maximum_size(), and copp::stack_traits::minimum_size().
operator=()
LIBCOPP_COPP_API stack_allocator_memory & copp::allocator::stack_allocator_memory::operator= (stack_allocator_memory & other)
Definition at line 58 of file stack_allocator_memory.cpp.
References libcopp::util::swap().
swap()
LIBCOPP_COPP_API void copp::allocator::stack_allocator_memory::swap (stack_allocator_memory & other)
Definition at line 75 of file stack_allocator_memory.cpp.
References is_used_, memory_size_, start_ptr_, and libcopp::util::swap().
Field Documentation
is_used_
bool copp::allocator::stack_allocator_memory::is_used_ private
Definition at line 29 of file stack_allocator_memory.h.
Referenced by swap().
memory_size_
std::size_t copp::allocator::stack_allocator_memory::memory_size_ private
Definition at line 28 of file stack_allocator_memory.h.
Referenced by swap().
start_ptr_
void* copp::allocator::stack_allocator_memory::start_ptr_ private
Definition at line 27 of file stack_allocator_memory.h.
Referenced by swap().
The documentation for this class was generated from the following files:
/home/runner/work/libcopp/libcopp/include/libcopp/stack/allocator/stack_allocator_memory.h
/home/runner/work/libcopp/libcopp/src/libcopp/stack/allocator/stack_allocator_memory.cpp