libcopp: copp::stack_context Struct Reference
copp::stack_context Struct Reference
#include <stack_context.h>
Public Member Functions
stack_context () LIBCOPP_MACRO_NOEXCEPT
stack end pointer
~stack_context () LIBCOPP_MACRO_NOEXCEPT
stack_context (const stack_context &other) LIBCOPP_MACRO_NOEXCEPT
stack_context & operator= (const stack_context &other) LIBCOPP_MACRO_NOEXCEPT
void reset () LIBCOPP_MACRO_NOEXCEPT
void copy_from (const stack_context &other) LIBCOPP_MACRO_NOEXCEPT
Data Fields
size_t size
void * sp
stack size
Detailed Description
Definition at line 14 of file stack_context.h.
Constructor & Destructor Documentation
stack_context() [1/2]
LIBCOPP_COPP_API copp::stack_context::stack_context ()
stack end pointer
Definition at line 8 of file stack_context.cpp.
Referenced by operator=().
~stack_context()
LIBCOPP_COPP_API copp::stack_context::~stack_context ()
Definition at line 22 of file stack_context.cpp.
stack_context() [2/2]
LIBCOPP_COPP_API copp::stack_context::stack_context (const stack_context & other)
Definition at line 24 of file stack_context.cpp.
References copy_from().
Member Function Documentation
copy_from()
LIBCOPP_COPP_API void copp::stack_context::copy_from (const stack_context & other)
Definition at line 56 of file stack_context.cpp.
References sp.
Referenced by operator=(), and stack_context().
operator=()
LIBCOPP_COPP_API stack_context & copp::stack_context::operator= (const stack_context & other)
Definition at line 26 of file stack_context.cpp.
References copy_from(), LIBCOPP_COPP_API, LIBCOPP_MACRO_NOEXCEPT, and stack_context().
reset()
LIBCOPP_COPP_API void copp::stack_context::reset ()
Definition at line 45 of file stack_context.cpp.
References sp.
Referenced by CASE_TEST().
Field Documentation
size
size_t copp::stack_context::size
Definition at line 15 of file stack_context.h.
Referenced by CASE_TEST().
sp
void* copp::stack_context::sp
stack size
Definition at line 16 of file stack_context.h.
Referenced by CASE_TEST(), copy_from(), copp::coroutine_context_container< TALLOC >::create(), and reset().
The documentation for this struct was generated from the following files:
/home/travis/build/owt5008137/libcopp/include/libcopp/stack/stack_context.h
/home/travis/build/owt5008137/libcopp/src/libcopp/stack/stack_context.cpp