libcopp: test_future_void_context_poll_functor< T > Struct Template Reference
test_future_void_context_poll_functor< T > Struct Template Reference
Public Member Functions
template<class U >
test_future_void_context_poll_functor (int32_t d, U in)
void operator() (copp::future::context_t< void > &ctx, copp::future::context_t< void >::poll_event_data_t evt)
Static Public Member Functions
static void on_destroy (copp::future::context_t< void > &ctx)
Data Fields
T data
int32_t delay
Detailed Description
template<class T>
struct test_future_void_context_poll_functor< T >
Definition at line 203 of file future_and_std_coroutine_test.cpp.
Constructor & Destructor Documentation
test_future_void_context_poll_functor()
template<class T > template<class U > test_future_void_context_poll_functor< T >::test_future_void_context_poll_functor (int32_t d, U in) inline
Definition at line 240 of file future_and_std_coroutine_test.cpp.
Member Function Documentation
on_destroy()
template<class T > static void test_future_void_context_poll_functor< T >::on_destroy (copp::future::context_t< void > & ctx) inline static
Definition at line 242 of file future_and_std_coroutine_test.cpp.
References CASE_MSG_INFO.
operator()()
template<class T > void test_future_void_context_poll_functor< T >::operator() (copp::future::context_t< void > & ctx, copp::future::context_t< void >::poll_event_data_t evt) inline
Definition at line 246 of file future_and_std_coroutine_test.cpp.
References CASE_MSG_INFO, test_no_trivial_parent_clazz::data, copp::future::future_t< T, TPTR >::poll_data(), copp::future::context_t< void >::set_on_destroy(), and test_future_trivial_name().
Field Documentation
data
template<class T > T test_future_void_context_poll_functor< T >::data
Definition at line 236 of file future_and_std_coroutine_test.cpp.
delay
template<class T > int32_t test_future_void_context_poll_functor< T >::delay
Definition at line 237 of file future_and_std_coroutine_test.cpp.
The documentation for this struct was generated from the following file:
/home/travis/build/owt5008137/libcopp/test/case/future_and_std_coroutine_test.cpp