libcopp: /home/travis/build/owt5008137/libcopp/sample/sample_readme_1.cpp File Reference
sample_readme_1.cpp File Reference
#include <cstdio>
#include <cstring>
#include <inttypes.h>
#include <iostream>
#include <stdint.h>
#include <libcopp/coroutine/coroutine_context_container.h>
Functions
int my_runner (void *)
int main ()
Function Documentation
main()
int main ()
Definition at line 23 of file sample_readme_1.cpp.
my_runner()
int my_runner (void *)
Definition at line 11 of file sample_readme_1.cpp.
References copp::this_coroutine::get_coroutine(), and copp::coroutine_context::yield().
Referenced by main().