libcopp: copp::fcontext Namespace Reference
copp::fcontext Namespace Reference
Data Structures
struct fcontext_t
struct fp_t
struct stack_t
struct transfer_t
Typedefs
typedef void * fcontext_t
Functions
COPP_BOOST_CONTEXT_DECL transfer_t COPP_BOOST_CONTEXT_CALLDECL copp_jump_fcontext (fcontext_t const to, void *vp)
COPP_BOOST_CONTEXT_DECL fcontext_t COPP_BOOST_CONTEXT_CALLDECL copp_make_fcontext (void *sp, std::size_t size, void(*fn)(transfer_t))
COPP_BOOST_CONTEXT_DECL transfer_t COPP_BOOST_CONTEXT_CALLDECL copp_ontop_fcontext (fcontext_t const to, void *vp, transfer_t(*fn)(transfer_t))
Typedef Documentation
fcontext_t
typedef void* copp::fcontext::fcontext_t
Definition at line 30 of file fcontext.hpp.
Function Documentation
copp_jump_fcontext()
COPP_BOOST_CONTEXT_DECL transfer_t COPP_BOOST_CONTEXT_CALLDECL copp::fcontext::copp_jump_fcontext (fcontext_t const to, void * vp)
Referenced by CASE_TEST(), copp::jump_to(), test_core_fcontext_func_a(), and test_core_fcontext_func_b().
copp_make_fcontext()
COPP_BOOST_CONTEXT_DECL fcontext_t COPP_BOOST_CONTEXT_CALLDECL copp::fcontext::copp_make_fcontext (void * sp, std::size_t size, void(*)(transfer_t) fn)
Referenced by CASE_TEST(), and copp::coroutine_context::create().
copp_ontop_fcontext()
COPP_BOOST_CONTEXT_DECL transfer_t COPP_BOOST_CONTEXT_CALLDECL copp::fcontext::copp_ontop_fcontext (fcontext_t const to, void * vp, transfer_t(*)(transfer_t) fn)