libcopp: test_on_start_base Class Reference
test_on_start_base Class Reference
#include <test_case_base.h>
Public Types
typedef void(* on_start_func) ()
Public Member Functions
typedef UTIL_UNIT_TEST_MACRO_AUTO_SET (std::string) after_set_t
test_on_start_base (const std::string &n, on_start_func func)
test_on_start_base (const std::string &n, on_start_func func, const std::string &dep1)
test_on_start_base (const std::string &n, on_start_func func, const std::string &dep1, const std::string &dep2)
test_on_start_base (const std::string &n, on_start_func func, const std::string &dep1, const std::string &dep2, const std::string &dep3)
test_on_start_base (const std::string &n, on_start_func func, const std::string &dep1, const std::string &dep2, const std::string &dep3, const std::string &dep4)
test_on_start_base (const std::string &n, on_start_func func, const std::string &dep1, const std::string &dep2, const std::string &dep3, const std::string &dep4, const std::string &dep5)
virtual ~test_on_start_base ()
virtual int run ()
Data Fields
std::string name
on_start_func func_
after_set_t after
Private Member Functions
void register_self ()
Detailed Description
Definition at line 55 of file test_case_base.h.
Member Typedef Documentation
on_start_func
typedef void(* test_on_start_base::on_start_func) ()
Definition at line 58 of file test_case_base.h.
Constructor & Destructor Documentation
test_on_start_base() [1/6]
test_on_start_base::test_on_start_base (const std::string & n, on_start_func func) inline
Definition at line 72 of file test_case_base.h.
References register_self().
test_on_start_base() [2/6]
test_on_start_base::test_on_start_base (const std::string & n, on_start_func func, const std::string & dep1) inline
Definition at line 73 of file test_case_base.h.
References after, and register_self().
test_on_start_base() [3/6]
test_on_start_base::test_on_start_base (const std::string & n, on_start_func func, const std::string & dep1, const std::string & dep2) inline
Definition at line 78 of file test_case_base.h.
References after, and register_self().
test_on_start_base() [4/6]
test_on_start_base::test_on_start_base (const std::string & n, on_start_func func, const std::string & dep1, const std::string & dep2, const std::string & dep3) inline
Definition at line 85 of file test_case_base.h.
References after, and register_self().
test_on_start_base() [5/6]
test_on_start_base::test_on_start_base (const std::string & n, on_start_func func, const std::string & dep1, const std::string & dep2, const std::string & dep3, const std::string & dep4) inline
Definition at line 94 of file test_case_base.h.
References after, and register_self().
test_on_start_base() [6/6]
test_on_start_base::test_on_start_base (const std::string & n, on_start_func func, const std::string & dep1, const std::string & dep2, const std::string & dep3, const std::string & dep4, const std::string & dep5) inline
Definition at line 104 of file test_case_base.h.
References after, and register_self().
~test_on_start_base()
test_on_start_base::~test_on_start_base () virtual
Definition at line 44 of file test_case_base.cpp.
Member Function Documentation
register_self()
void test_on_start_base::register_self () private
Definition at line 42 of file test_case_base.cpp.
References test_manager::append_event_on_start(), test_manager::me(), and name.
Referenced by test_on_start_base().
run()
int test_on_start_base::run () virtual
Definition at line 46 of file test_case_base.cpp.
References func_.
UTIL_UNIT_TEST_MACRO_AUTO_SET()
typedef test_on_start_base::UTIL_UNIT_TEST_MACRO_AUTO_SET (std::string)
Field Documentation
after
after_set_t test_on_start_base::after
Definition at line 122 of file test_case_base.h.
Referenced by test_on_start_base().
func_
on_start_func test_on_start_base::func_
Definition at line 121 of file test_case_base.h.
Referenced by run().
name
std::string test_on_start_base::name
Definition at line 120 of file test_case_base.h.
Referenced by register_self().
The documentation for this class was generated from the following files:
/home/runner/work/libcopp/libcopp/test/frame/test_case_base.h
/home/runner/work/libcopp/libcopp/test/frame/test_case_base.cpp