libcopp: copp::libcopp_inner_api_helper Struct Reference
copp::libcopp_inner_api_helper Struct Reference
Public Types
typedef coroutine_context::jump_src_data_t jump_src_data_t
Static Public Member Functions
static UTIL_FORCEINLINE void set_caller (coroutine_context *src, const fcontext::fcontext_t &fctx)
static UTIL_FORCEINLINE void set_callee (coroutine_context *src, const fcontext::fcontext_t &fctx)
static void coroutine_context_callback (::copp::fcontext::transfer_t src_ctx)
Detailed Description
Definition at line 131 of file coroutine_context.cpp.
Member Typedef Documentation
jump_src_data_t
typedef coroutine_context::jump_src_data_t copp::libcopp_inner_api_helper::jump_src_data_t
Definition at line 132 of file coroutine_context.cpp.
Member Function Documentation
coroutine_context_callback()
static void copp::libcopp_inner_api_helper::coroutine_context_callback (::copp::fcontext::transfer_t src_ctx) inline static
Definition at line 163 of file coroutine_context.cpp.
References copp::coroutine_context::callee_, copp::coroutine_context::caller_, copp::fcontext::transfer_t::data, copp::coroutine_context_base::flag_t::EN_CFT_FINISHED, copp::fcontext::transfer_t::fctx, copp::coroutine_context::flags_, copp::coroutine_context::jump_src_data_t::from_co, copp::coroutine_context::jump_src_data_t::priv_data, copp::coroutine_context_base::run_and_recv_retcode(), copp::detail::set_this_coroutine_context(), copp::coroutine_context::jump_src_data_t::to_co, and copp::coroutine_context::yield().
Referenced by copp::coroutine_context::create().
set_callee()
static UTIL_FORCEINLINE void copp::libcopp_inner_api_helper::set_callee (coroutine_context * src, const fcontext::fcontext_t & fctx) inline static
Definition at line 140 of file coroutine_context.cpp.
References copp::coroutine_context::callee_.
Referenced by copp::jump_to().
set_caller()
static UTIL_FORCEINLINE void copp::libcopp_inner_api_helper::set_caller (coroutine_context * src, const fcontext::fcontext_t & fctx) inline static
Definition at line 134 of file coroutine_context.cpp.
References copp::coroutine_context::caller_.
Referenced by copp::jump_to().
The documentation for this struct was generated from the following file:
/home/runner/work/libcopp/libcopp/src/libcopp/coroutine/coroutine_context.cpp