libcopp: /home/travis/build/owt5008137/libcopp/sample/sample_readme_4.cpp File Reference
sample_readme_4.cpp File Reference
#include <cstdio>
#include <cstring>
#include <ctime>
#include <inttypes.h>
#include <iostream>
#include <stdint.h>
#include <libcopp/stack/stack_pool.h>
#include <libcotask/task.h>
Data Structures
struct sample_macro_coroutine
Typedefs
typedef copp::stack_pool< copp::allocator::default_statck_allocator > stack_pool_t
typedef cotask::task< sample_macro_coroutine > sample_task_t
Functions
int main ()
Variables
static stack_pool_t::ptr_t global_stack_pool = stack_pool_t::create()
Typedef Documentation
sample_task_t
typedef cotask::task<sample_macro_coroutine> sample_task_t
Definition at line 24 of file sample_readme_4.cpp.
stack_pool_t
typedef copp::stack_pool<copp::allocator::default_statck_allocator> stack_pool_t
Definition at line 13 of file sample_readme_4.cpp.
Function Documentation
main()
int main ()
Definition at line 26 of file sample_readme_4.cpp.
References cotask::task< TCO_MACRO >::create(), cotask::this_task::get_task(), global_stack_pool, and cotask::impl::task_impl::yield().
Variable Documentation
global_stack_pool
stack_pool_t::ptr_t global_stack_pool = stack_pool_t::create() static
Definition at line 22 of file sample_readme_4.cpp.
Referenced by main().