libcopp: util::cli::ci_char_traits< Tc > Struct Template Reference
util::cli::ci_char_traits< Tc > Struct Template Reference
#include <cmd_option_string.h>
Static Public Member Functions
static bool eq (Tc left, Tc right)
static bool lt (Tc left, Tc right)
static int compare (const Tc *left, const Tc *right, size_t n)
static const Tc * find (const char *s, int n, Tc a)
Detailed Description
template<typename Tc>
struct util::cli::ci_char_traits< Tc >
功能受限的字符串类型处理类
Definition at line 19 of file cmd_option_string.h.
Member Function Documentation
compare()
template<typename Tc > static int util::cli::ci_char_traits< Tc >::compare (const Tc * left, const Tc * right, size_t n) inline static
Definition at line 23 of file cmd_option_string.h.
References util::string::toupper().
eq()
template<typename Tc > static bool util::cli::ci_char_traits< Tc >::eq (Tc left, Tc right) inline static
Definition at line 20 of file cmd_option_string.h.
References util::string::toupper().
find()
template<typename Tc > static const Tc* util::cli::ci_char_traits< Tc >::find (const char * s, int n, Tc a) inline static
Definition at line 36 of file cmd_option_string.h.
References util::string::toupper().
lt()
template<typename Tc > static bool util::cli::ci_char_traits< Tc >::lt (Tc left, Tc right) inline static
Definition at line 21 of file cmd_option_string.h.
References util::string::toupper().
The documentation for this struct was generated from the following file:
/home/travis/build/owt5008137/libcopp/test/cli/cmd_option_string.h