libcopp: libcopp::util::intrusive_ptr< T > Class Template Reference
libcopp::util::intrusive_ptr< T > Class Template Reference
#include <intrusive_ptr.h>
Public Types
typedef intrusive_ptr< T > self_type
typedef T element_type
Public Member Functions
UTIL_CONFIG_CONSTEXPR intrusive_ptr () LIBCOPP_MACRO_NOEXCEPT
intrusive_ptr (T *p, bool add_ref=true)
template<typename U >
intrusive_ptr (intrusive_ptr< U > const &rhs, typename std::enable_if< std::is_convertible< U *, T * >::value >::type *=NULL)
intrusive_ptr (self_type const &rhs)
~intrusive_ptr ()
template<typename U >
intrusive_ptr & operator= (intrusive_ptr< U > const &rhs)
self_type & operator= (self_type const &rhs)
void reset () LIBCOPP_MACRO_NOEXCEPT
void reset (element_type *rhs)
void reset (element_type *rhs, bool add_ref)
element_type * get () const LIBCOPP_MACRO_NOEXCEPT
element_type * detach () LIBCOPP_MACRO_NOEXCEPT
element_type & operator* () const
element_type * operator-> () const
operator bool () const LIBCOPP_MACRO_NOEXCEPT
bool operator! () const LIBCOPP_MACRO_NOEXCEPT
void swap (intrusive_ptr &rhs) LIBCOPP_MACRO_NOEXCEPT
Private Attributes
element_type * px
Friends
template<typename U >
class intrusive_ptr
Detailed Description
template<typename T>
class libcopp::util::intrusive_ptr< T >
Definition at line 50 of file intrusive_ptr.h.
Member Typedef Documentation
element_type
template<typename T > typedef T libcopp::util::intrusive_ptr< T >::element_type
Definition at line 53 of file intrusive_ptr.h.
self_type
template<typename T > typedef intrusive_ptr<T> libcopp::util::intrusive_ptr< T >::self_type
Definition at line 52 of file intrusive_ptr.h.
Constructor & Destructor Documentation
intrusive_ptr() [1/4]
template<typename T > UTIL_CONFIG_CONSTEXPR libcopp::util::intrusive_ptr< T >::intrusive_ptr () inline
Definition at line 55 of file intrusive_ptr.h.
intrusive_ptr() [2/4]
template<typename T > libcopp::util::intrusive_ptr< T >::intrusive_ptr (T * p, bool add_ref = true) inline
Definition at line 57 of file intrusive_ptr.h.
References libcopp::util::intrusive_ptr< T >::px.
intrusive_ptr() [3/4]
template<typename T > template<typename U > libcopp::util::intrusive_ptr< T >::intrusive_ptr (intrusive_ptr< U > const & rhs, typename std::enable_if< std::is_convertible< U *, T * >::value >::type * = NULL) inline
Definition at line 64 of file intrusive_ptr.h.
References libcopp::util::intrusive_ptr< T >::px.
intrusive_ptr() [4/4]
template<typename T > libcopp::util::intrusive_ptr< T >::intrusive_ptr (self_type const & rhs) inline
Definition at line 72 of file intrusive_ptr.h.
References libcopp::util::intrusive_ptr< T >::px.
~intrusive_ptr()
template<typename T > libcopp::util::intrusive_ptr< T >::~intrusive_ptr () inline
Definition at line 78 of file intrusive_ptr.h.
References libcopp::util::intrusive_ptr< T >::px.
Member Function Documentation
detach()
template<typename T > element_type* libcopp::util::intrusive_ptr< T >::detach () inline
Definition at line 131 of file intrusive_ptr.h.
References libcopp::util::intrusive_ptr< T >::px.
get()
template<typename T > element_type* libcopp::util::intrusive_ptr< T >::get () const inline
Definition at line 129 of file intrusive_ptr.h.
References libcopp::util::intrusive_ptr< T >::px.
Referenced by cotask::task< TCO_MACRO >::await_task(), CASE_TEST(), libcopp::util::const_pointer_cast(), copp::coroutine_context_container< TALLOC >::create(), cotask::task< TCO_MACRO >::create_with_delegate(), libcopp::util::get_pointer(), main(), cotask::task< TCO_MACRO >::next(), libcopp::util::operator<<(), and libcopp::util::static_pointer_cast().
operator bool()
template<typename T > libcopp::util::intrusive_ptr< T >::operator bool () const inline
Definition at line 148 of file intrusive_ptr.h.
References libcopp::util::intrusive_ptr< T >::px.
operator!()
template<typename T > bool libcopp::util::intrusive_ptr< T >::operator! () const inline
Definition at line 150 of file intrusive_ptr.h.
References libcopp::util::intrusive_ptr< T >::px.
operator*()
template<typename T > element_type& libcopp::util::intrusive_ptr< T >::operator* () const inline
Definition at line 137 of file intrusive_ptr.h.
References libcopp::util::intrusive_ptr< T >::px.
operator->()
template<typename T > element_type* libcopp::util::intrusive_ptr< T >::operator-> () const inline
Definition at line 142 of file intrusive_ptr.h.
References libcopp::util::intrusive_ptr< T >::px.
operator=() [1/2]
template<typename T > template<typename U > intrusive_ptr& libcopp::util::intrusive_ptr< T >::operator= (intrusive_ptr< U > const & rhs) inline
Definition at line 88 of file intrusive_ptr.h.
operator=() [2/2]
template<typename T > self_type& libcopp::util::intrusive_ptr< T >::operator= (self_type const & rhs) inline
Definition at line 118 of file intrusive_ptr.h.
reset() [1/3]
template<typename T > void libcopp::util::intrusive_ptr< T >::reset () inline
Definition at line 123 of file intrusive_ptr.h.
Referenced by copp::coroutine_context_container< TALLOC >::create().
reset() [2/3]
template<typename T > void libcopp::util::intrusive_ptr< T >::reset (element_type * rhs) inline
Definition at line 125 of file intrusive_ptr.h.
reset() [3/3]
template<typename T > void libcopp::util::intrusive_ptr< T >::reset (element_type * rhs, bool add_ref) inline
Definition at line 127 of file intrusive_ptr.h.
swap()
template<typename T > void libcopp::util::intrusive_ptr< T >::swap (intrusive_ptr< T > & rhs) inline
Definition at line 152 of file intrusive_ptr.h.
References libcopp::util::intrusive_ptr< T >::px.
Referenced by libcopp::util::swap().
Friends And Related Function Documentation
intrusive_ptr
template<typename T > template<typename U > friend class intrusive_ptr friend
Definition at line 85 of file intrusive_ptr.h.
Field Documentation
px
template<typename T > element_type* libcopp::util::intrusive_ptr< T >::px private
Definition at line 159 of file intrusive_ptr.h.
Referenced by libcopp::util::intrusive_ptr< T >::detach(), libcopp::util::intrusive_ptr< T >::get(), libcopp::util::intrusive_ptr< T >::intrusive_ptr(), libcopp::util::intrusive_ptr< T >::operator bool(), libcopp::util::intrusive_ptr< T >::operator!(), libcopp::util::intrusive_ptr< T >::operator*(), libcopp::util::intrusive_ptr< T >::operator->(), libcopp::util::intrusive_ptr< T >::swap(), and libcopp::util::intrusive_ptr< T >::~intrusive_ptr().
The documentation for this class was generated from the following file:
/home/runner/work/libcopp/libcopp/include/libcopp/utils/intrusive_ptr.h