libcopp: util::cli::shell_stream::shell_stream_opr Class Reference
util::cli::shell_stream::shell_stream_opr Class Reference
#include <shell_font.h>
Public Types
typedef shell_stream_opr self_t
Public Member Functions
shell_stream_opr (stream_t *os)
~shell_stream_opr ()
template<typename Ty >
const shell_stream_opr & operator<< (const Ty &v) const
const shell_stream_opr & operator<< (shell_font_style::shell_font_spec style) const
const shell_stream_opr & operator<< (shell_font_style::shell_font_color style) const
const shell_stream_opr & operator<< (shell_font_style::shell_font_background_color style) const
const shell_stream_opr & operator<< (stream_t &(*fn)(stream_t &)) const
const shell_stream_opr & open (int flag) const
void close () const
void reset () const
operator stream_t & () const
operator const stream_t & () const
Private Member Functions
shell_stream_opr (const shell_stream_opr &)
shell_stream_opr & operator= (const shell_stream_opr &)
Private Attributes
stream_t * pOs
int flag
Friends
class shell_stream
Detailed Description
Definition at line 159 of file shell_font.h.
Member Typedef Documentation
self_t
typedef shell_stream_opr util::cli::shell_stream::shell_stream_opr::self_t
Definition at line 161 of file shell_font.h.
Constructor & Destructor Documentation
shell_stream_opr() [1/2]
util::cli::shell_stream::shell_stream_opr::shell_stream_opr (const shell_stream_opr & other) private
Definition at line 240 of file shell_font.cpp.
shell_stream_opr() [2/2]
util::cli::shell_stream::shell_stream_opr::shell_stream_opr (stream_t * os)
Definition at line 220 of file shell_font.cpp.
~shell_stream_opr()
util::cli::shell_stream::shell_stream_opr::~shell_stream_opr ()
Definition at line 232 of file shell_font.cpp.
References pOs, and reset().
Member Function Documentation
close()
void util::cli::shell_stream::shell_stream_opr::close () const
Definition at line 293 of file shell_font.cpp.
References flag, util::cli::shell_font::GetStyleCode(), pOs, and util::cli::shell_font_style::SHELL_FONT_SPEC_NULL.
Referenced by operator<<(), operator=(), and reset().
open()
const shell_stream::shell_stream_opr & util::cli::shell_stream::shell_stream_opr::open (int flag) const
Definition at line 283 of file shell_font.cpp.
References flag, reset(), and util::cli::shell_font_style::SHELL_FONT_SPEC_NULL.
Referenced by operator<<().
operator const stream_t &()
util::cli::shell_stream::shell_stream_opr::operator const stream_t & () const inline
Definition at line 204 of file shell_font.h.
operator stream_t &()
util::cli::shell_stream::shell_stream_opr::operator stream_t & () const inline
Definition at line 202 of file shell_font.h.
operator<<() [1/5]
template<typename Ty > const shell_stream_opr& util::cli::shell_stream::shell_stream_opr::operator<< (const Ty & v) const inline
Definition at line 182 of file shell_font.h.
References libcopp::util::operator<<().
Referenced by operator=().
operator<<() [2/5]
const shell_stream::shell_stream_opr & util::cli::shell_stream::shell_stream_opr::operator<< (shell_font_style::shell_font_spec style) const
Definition at line 261 of file shell_font.cpp.
References open().
operator<<() [3/5]
const shell_stream::shell_stream_opr & util::cli::shell_stream::shell_stream_opr::operator<< (shell_font_style::shell_font_color style) const
Definition at line 266 of file shell_font.cpp.
References open().
operator<<() [4/5]
const shell_stream::shell_stream_opr & util::cli::shell_stream::shell_stream_opr::operator<< (shell_font_style::shell_font_background_color style) const
Definition at line 271 of file shell_font.cpp.
References open().
operator<<() [5/5]
const shell_stream::shell_stream_opr & util::cli::shell_stream::shell_stream_opr::operator<< (stream_t &(*)(stream_t &) fn) const
Definition at line 276 of file shell_font.cpp.
References close().
operator=()
shell_stream::shell_stream_opr & util::cli::shell_stream::shell_stream_opr::operator= (const shell_stream_opr & other) private
Definition at line 242 of file shell_font.cpp.
References close(), flag, operator<<(), pOs, and util::cli::shell_font_style::SHELL_FONT_SPEC_NULL.
reset()
void util::cli::shell_stream::shell_stream_opr::reset () const
Definition at line 328 of file shell_font.cpp.
References close(), util::cli::shell_font::GetStyleCloseCode(), and pOs.
Referenced by open(), and ~shell_stream_opr().
Friends And Related Function Documentation
shell_stream
friend class shell_stream friend
Definition at line 174 of file shell_font.h.
Field Documentation
flag
int util::cli::shell_stream::shell_stream_opr::flag mutable private
Definition at line 168 of file shell_font.h.
Referenced by close(), open(), and operator=().
pOs
stream_t* util::cli::shell_stream::shell_stream_opr::pOs private
Definition at line 164 of file shell_font.h.
Referenced by close(), operator=(), reset(), and ~shell_stream_opr().
The documentation for this class was generated from the following files:
/home/travis/build/owt5008137/libcopp/test/cli/shell_font.h
/home/travis/build/owt5008137/libcopp/test/cli/shell_font.cpp