libcopp: test_case_base Class Reference
test_case_base Class Reference
#include <test_case_base.h>
Public Types
typedef void(* test_func) ()
Public Member Functions
test_case_base (const std::string &test_name, const std::string &case_name, test_func func)
virtual ~test_case_base ()
virtual int run ()
Data Fields
int success_
int failed_
test_func func_
Detailed Description
Definition at line 39 of file test_case_base.h.
Member Typedef Documentation
test_func
typedef void(* test_case_base::test_func) ()
Definition at line 41 of file test_case_base.h.
Constructor & Destructor Documentation
test_case_base()
test_case_base::test_case_base (const std::string & test_name, const std::string & case_name, test_func func)
Definition at line 14 of file test_case_base.cpp.
References test_manager::append_test_case(), failed_, func_, test_manager::me(), and success_.
~test_case_base()
test_case_base::~test_case_base () virtual
Definition at line 23 of file test_case_base.cpp.
Member Function Documentation
run()
int test_case_base::run () virtual
Definition at line 25 of file test_case_base.cpp.
References failed_, func_, test_manager::set_counter_ptr(), and success_.
Field Documentation
failed_
int test_case_base::failed_
Definition at line 50 of file test_case_base.h.
Referenced by run(), and test_case_base().
func_
test_func test_case_base::func_
Definition at line 52 of file test_case_base.h.
Referenced by run(), and test_case_base().
success_
int test_case_base::success_
Definition at line 49 of file test_case_base.h.
Referenced by run(), and test_case_base().
The documentation for this class was generated from the following files:
/home/runner/work/libcopp/libcopp/test/frame/test_case_base.h
/home/runner/work/libcopp/libcopp/test/frame/test_case_base.cpp