libcopp: copp::future::poll_t< T, TPTR > Class Template Reference
copp::future::poll_t< T, TPTR > Class Template Reference
#include <poll.h>
Public Types
typedef poll_t< T, TPTR > self_type
typedef poll_storage_base_t< T, TPTR > poll_storage_t
typedef poll_storage_t::storage_type storage_type
typedef poll_storage_t::ptr_type ptr_type
typedef poll_storage_t::value_type value_type
Public Member Functions
poll_t () LIBCOPP_MACRO_NOEXCEPT
template<class U >
poll_t (U &&in) LIBCOPP_MACRO_NOEXCEPT
poll_t (self_type &&other) LIBCOPP_MACRO_NOEXCEPT
poll_t & operator= (self_type &&other) LIBCOPP_MACRO_NOEXCEPT
UTIL_FORCEINLINE bool is_ready () const LIBCOPP_MACRO_NOEXCEPT
UTIL_FORCEINLINE bool is_pending () const LIBCOPP_MACRO_NOEXCEPT
UTIL_FORCEINLINE const value_type * data () const LIBCOPP_MACRO_NOEXCEPT
UTIL_FORCEINLINE value_type * data () LIBCOPP_MACRO_NOEXCEPT
UTIL_FORCEINLINE const ptr_type & raw_ptr () const LIBCOPP_MACRO_NOEXCEPT
UTIL_FORCEINLINE ptr_type & raw_ptr () LIBCOPP_MACRO_NOEXCEPT
UTIL_FORCEINLINE void reset ()
UTIL_FORCEINLINE void swap (self_type &other) LIBCOPP_MACRO_NOEXCEPT
Private Member Functions
template<class U , class UDELETER , typename std::enable_if< std::is_base_of< T, typename std::decay< U >::type >::value, bool >::type = false>
void setup_from (std::unique_ptr< U, UDELETER > &&in)
template<class TARGS >
void setup_from (TARGS &&args)
void setup_from (self_type &&other)
Private Attributes
storage_type storage_data_
Friends
UTIL_FORCEINLINE void swap (self_type &l, self_type &r) LIBCOPP_MACRO_NOEXCEPT
Detailed Description
template<class T, class TPTR = typename poll_storage_select_ptr_t<T>::type>
class copp::future::poll_t< T, TPTR >
Definition at line 11 of file poll.h.
Member Typedef Documentation
poll_storage_t
template<class T, class TPTR = typename poll_storage_select_ptr_t<T>::type> typedef poll_storage_base_t<T, TPTR> copp::future::poll_t< T, TPTR >::poll_storage_t
Definition at line 15 of file poll.h.
ptr_type
template<class T, class TPTR = typename poll_storage_select_ptr_t<T>::type> typedef poll_storage_t::ptr_type copp::future::poll_t< T, TPTR >::ptr_type
Definition at line 17 of file poll.h.
self_type
template<class T, class TPTR = typename poll_storage_select_ptr_t<T>::type> typedef poll_t<T, TPTR> copp::future::poll_t< T, TPTR >::self_type
Definition at line 13 of file poll.h.
storage_type
template<class T, class TPTR = typename poll_storage_select_ptr_t<T>::type> typedef poll_storage_t::storage_type copp::future::poll_t< T, TPTR >::storage_type
Definition at line 16 of file poll.h.
value_type
template<class T, class TPTR = typename poll_storage_select_ptr_t<T>::type> typedef poll_storage_t::value_type copp::future::poll_t< T, TPTR >::value_type
Definition at line 18 of file poll.h.
Constructor & Destructor Documentation
poll_t() [1/3]
template<class T, class TPTR = typename poll_storage_select_ptr_t<T>::type> copp::future::poll_t< T, TPTR >::poll_t () inline
Definition at line 21 of file poll.h.
poll_t() [2/3]
template<class T, class TPTR = typename poll_storage_select_ptr_t<T>::type> template<class U > copp::future::poll_t< T, TPTR >::poll_t (U && in) inline
Definition at line 24 of file poll.h.
poll_t() [3/3]
template<class T, class TPTR = typename poll_storage_select_ptr_t<T>::type> copp::future::poll_t< T, TPTR >::poll_t (self_type && other) inline
Definition at line 28 of file poll.h.
Member Function Documentation
data() [1/2]
template<class T, class TPTR = typename poll_storage_select_ptr_t<T>::type> UTIL_FORCEINLINE const value_type* copp::future::poll_t< T, TPTR >::data () const inline
Definition at line 39 of file poll.h.
Referenced by CASE_TEST().
data() [2/2]
template<class T, class TPTR = typename poll_storage_select_ptr_t<T>::type> UTIL_FORCEINLINE value_type* copp::future::poll_t< T, TPTR >::data () inline
Definition at line 40 of file poll.h.
is_pending()
template<class T, class TPTR = typename poll_storage_select_ptr_t<T>::type> UTIL_FORCEINLINE bool copp::future::poll_t< T, TPTR >::is_pending () const inline
Definition at line 37 of file poll.h.
Referenced by CASE_TEST().
is_ready()
template<class T, class TPTR = typename poll_storage_select_ptr_t<T>::type> UTIL_FORCEINLINE bool copp::future::poll_t< T, TPTR >::is_ready () const inline
Definition at line 35 of file poll.h.
Referenced by CASE_TEST().
operator=()
template<class T, class TPTR = typename poll_storage_select_ptr_t<T>::type> poll_t& copp::future::poll_t< T, TPTR >::operator= (self_type && other) inline
Definition at line 30 of file poll.h.
raw_ptr() [1/2]
template<class T, class TPTR = typename poll_storage_select_ptr_t<T>::type> UTIL_FORCEINLINE const ptr_type& copp::future::poll_t< T, TPTR >::raw_ptr () const inline
Definition at line 42 of file poll.h.
raw_ptr() [2/2]
template<class T, class TPTR = typename poll_storage_select_ptr_t<T>::type> UTIL_FORCEINLINE ptr_type& copp::future::poll_t< T, TPTR >::raw_ptr () inline
Definition at line 43 of file poll.h.
reset()
template<class T, class TPTR = typename poll_storage_select_ptr_t<T>::type> UTIL_FORCEINLINE void copp::future::poll_t< T, TPTR >::reset () inline
Definition at line 45 of file poll.h.
Referenced by CASE_TEST().
setup_from() [1/3]
template<class T, class TPTR = typename poll_storage_select_ptr_t<T>::type> template<class U , class UDELETER , typename std::enable_if< std::is_base_of< T, typename std::decay< U >::type >::value, bool >::type = false> void copp::future::poll_t< T, TPTR >::setup_from (std::unique_ptr< U, UDELETER > && in) inline private
Definition at line 53 of file poll.h.
setup_from() [2/3]
template<class T, class TPTR = typename poll_storage_select_ptr_t<T>::type> template<class TARGS > void copp::future::poll_t< T, TPTR >::setup_from (TARGS && args) inline private
Definition at line 58 of file poll.h.
setup_from() [3/3]
template<class T, class TPTR = typename poll_storage_select_ptr_t<T>::type> void copp::future::poll_t< T, TPTR >::setup_from (self_type && other) inline private
Definition at line 62 of file poll.h.
swap()
template<class T, class TPTR = typename poll_storage_select_ptr_t<T>::type> UTIL_FORCEINLINE void copp::future::poll_t< T, TPTR >::swap (self_type & other) inline
Definition at line 46 of file poll.h.
References libcopp::util::swap().
Friends And Related Function Documentation
swap
template<class T, class TPTR = typename poll_storage_select_ptr_t<T>::type> UTIL_FORCEINLINE void swap (self_type & l, self_type & r) friend
Definition at line 49 of file poll.h.
Field Documentation
storage_data_
template<class T, class TPTR = typename poll_storage_select_ptr_t<T>::type> storage_type copp::future::poll_t< T, TPTR >::storage_data_ private
Definition at line 65 of file poll.h.
The documentation for this class was generated from the following file:
/home/travis/build/owt5008137/libcopp/include/libcopp/future/poll.h