libcopp: copp::stack_traits Struct Reference
copp::stack_traits Struct Reference
#include <stack_traits.h>
Static Public Member Functions
static LIBCOPP_COPP_API bool is_unbounded () LIBCOPP_MACRO_NOEXCEPT
static LIBCOPP_COPP_API std::size_t page_size () LIBCOPP_MACRO_NOEXCEPT
static LIBCOPP_COPP_API std::size_t default_size () LIBCOPP_MACRO_NOEXCEPT
static LIBCOPP_COPP_API std::size_t minimum_size () LIBCOPP_MACRO_NOEXCEPT
static LIBCOPP_COPP_API std::size_t maximum_size () LIBCOPP_MACRO_NOEXCEPT
static LIBCOPP_COPP_API std::size_t round_to_page_size (std::size_t stacksize) LIBCOPP_MACRO_NOEXCEPT
Detailed Description
Definition at line 15 of file stack_traits.h.
Member Function Documentation
default_size()
LIBCOPP_COPP_API std::size_t copp::stack_traits::default_size () static
Definition at line 55 of file stack_traits_posix.cpp.
References is_unbounded(), maximum_size(), and minimum_size().
Referenced by copp::coroutine_context_container< TALLOC >::create(), cotask::task< TCO_MACRO >::create_with_delegate(), and copp::stack_pool< TAlloc >::stack_pool().
is_unbounded()
LIBCOPP_COPP_API bool copp::stack_traits::is_unbounded () static
Definition at line 49 of file stack_traits_posix.cpp.
References copp::detail::stacksize_limit().
Referenced by copp::allocator::stack_allocator_windows::allocate(), copp::allocator::stack_allocator_windows::deallocate(), copp::allocator::stack_allocator_posix::deallocate(), copp::allocator::stack_allocator_malloc::deallocate(), copp::allocator::stack_allocator_memory::deallocate(), default_size(), and maximum_size().
maximum_size()
LIBCOPP_COPP_API std::size_t copp::stack_traits::maximum_size () static
Definition at line 65 of file stack_traits_posix.cpp.
References is_unbounded(), and copp::detail::stacksize_limit().
Referenced by copp::allocator::stack_allocator_windows::allocate(), copp::allocator::stack_allocator_posix::allocate(), copp::allocator::stack_allocator_malloc::allocate(), copp::allocator::stack_allocator_memory::allocate(), copp::allocator::stack_allocator_windows::deallocate(), copp::allocator::stack_allocator_posix::deallocate(), copp::allocator::stack_allocator_malloc::deallocate(), copp::allocator::stack_allocator_memory::deallocate(), and default_size().
minimum_size()
LIBCOPP_COPP_API std::size_t copp::stack_traits::minimum_size () static
Definition at line 63 of file stack_traits_posix.cpp.
References MINSIGSTKSZ.
Referenced by copp::allocator::stack_allocator_windows::allocate(), copp::allocator::stack_allocator_posix::allocate(), copp::allocator::stack_allocator_malloc::allocate(), copp::allocator::stack_allocator_memory::allocate(), copp::allocator::stack_allocator_windows::deallocate(), copp::allocator::stack_allocator_posix::deallocate(), copp::allocator::stack_allocator_malloc::deallocate(), copp::allocator::stack_allocator_memory::deallocate(), default_size(), main(), and copp::stack_pool< TAlloc >::set_stack_size().
page_size()
LIBCOPP_COPP_API std::size_t copp::stack_traits::page_size () static
Definition at line 53 of file stack_traits_posix.cpp.
References copp::detail::pagesize().
Referenced by copp::allocator::stack_allocator_windows::allocate(), and copp::allocator::stack_allocator_posix::allocate().
round_to_page_size()
LIBCOPP_COPP_API std::size_t copp::stack_traits::round_to_page_size (std::size_t stacksize) static
Definition at line 70 of file stack_traits_posix.cpp.
References copp::detail::pagesize().
Referenced by copp::allocator::stack_allocator_windows::allocate(), copp::allocator::stack_allocator_posix::allocate(), copp::allocator::stack_allocator_malloc::allocate(), copp::allocator::stack_allocator_memory::allocate(), and copp::stack_pool< TAlloc >::set_stack_size().
The documentation for this struct was generated from the following files:
/home/runner/work/libcopp/libcopp/include/libcopp/stack/stack_traits.h
/home/runner/work/libcopp/libcopp/src/libcopp/stack/stack_traits/stack_traits_posix.cpp
/home/runner/work/libcopp/libcopp/src/libcopp/stack/stack_traits/stack_traits_windows.cpp