libcopp: test_on_exit_base Class Reference
test_on_exit_base Class Reference
#include <test_case_base.h>
Public Types
typedef void(* on_exit_func) ()
Public Member Functions
typedef UTIL_UNIT_TEST_MACRO_AUTO_SET (std::string) before_set_t
test_on_exit_base (const std::string &n, on_exit_func func)
test_on_exit_base (const std::string &n, on_exit_func func, const std::string &dep1)
test_on_exit_base (const std::string &n, on_exit_func func, const std::string &dep1, const std::string &dep2)
test_on_exit_base (const std::string &n, on_exit_func func, const std::string &dep1, const std::string &dep2, const std::string &dep3)
test_on_exit_base (const std::string &n, on_exit_func func, const std::string &dep1, const std::string &dep2, const std::string &dep3, const std::string &dep4)
test_on_exit_base (const std::string &n, on_exit_func func, const std::string &dep1, const std::string &dep2, const std::string &dep3, const std::string &dep4, const std::string &dep5)
virtual ~test_on_exit_base ()
virtual int run ()
Data Fields
std::string name
on_exit_func func_
before_set_t before
Private Member Functions
void register_self ()
Detailed Description
Definition at line 128 of file test_case_base.h.
Member Typedef Documentation
on_exit_func
typedef void(* test_on_exit_base::on_exit_func) ()
Definition at line 131 of file test_case_base.h.
Constructor & Destructor Documentation
test_on_exit_base() [1/6]
test_on_exit_base::test_on_exit_base (const std::string & n, on_exit_func func) inline
Definition at line 145 of file test_case_base.h.
References register_self().
test_on_exit_base() [2/6]
test_on_exit_base::test_on_exit_base (const std::string & n, on_exit_func func, const std::string & dep1) inline
Definition at line 146 of file test_case_base.h.
References before, and register_self().
test_on_exit_base() [3/6]
test_on_exit_base::test_on_exit_base (const std::string & n, on_exit_func func, const std::string & dep1, const std::string & dep2) inline
Definition at line 151 of file test_case_base.h.
References before, and register_self().
test_on_exit_base() [4/6]
test_on_exit_base::test_on_exit_base (const std::string & n, on_exit_func func, const std::string & dep1, const std::string & dep2, const std::string & dep3) inline
Definition at line 158 of file test_case_base.h.
References before, and register_self().
test_on_exit_base() [5/6]
test_on_exit_base::test_on_exit_base (const std::string & n, on_exit_func func, const std::string & dep1, const std::string & dep2, const std::string & dep3, const std::string & dep4) inline
Definition at line 167 of file test_case_base.h.
References before, and register_self().
test_on_exit_base() [6/6]
test_on_exit_base::test_on_exit_base (const std::string & n, on_exit_func func, const std::string & dep1, const std::string & dep2, const std::string & dep3, const std::string & dep4, const std::string & dep5) inline
Definition at line 176 of file test_case_base.h.
References before, and register_self().
~test_on_exit_base()
test_on_exit_base::~test_on_exit_base () virtual
Definition at line 55 of file test_case_base.cpp.
Member Function Documentation
register_self()
void test_on_exit_base::register_self () private
Definition at line 53 of file test_case_base.cpp.
References test_manager::append_event_on_exit(), test_manager::me(), and name.
Referenced by test_on_exit_base().
run()
int test_on_exit_base::run () virtual
Definition at line 57 of file test_case_base.cpp.
References func_.
UTIL_UNIT_TEST_MACRO_AUTO_SET()
typedef test_on_exit_base::UTIL_UNIT_TEST_MACRO_AUTO_SET (std::string)
Field Documentation
before
before_set_t test_on_exit_base::before
Definition at line 194 of file test_case_base.h.
Referenced by test_on_exit_base().
func_
on_exit_func test_on_exit_base::func_
Definition at line 193 of file test_case_base.h.
Referenced by run().
name
std::string test_on_exit_base::name
Definition at line 192 of file test_case_base.h.
Referenced by register_self().
The documentation for this class was generated from the following files:
/home/runner/work/libcopp/libcopp/test/frame/test_case_base.h
/home/runner/work/libcopp/libcopp/test/frame/test_case_base.cpp