libcopp: util::cli::phoenix Namespace Reference
util::cli::phoenix Namespace Reference
Data Structures
struct assign_logic_bool_t
通用赋值动作 - 设置一个变量为bool值并检查语义
struct assign_t
通用赋值动作 - 设置一个变量值
struct insert_t
通用赋值动作 - 容器insert操作
struct push_back_t
通用赋值动作 - 容器push_back操作
struct push_front_t
通用赋值动作 - 容器push_front操作
struct set_const_t
通用赋值动作 - 设置变量值为某个固定值
Functions
template<typename T >
assign_t< T > assign (T &t)
template<typename T >
push_back_t< T > push_back (T &t)
template<typename T >
push_front_t< T > push_front (T &t)
template<typename T >
insert_t< T > insert (T &t)
template<typename T >
set_const_t< T > set_const (T &t, const T &v)
template<typename T >
assign_logic_bool_t< T > assign_logic_bool (T &t)
Function Documentation
assign()
template<typename T > assign_t<T> util::cli::phoenix::assign (T & t)
Definition at line 40 of file cmd_option_phoenix.h.
Referenced by copp::future::context_t< void >::context_t().
assign_logic_bool()
template<typename T > assign_logic_bool_t<T> util::cli::phoenix::assign_logic_bool (T & t)
Definition at line 140 of file cmd_option_phoenix.h.
insert()
template<typename T > insert_t<T> util::cli::phoenix::insert (T & t)
Definition at line 100 of file cmd_option_phoenix.h.
push_back()
template<typename T > push_back_t<T> util::cli::phoenix::push_back (T & t)
Definition at line 60 of file cmd_option_phoenix.h.
Referenced by run_tests().
push_front()
template<typename T > push_front_t<T> util::cli::phoenix::push_front (T & t)
Definition at line 80 of file cmd_option_phoenix.h.
set_const()
template<typename T > set_const_t<T> util::cli::phoenix::set_const (T & t, const T & v)
Definition at line 117 of file cmd_option_phoenix.h.
Referenced by run_tests().