libcopp: util::string Namespace Reference
util::string Namespace Reference
Functions
template<typename TCH = char>
static TCH tolower (TCH c)
字符转小写
template<typename TCH = char>
static TCH toupper (TCH c)
字符转大写
template<typename T >
void str2int (T &out, const char *str)
字符串转整数
template<typename T >
T to_int (const char *str)
字符串转整数
template<typename TStr , typename TCh >
void hex (TStr *out, TCh c, bool upper_case=false)
字符转十六进制表示
template<typename TStr , typename TCh >
void oct (TStr *out, TCh c)
字符转8进制表示
template<typename TCh >
void serialization (const void *src, size_t ss, TCh *out, size_t &os)
字符转8进制表示
template<typename Elem , typename Traits >
void serialization (const void *src, size_t ss, std::basic_ostream< Elem, Traits > &out)
字符转8进制表示
template<typename TCh >
void dumphex (const void *src, size_t ss, TCh *out, bool upper_case=false)
字符转16进制表示
template<typename Elem , typename Traits >
void dumphex (const void *src, size_t ss, std::basic_ostream< Elem, Traits > &out, bool upper_case=false)
字符转16进制表示
Function Documentation
dumphex() [1/2]
template<typename Elem , typename Traits > void util::string::dumphex (const void * src, size_t ss, std::basic_ostream< Elem, Traits > & out, bool upper_case = false)
字符转16进制表示
Parameters
src 输入的buffer
ss 输入的buffer长度
out 输出缓冲区
upper_case 是否大写
Definition at line 264 of file string_oprs.h.
dumphex() [2/2]
template<typename TCh > void util::string::dumphex (const void * src, size_t ss, TCh * out, bool upper_case = false)
字符转16进制表示
Parameters
src 输入的buffer
ss 输入的buffer长度
out 输出buffer
upper_case 是否大写
Definition at line 248 of file string_oprs.h.
hex()
template<typename TStr , typename TCh > void util::string::hex (TStr * out, TCh c, bool upper_case = false)
字符转十六进制表示
Parameters
out 输出的字符串(缓冲区长度至少为2)
c 被转换的字符
upper_case 输出大写字符？
Definition at line 166 of file string_oprs.h.
oct()
template<typename TStr , typename TCh > void util::string::oct (TStr * out, TCh c)
字符转8进制表示
Parameters
out 输出的字符串(缓冲区长度至少为3)
c 被转换的字符
upper_case 输出大写字符？
Definition at line 186 of file string_oprs.h.
Referenced by serialization().
serialization() [1/2]
template<typename Elem , typename Traits > void util::string::serialization (const void * src, size_t ss, std::basic_ostream< Elem, Traits > & out)
字符转8进制表示
Parameters
src 输入的buffer
ss 输入的buffer长度
out 输出缓冲区
Definition at line 226 of file string_oprs.h.
References oct().
serialization() [2/2]
template<typename TCh > void util::string::serialization (const void * src, size_t ss, TCh * out, size_t & os)
字符转8进制表示
Parameters
src 输入的buffer
ss 输入的buffer长度
out 输出buffer
os 输出buffer长度，回传输出缓冲区使用的长度
Definition at line 200 of file string_oprs.h.
References oct().
str2int()
template<typename T > void util::string::str2int (T & out, const char * str)
字符串转整数
Parameters
out 输出的整数
str 被转换的字符串
Note
性能肯定比sscanf系，和iostream系高。strtol系就不知道了
Definition at line 100 of file string_oprs.h.
References tolower().
Referenced by to_int().
to_int()
template<typename T > T util::string::to_int (const char * str) inline
字符串转整数
Parameters
str 被转换的字符串
Returns
输出的整数
Definition at line 153 of file string_oprs.h.
References str2int().
tolower()
template<typename TCH = char> static TCH util::string::tolower (TCH c) static
字符转小写
Parameters
c 字符
Returns
str 如果是大写字符输出响应的小写字符，否则原样返回
Note
用于替换标准函数里参数是int类型导致的某些编译器warning问题
Definition at line 70 of file string_oprs.h.
Referenced by str2int().
toupper()
template<typename TCH = char> static TCH util::string::toupper (TCH c) static
字符转大写
Parameters
c 字符
Returns
str 如果是小写字符输出响应的大写字符，否则原样返回
Note
用于替换标准函数里参数是int类型导致的某些编译器warning问题
Definition at line 85 of file string_oprs.h.
Referenced by util::cli::ci_char_traits< Tc >::compare(), util::cli::ci_char_traits< Tc >::eq(), util::cli::ci_char_traits< Tc >::find(), and util::cli::ci_char_traits< Tc >::lt().