libcopp: copp::future::future_t< T, TPTR > Class Template Reference
copp::future::future_t< T, TPTR > Class Template Reference
#include <future.h>
Data Structures
struct clear_context_waker_t
struct future_waker_t
struct future_waker_t< TSELF, context_t< TPD > >
struct waker_t
Public Types
typedef future_t< T, TPTR > self_type
typedef poll_t< T, TPTR > poll_type
typedef poll_type::storage_type storage_type
typedef poll_type::value_type value_type
typedef poll_type::ptr_type ptr_type
Public Member Functions
future_t ()
~future_t ()
UTIL_FORCEINLINE bool is_ready () const LIBCOPP_MACRO_NOEXCEPT
UTIL_FORCEINLINE bool is_pending () const LIBCOPP_MACRO_NOEXCEPT
template<class TCONTEXT >
UTIL_FORCEINLINE void poll (TCONTEXT &&ctx)
template<class TSELF , class TCONTEXT >
UTIL_FORCEINLINE void poll_as (TCONTEXT &&ctx)
UTIL_FORCEINLINE const value_type * data () const LIBCOPP_MACRO_NOEXCEPT
UTIL_FORCEINLINE value_type * data () LIBCOPP_MACRO_NOEXCEPT
UTIL_FORCEINLINE const ptr_type & raw_ptr () const LIBCOPP_MACRO_NOEXCEPT
UTIL_FORCEINLINE ptr_type & raw_ptr () LIBCOPP_MACRO_NOEXCEPT
UTIL_FORCEINLINE const poll_type & poll_data () const LIBCOPP_MACRO_NOEXCEPT
UTIL_FORCEINLINE poll_type & poll_data () LIBCOPP_MACRO_NOEXCEPT
UTIL_FORCEINLINE void reset_data ()
void clear_ctx_waker () LIBCOPP_MACRO_NOEXCEPT
template<class TCONTEXT >
void set_ctx_waker (TCONTEXT &&ctx)
Static Protected Member Functions
template<class TSELF , class TCONTEXT >
static void poll_as (TSELF &self, TCONTEXT &&ctx)
Private Member Functions
future_t (const future_t &) UTIL_CONFIG_DELETED_FUNCTION
future_t & operator= (const future_t &) UTIL_CONFIG_DELETED_FUNCTION
future_t (future_t &&) UTIL_CONFIG_DELETED_FUNCTION
future_t & operator= (future_t &&) UTIL_CONFIG_DELETED_FUNCTION
Private Attributes
std::function< void()> clear_ctx_waker_
poll_type poll_data_
Detailed Description
template<class T, class TPTR = typename poll_storage_select_ptr_t<T>::type>
class copp::future::future_t< T, TPTR >
Definition at line 14 of file future.h.
Member Typedef Documentation
poll_type
template<class T, class TPTR = typename poll_storage_select_ptr_t<T>::type> typedef poll_t<T, TPTR> copp::future::future_t< T, TPTR >::poll_type
Definition at line 24 of file future.h.
ptr_type
template<class T, class TPTR = typename poll_storage_select_ptr_t<T>::type> typedef poll_type::ptr_type copp::future::future_t< T, TPTR >::ptr_type
Definition at line 27 of file future.h.
self_type
template<class T, class TPTR = typename poll_storage_select_ptr_t<T>::type> typedef future_t<T, TPTR> copp::future::future_t< T, TPTR >::self_type
Definition at line 23 of file future.h.
storage_type
template<class T, class TPTR = typename poll_storage_select_ptr_t<T>::type> typedef poll_type::storage_type copp::future::future_t< T, TPTR >::storage_type
Definition at line 25 of file future.h.
value_type
template<class T, class TPTR = typename poll_storage_select_ptr_t<T>::type> typedef poll_type::value_type copp::future::future_t< T, TPTR >::value_type
Definition at line 26 of file future.h.
Constructor & Destructor Documentation
future_t() [1/3]
template<class T, class TPTR = typename poll_storage_select_ptr_t<T>::type> copp::future::future_t< T, TPTR >::future_t (const future_t< T, TPTR > &) private
future_t() [2/3]
template<class T, class TPTR = typename poll_storage_select_ptr_t<T>::type> copp::future::future_t< T, TPTR >::future_t (future_t< T, TPTR > &&) private
future_t() [3/3]
template<class T, class TPTR = typename poll_storage_select_ptr_t<T>::type> copp::future::future_t< T, TPTR >::future_t () inline
Definition at line 81 of file future.h.
~future_t()
template<class T, class TPTR = typename poll_storage_select_ptr_t<T>::type> copp::future::future_t< T, TPTR >::~future_t () inline
Definition at line 82 of file future.h.
Member Function Documentation
clear_ctx_waker()
template<class T, class TPTR = typename poll_storage_select_ptr_t<T>::type> void copp::future::future_t< T, TPTR >::clear_ctx_waker () inline
Definition at line 121 of file future.h.
data() [1/2]
template<class T, class TPTR = typename poll_storage_select_ptr_t<T>::type> UTIL_FORCEINLINE const value_type* copp::future::future_t< T, TPTR >::data () const inline
Definition at line 98 of file future.h.
Referenced by CASE_TEST(), run_with_custom_context(), and run_with_void_context().
data() [2/2]
template<class T, class TPTR = typename poll_storage_select_ptr_t<T>::type> UTIL_FORCEINLINE value_type* copp::future::future_t< T, TPTR >::data () inline
Definition at line 106 of file future.h.
is_pending()
template<class T, class TPTR = typename poll_storage_select_ptr_t<T>::type> UTIL_FORCEINLINE bool copp::future::future_t< T, TPTR >::is_pending () const inline
Definition at line 86 of file future.h.
Referenced by CASE_TEST().
is_ready()
template<class T, class TPTR = typename poll_storage_select_ptr_t<T>::type> UTIL_FORCEINLINE bool copp::future::future_t< T, TPTR >::is_ready () const inline
Definition at line 84 of file future.h.
Referenced by CASE_TEST(), run_with_custom_context(), and run_with_void_context().
operator=() [1/2]
template<class T, class TPTR = typename poll_storage_select_ptr_t<T>::type> future_t& copp::future::future_t< T, TPTR >::operator= (const future_t< T, TPTR > &) private
operator=() [2/2]
template<class T, class TPTR = typename poll_storage_select_ptr_t<T>::type> future_t& copp::future::future_t< T, TPTR >::operator= (future_t< T, TPTR > &&) private
poll()
template<class T, class TPTR = typename poll_storage_select_ptr_t<T>::type> template<class TCONTEXT > UTIL_FORCEINLINE void copp::future::future_t< T, TPTR >::poll (TCONTEXT && ctx) inline
Definition at line 89 of file future.h.
Referenced by CASE_TEST(), run_with_custom_context(), and run_with_void_context().
poll_as() [1/2]
template<class T, class TPTR = typename poll_storage_select_ptr_t<T>::type> template<class TSELF , class TCONTEXT > static void copp::future::future_t< T, TPTR >::poll_as (TSELF & self, TCONTEXT && ctx) inline static protected
Definition at line 54 of file future.h.
poll_as() [2/2]
template<class T, class TPTR = typename poll_storage_select_ptr_t<T>::type> template<class TSELF , class TCONTEXT > UTIL_FORCEINLINE void copp::future::future_t< T, TPTR >::poll_as (TCONTEXT && ctx) inline
Definition at line 94 of file future.h.
poll_data() [1/2]
template<class T, class TPTR = typename poll_storage_select_ptr_t<T>::type> UTIL_FORCEINLINE const poll_type& copp::future::future_t< T, TPTR >::poll_data () const inline
Definition at line 116 of file future.h.
Referenced by custom_poller_function(), custom_waker_t::operator()(), example_poller::operator()(), test_future_void_context_poll_functor< void >::operator()(), test_future_void_context_poll_functor< T >::operator()(), and test_future_custom_poller_for_context< T >::operator()().
poll_data() [2/2]
template<class T, class TPTR = typename poll_storage_select_ptr_t<T>::type> UTIL_FORCEINLINE poll_type& copp::future::future_t< T, TPTR >::poll_data () inline
Definition at line 117 of file future.h.
raw_ptr() [1/2]
template<class T, class TPTR = typename poll_storage_select_ptr_t<T>::type> UTIL_FORCEINLINE const ptr_type& copp::future::future_t< T, TPTR >::raw_ptr () const inline
Definition at line 114 of file future.h.
Referenced by CASE_TEST().
raw_ptr() [2/2]
template<class T, class TPTR = typename poll_storage_select_ptr_t<T>::type> UTIL_FORCEINLINE ptr_type& copp::future::future_t< T, TPTR >::raw_ptr () inline
Definition at line 115 of file future.h.
reset_data()
template<class T, class TPTR = typename poll_storage_select_ptr_t<T>::type> UTIL_FORCEINLINE void copp::future::future_t< T, TPTR >::reset_data () inline
Definition at line 118 of file future.h.
set_ctx_waker()
template<class T, class TPTR = typename poll_storage_select_ptr_t<T>::type> template<class TCONTEXT > void copp::future::future_t< T, TPTR >::set_ctx_waker (TCONTEXT && ctx) inline
Definition at line 129 of file future.h.
Field Documentation
clear_ctx_waker_
template<class T, class TPTR = typename poll_storage_select_ptr_t<T>::type> std::function<void ()> copp::future::future_t< T, TPTR >::clear_ctx_waker_ private
Definition at line 184 of file future.h.
poll_data_
template<class T, class TPTR = typename poll_storage_select_ptr_t<T>::type> poll_type copp::future::future_t< T, TPTR >::poll_data_ private
Definition at line 185 of file future.h.
The documentation for this class was generated from the following file:
/home/travis/build/owt5008137/libcopp/include/libcopp/future/future.h