libcopp: copp::allocator::stack_allocator_posix Class Reference
copp::allocator::stack_allocator_posix Class Reference
memory allocator this allocator will create buffer using posix api and protect it
#include <stack_allocator_posix.h>
Public Member Functions
stack_allocator_posix () LIBCOPP_MACRO_NOEXCEPT
~stack_allocator_posix ()
stack_allocator_posix (const stack_allocator_posix &other) LIBCOPP_MACRO_NOEXCEPT
stack_allocator_posix & operator= (const stack_allocator_posix &other) LIBCOPP_MACRO_NOEXCEPT
void allocate (stack_context &, std::size_t) LIBCOPP_MACRO_NOEXCEPT
void deallocate (stack_context &) LIBCOPP_MACRO_NOEXCEPT
Detailed Description
memory allocator this allocator will create buffer using posix api and protect it
Definition at line 25 of file stack_allocator_posix.h.
Constructor & Destructor Documentation
stack_allocator_posix() [1/2]
LIBCOPP_COPP_API copp::allocator::stack_allocator_posix::stack_allocator_posix ()
Definition at line 36 of file stack_allocator_posix.cpp.
~stack_allocator_posix()
LIBCOPP_COPP_API copp::allocator::stack_allocator_posix::~stack_allocator_posix ()
Definition at line 37 of file stack_allocator_posix.cpp.
stack_allocator_posix() [2/2]
LIBCOPP_COPP_API copp::allocator::stack_allocator_posix::stack_allocator_posix (const stack_allocator_posix & other)
Definition at line 38 of file stack_allocator_posix.cpp.
Member Function Documentation
allocate()
LIBCOPP_COPP_API void copp::allocator::stack_allocator_posix::allocate (stack_context & ctx, std::size_t size)
allocate memory and attach to stack context [standard function]
Parameters
ctx stack context
size stack size
Definition at line 51 of file stack_allocator_posix.cpp.
References copp::stack_traits::maximum_size(), copp::stack_traits::minimum_size(), copp::stack_traits::page_size(), and copp::stack_traits::round_to_page_size().
deallocate()
LIBCOPP_COPP_API void copp::allocator::stack_allocator_posix::deallocate (stack_context & ctx)
deallocate memory from stack context [standard function]
Parameters
ctx stack context
Definition at line 82 of file stack_allocator_posix.cpp.
References copp::stack_traits::is_unbounded(), copp::stack_traits::maximum_size(), and copp::stack_traits::minimum_size().
operator=()
LIBCOPP_COPP_API stack_allocator_posix & copp::allocator::stack_allocator_posix::operator= (const stack_allocator_posix & other)
Definition at line 39 of file stack_allocator_posix.cpp.
The documentation for this class was generated from the following files:
/home/runner/work/libcopp/libcopp/include/libcopp/stack/allocator/stack_allocator_posix.h
/home/runner/work/libcopp/libcopp/src/libcopp/stack/allocator/stack_allocator_posix.cpp