libcopp: /home/runner/work/libcopp/libcopp/test/case/fcontext_test.cpp File Reference
fcontext_test.cpp File Reference
#include <cstdio>
#include <cstring>
#include <iostream>
#include "libcopp/utils/config/libcopp_build_features.h"
#include "frame/test_macros.h"
#include "libcopp/fcontext/all.hpp"
Functions
void test_core_fcontext_func_a (::copp::fcontext::transfer_t src)
void test_core_fcontext_func_b (::copp::fcontext::transfer_t src)
CASE_TEST (core, fcontext)
Variables
copp::fcontext::fcontext_t test_core_fcontext_main_func
copp::fcontext::fcontext_t test_core_fcontext_a_func
copp::fcontext::fcontext_t test_core_fcontext_b_func
char test_core_fcontext_stack_a [128 *1024] = {0}
char test_core_fcontext_stack_b [128 *1024] = {0}
int g_test_core_fcontext_status = 0
Function Documentation
CASE_TEST()
CASE_TEST (core , fcontext)
Definition at line 50 of file fcontext_test.cpp.
References CASE_EXPECT_EQ, copp::fcontext::copp_jump_fcontext(), copp::fcontext::copp_make_fcontext(), g_test_core_fcontext_status, test_core_fcontext_a_func, test_core_fcontext_b_func, test_core_fcontext_func_a(), test_core_fcontext_func_b(), test_core_fcontext_stack_a, and test_core_fcontext_stack_b.
test_core_fcontext_func_a()
void test_core_fcontext_func_a (::copp::fcontext::transfer_t src)
Definition at line 19 of file fcontext_test.cpp.
References CASE_EXPECT_EQ, copp::fcontext::copp_jump_fcontext(), copp::fcontext::transfer_t::data, copp::fcontext::transfer_t::fctx, g_test_core_fcontext_status, test_core_fcontext_a_func, test_core_fcontext_b_func, and test_core_fcontext_main_func.
Referenced by CASE_TEST().
test_core_fcontext_func_b()
void test_core_fcontext_func_b (::copp::fcontext::transfer_t src)
Definition at line 39 of file fcontext_test.cpp.
References CASE_EXPECT_EQ, copp::fcontext::copp_jump_fcontext(), copp::fcontext::transfer_t::data, copp::fcontext::transfer_t::fctx, g_test_core_fcontext_status, test_core_fcontext_a_func, and test_core_fcontext_b_func.
Referenced by CASE_TEST().
Variable Documentation
g_test_core_fcontext_status
int g_test_core_fcontext_status = 0
Definition at line 17 of file fcontext_test.cpp.
Referenced by CASE_TEST(), test_core_fcontext_func_a(), and test_core_fcontext_func_b().
test_core_fcontext_a_func
copp::fcontext::fcontext_t test_core_fcontext_a_func
Definition at line 14 of file fcontext_test.cpp.
Referenced by CASE_TEST(), test_core_fcontext_func_a(), and test_core_fcontext_func_b().
test_core_fcontext_b_func
copp::fcontext::fcontext_t test_core_fcontext_b_func
Definition at line 14 of file fcontext_test.cpp.
Referenced by CASE_TEST(), test_core_fcontext_func_a(), and test_core_fcontext_func_b().
test_core_fcontext_main_func
copp::fcontext::fcontext_t test_core_fcontext_main_func
Definition at line 14 of file fcontext_test.cpp.
Referenced by test_core_fcontext_func_a().
test_core_fcontext_stack_a
char test_core_fcontext_stack_a[128 *1024] = {0}
Definition at line 15 of file fcontext_test.cpp.
Referenced by CASE_TEST().
test_core_fcontext_stack_b
char test_core_fcontext_stack_b[128 *1024] = {0}
Definition at line 16 of file fcontext_test.cpp.
Referenced by CASE_TEST().