libcopp: test_future_void_context_poll_functor< void > Struct Reference
test_future_void_context_poll_functor< void > Struct Reference
Public Member Functions
test_future_void_context_poll_functor (int32_t d)
void operator() (copp::future::context_t< void > &ctx, copp::future::context_t< void >::poll_event_data_t evt)
Static Public Member Functions
static void on_destroy (copp::future::context_t< void > &ctx)
Data Fields
int32_t delay
Detailed Description
Definition at line 209 of file future_and_std_coroutine_test.cpp.
Constructor & Destructor Documentation
test_future_void_context_poll_functor()
test_future_void_context_poll_functor< void >::test_future_void_context_poll_functor (int32_t d) inline
Definition at line 212 of file future_and_std_coroutine_test.cpp.
Member Function Documentation
on_destroy()
static void test_future_void_context_poll_functor< void >::on_destroy (copp::future::context_t< void > & ctx) inline static
Definition at line 214 of file future_and_std_coroutine_test.cpp.
References CASE_MSG_INFO.
operator()()
void test_future_void_context_poll_functor< void >::operator() (copp::future::context_t< void > & ctx, copp::future::context_t< void >::poll_event_data_t evt) inline
Definition at line 218 of file future_and_std_coroutine_test.cpp.
References CASE_MSG_INFO, test_future_void_context_poll_functor< T >::delay, test_future_void_context_poll_functor< T >::on_destroy(), copp::future::future_t< T, TPTR >::poll_data(), and copp::future::context_t< void >::set_on_destroy().
Field Documentation
delay
int32_t test_future_void_context_poll_functor< void >::delay
Definition at line 210 of file future_and_std_coroutine_test.cpp.
The documentation for this struct was generated from the following file:
/home/runner/work/libcopp/libcopp/test/case/future_and_std_coroutine_test.cpp