libcopp: /home/travis/build/owt5008137/libcopp/test/frame/test_manager.cpp File Reference
test_manager.cpp File Reference
#include <cstring>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>
#include <list>
#include <libcopp/utils/config/compile_optimize.h>
#include <libcopp/utils/config/compiler_features.h>
#include "cli/cmd_option.h"
#include "cli/cmd_option_phoenix.h"
#include "cli/shell_font.h"
#include "test_manager.h"
Data Structures
struct detail::test_manager_tls_block_t
struct detail::topological_sort_object_t
Namespaces
detail
Functions
test_manager_tls_block_t * detail::get_test_manager_tls_block ()
static void topological_sort (UTIL_UNIT_TEST_MACRO_AUTO_MAP(std::string, detail::topological_sort_object_t) &in, std::vector< detail::topological_sort_object_t *> &out)
int run_event_on_start ()
int run_event_on_exit ()
int run_tests (int argc, char *argv[])
Variables
static test_manager_tls_block_t detail::g_global_counter_cache = {0, 0}
Function Documentation
run_event_on_exit()
int run_event_on_exit ()
Definition at line 459 of file test_manager.cpp.
References test_manager::me(), and test_manager::run_event_on_exit().
Referenced by main().
run_event_on_start()
int run_event_on_start ()
Definition at line 457 of file test_manager.cpp.
References test_manager::me(), and test_manager::run_event_on_start().
Referenced by main().
run_tests()
int run_tests (int argc, char * argv[])
Definition at line 461 of file test_manager.cpp.
References util::cli::cmd_option_bind< TCmdStr >::create(), test_manager::me(), util::cli::phoenix::push_back(), test_manager::run(), test_manager::run_event_on_exit(), test_manager::run_event_on_start(), test_manager::set_cases(), and util::cli::phoenix::set_const().
Referenced by main().
topological_sort()
static void topological_sort (UTIL_UNIT_TEST_MACRO_AUTO_MAP(std::string, detail::topological_sort_object_t) & in, std::vector< detail::topological_sort_object_t *> & out) static
Definition at line 177 of file test_manager.cpp.
References UTIL_UNIT_TEST_MACRO_AUTO_MAP.
Referenced by test_manager::run_event_on_exit(), and test_manager::run_event_on_start().