libcopp: print_color Namespace Reference
print_color Namespace Reference
Data Structures
class HtmlColor
class NoneColor
class print_style
class TermColor
class Win32ConsoleColor
Functions
def cprintf_set_mode (mode_name="auto")
def cprintf_set_theme (theme_name=None)
def cprintf_unpack_text (fmt, text)
def cprintf_stdout (options, fmt, *text)
def cprintf_stderr (options, fmt, *text)
Variables
console_encoding = sys.getfilesystemencoding()
string usage = "usage: %prog [options...] <format message> [format parameters...]"
parser = OptionParser(usage)
action
help
dest
metavar
const
default
options
left_args
string print_stream = "stdout"
list print_options = []
list fc_list = ["FC_" + x.upper() for x in options.color or []]
list bk_list = ["BC_" + y.upper() for y in options.background_color or []]
Function Documentation
cprintf_set_mode()
def print_color.cprintf_set_mode (mode_name = "auto")
Definition at line 233 of file print_color.py.
Referenced by cprintf_stderr().
cprintf_set_theme()
def print_color.cprintf_set_theme (theme_name = None)
Definition at line 285 of file print_color.py.
cprintf_stderr()
def print_color.cprintf_stderr (options, fmt, * text)
Definition at line 314 of file print_color.py.
References cprintf_set_mode(), and cprintf_unpack_text().
cprintf_stdout()
def print_color.cprintf_stdout (options, fmt, * text)
Definition at line 308 of file print_color.py.
References cprintf_unpack_text().
cprintf_unpack_text()
def print_color.cprintf_unpack_text (fmt, text)
Definition at line 293 of file print_color.py.
Referenced by cprintf_stderr(), and cprintf_stdout().
Variable Documentation
action
print_color.action
Definition at line 333 of file print_color.py.
Referenced by cotask::impl::task_impl._set_action(), and cotask::task< TCO_MACRO >.create_with_delegate().
bk_list
list print_color.bk_list = ["BC_" + y.upper() for y in options.background_color or []]
Definition at line 407 of file print_color.py.
console_encoding
print_color.console_encoding = sys.getfilesystemencoding()
Definition at line 10 of file print_color.py.
const
print_color.const
Definition at line 358 of file print_color.py.
default
print_color.default
Definition at line 376 of file print_color.py.
dest
print_color.dest
Definition at line 335 of file print_color.py.
fc_list
list print_color.fc_list = ["FC_" + x.upper() for x in options.color or []]
Definition at line 406 of file print_color.py.
help
print_color.help
Definition at line 334 of file print_color.py.
left_args
print_color.left_args
Definition at line 401 of file print_color.py.
metavar
print_color.metavar
Definition at line 342 of file print_color.py.
options
print_color.options
Definition at line 401 of file print_color.py.
parser
print_color.parser = OptionParser(usage)
Definition at line 327 of file print_color.py.
print_options
list print_color.print_options = []
Definition at line 404 of file print_color.py.
print_stream
string print_color.print_stream = "stdout"
Definition at line 403 of file print_color.py.
usage
string print_color.usage = "usage: %prog [options...] <format message> [format parameters...]"
Definition at line 326 of file print_color.py.