libcopp: copp::coroutine_context_container< TALLOC > Class Template Reference
copp::coroutine_context_container< TALLOC > Class Template Reference
coroutine container contain stack context, stack allocator and runtime fcontext
#include <coroutine_context_container.h>
Public Types
typedef coroutine_context coroutine_context_type
typedef coroutine_context base_type
typedef TALLOC allocator_type
typedef coroutine_context_container< allocator_type > this_type
typedef libcopp::util::intrusive_ptr< this_type > ptr_t
typedef coroutine_context::callback_t callback_t
typedef coroutine_context_base::status_t status_t
typedef coroutine_context_base::flag_t flag_t
Public Member Functions
~coroutine_context_container ()
const allocator_type & get_allocator () const LIBCOPP_MACRO_NOEXCEPT
get stack allocator
allocator_type & get_allocator () LIBCOPP_MACRO_NOEXCEPT
get stack allocator
size_t use_count () const LIBCOPP_MACRO_NOEXCEPT
LIBCOPP_COPP_API int start (void *priv_data=UTIL_CONFIG_NULLPTR)
start coroutine
LIBCOPP_COPP_API int resume (void *priv_data=UTIL_CONFIG_NULLPTR)
resume coroutine
LIBCOPP_COPP_API int yield (void **priv_data=UTIL_CONFIG_NULLPTR) LIBCOPP_MACRO_NOEXCEPT
yield coroutine
LIBCOPP_COPP_API bool set_flags (int flags) LIBCOPP_MACRO_NOEXCEPT
set all flags to true
LIBCOPP_COPP_API bool unset_flags (int flags) LIBCOPP_MACRO_NOEXCEPT
set all flags to false
LIBCOPP_COPP_API bool check_flags (int flags) const LIBCOPP_MACRO_NOEXCEPT
check flags
LIBCOPP_COPP_API int set_runner (const callback_t &runner)
set runner
UTIL_FORCEINLINE const std::function< int(void *)> & get_runner () const LIBCOPP_MACRO_NOEXCEPT
UTIL_FORCEINLINE int get_ret_code () const LIBCOPP_MACRO_NOEXCEPT
get runner return code
LIBCOPP_COPP_API bool is_finished () const LIBCOPP_MACRO_NOEXCEPT
get runner return code
UTIL_FORCEINLINE void * get_private_buffer () const LIBCOPP_MACRO_NOEXCEPT
get private buffer(raw pointer)
UTIL_FORCEINLINE size_t get_private_buffer_size () const LIBCOPP_MACRO_NOEXCEPT
get private buffer size
Static Public Member Functions
static ptr_t create (const callback_t &runner, allocator_type &alloc, size_t stack_sz=0, size_t private_buffer_size=0, size_t coroutine_size=0) LIBCOPP_MACRO_NOEXCEPT
create and init coroutine with specify runner and specify stack size
template<class TRunner >
static ptr_t create (TRunner *runner, allocator_type &alloc, size_t stack_size=0, size_t private_buffer_size=0, size_t coroutine_size=0) LIBCOPP_MACRO_NOEXCEPT
static ptr_t create (int(*fn)(void *), allocator_type &alloc, size_t stack_size=0, size_t private_buffer_size=0, size_t coroutine_size=0) LIBCOPP_MACRO_NOEXCEPT
static ptr_t create (const callback_t &runner, size_t stack_size=0, size_t private_buffer_size=0, size_t coroutine_size=0) LIBCOPP_MACRO_NOEXCEPT
template<class TRunner >
static ptr_t create (TRunner *runner, size_t stack_size=0, size_t private_buffer_size=0, size_t coroutine_size=0) LIBCOPP_MACRO_NOEXCEPT
static ptr_t create (int(*fn)(void *), size_t stack_size=0, size_t private_buffer_size=0, size_t coroutine_size=0) LIBCOPP_MACRO_NOEXCEPT
static LIBCOPP_COPP_API int create (coroutine_context *p, callback_t &runner, const stack_context &callee_stack, size_t coroutine_size, size_t private_buffer_size) LIBCOPP_MACRO_NOEXCEPT
create coroutine context at stack context callee_
template<typename TRunner >
static LIBCOPP_COPP_API_HEAD_ONLY int create (coroutine_context *p, TRunner *runner, const stack_context &callee_stack, size_t coroutine_size, size_t private_buffer_size) LIBCOPP_MACRO_NOEXCEPT
static UTIL_FORCEINLINE size_t align_private_data_size (size_t sz)
static size_t align_address_size (size_t sz)
static size_t align_stack_size (size_t sz)
static LIBCOPP_COPP_API coroutine_context_base * get_this_coroutine_base () LIBCOPP_MACRO_NOEXCEPT
get current coroutine
static LIBCOPP_COPP_API void set_this_coroutine_base (coroutine_context_base *ctx) LIBCOPP_MACRO_NOEXCEPT
set current coroutine
Protected Member Functions
UTIL_FORCEINLINE void run_and_recv_retcode (void *priv_data)
coroutine entrance function
Protected Attributes
fcontext::fcontext_t caller_
fcontext::fcontext_t callee_
stack_context callee_stack_
int runner_ret_code_
int flags_
callback_t runner_
void * priv_data_
size_t private_buffer_size_
libcopp::util::lock::atomic_int_type< int > status_
Private Member Functions
coroutine_context_container (const allocator_type &alloc) LIBCOPP_MACRO_NOEXCEPT
coroutine_context_container (const coroutine_context_container &) UTIL_CONFIG_DELETED_FUNCTION
Private Attributes
allocator_type alloc_
libcopp::util::lock::atomic_int_type< size_t > ref_count_
Friends
void intrusive_ptr_add_ref (this_type *p)
void intrusive_ptr_release (this_type *p)
Detailed Description
template<typename TALLOC>
class copp::coroutine_context_container< TALLOC >
coroutine container contain stack context, stack allocator and runtime fcontext
Definition at line 23 of file coroutine_context_container.h.
Member Typedef Documentation
allocator_type
template<typename TALLOC > typedef TALLOC copp::coroutine_context_container< TALLOC >::allocator_type
Definition at line 35 of file coroutine_context_container.h.
base_type
template<typename TALLOC > typedef coroutine_context copp::coroutine_context_container< TALLOC >::base_type
Definition at line 34 of file coroutine_context_container.h.
callback_t
template<typename TALLOC > typedef coroutine_context::callback_t copp::coroutine_context_container< TALLOC >::callback_t
Definition at line 38 of file coroutine_context_container.h.
coroutine_context_type
template<typename TALLOC > typedef coroutine_context copp::coroutine_context_container< TALLOC >::coroutine_context_type
Definition at line 33 of file coroutine_context_container.h.
flag_t
typedef coroutine_context_base::flag_t copp::coroutine_context::flag_t inherited
Definition at line 36 of file coroutine_context.h.
ptr_t
template<typename TALLOC > typedef libcopp::util::intrusive_ptr<this_type> copp::coroutine_context_container< TALLOC >::ptr_t
Definition at line 37 of file coroutine_context_container.h.
status_t
typedef coroutine_context_base::status_t copp::coroutine_context::status_t inherited
Definition at line 35 of file coroutine_context.h.
this_type
template<typename TALLOC > typedef coroutine_context_container<allocator_type> copp::coroutine_context_container< TALLOC >::this_type
Definition at line 36 of file coroutine_context_container.h.
Constructor & Destructor Documentation
coroutine_context_container() [1/2]
template<typename TALLOC > copp::coroutine_context_container< TALLOC >::coroutine_context_container (const allocator_type & alloc) inline private
Definition at line 43 of file coroutine_context_container.h.
References copp::coroutine_context_container< TALLOC >::alloc_, LIBCOPP_MACRO_NOEXCEPT, and copp::coroutine_context_container< TALLOC >::ref_count_.
Referenced by copp::coroutine_context_container< TALLOC >::use_count().
~coroutine_context_container()
template<typename TALLOC > copp::coroutine_context_container< TALLOC >::~coroutine_context_container () inline
Definition at line 50 of file coroutine_context_container.h.
coroutine_context_container() [2/2]
template<typename TALLOC > copp::coroutine_context_container< TALLOC >::coroutine_context_container (const coroutine_context_container< TALLOC > &) private
Member Function Documentation
align_address_size()
static size_t copp::coroutine_context_base::align_address_size (size_t sz) inline static inherited
Definition at line 223 of file coroutine_context_base.h.
References COROUTINE_CONTEXT_BASE_ALIGN_UNIT_SIZE.
Referenced by copp::coroutine_context_container< TALLOC >::create().
align_private_data_size()
static UTIL_FORCEINLINE size_t copp::coroutine_context_base::align_private_data_size (size_t sz) inline static inherited
Definition at line 207 of file coroutine_context_base.h.
References COROUTINE_CONTEXT_BASE_ALIGN_UNIT_SIZE.
Referenced by copp::coroutine_context_container< TALLOC >::create().
align_stack_size()
static size_t copp::coroutine_context_base::align_stack_size (size_t sz) inline static inherited
Definition at line 231 of file coroutine_context_base.h.
References COROUTINE_CONTEXT_STACK_ALIGN_UNIT_SIZE, LIBCOPP_COPP_API, LIBCOPP_MACRO_NOEXCEPT, libcopp::util::swap(), unlikely, and UTIL_FORCEINLINE.
check_flags()
LIBCOPP_COPP_API bool copp::coroutine_context_base::check_flags (int flags) const inherited
check flags
Parameters
flags flags to be checked
Returns
true if flags any flags is true
Definition at line 91 of file coroutine_context.cpp.
References LIBCOPP_COPP_API, and copp::coroutine_context_base::set_runner().
Referenced by copp::this_coroutine::get_coroutine(), copp::coroutine_context::start(), and cotask::impl::task_impl::this_task().
create() [1/8]
template<typename TALLOC > static ptr_t copp::coroutine_context_container< TALLOC >::create (const callback_t & runner, allocator_type & alloc, size_t stack_sz = 0, size_t private_buffer_size = 0, size_t coroutine_size = 0) inline static
create and init coroutine with specify runner and specify stack size
Parameters
runner runner
stack_sz stack size
private_buffer_size private buffer size
coroutine_size extend buffer before coroutine
Returns
COPP_EC_SUCCESS or error code
Definition at line 73 of file coroutine_context_container.h.
References copp::coroutine_context_base::align_address_size(), copp::coroutine_context_base::align_private_data_size(), copp::coroutine_context::create(), copp::stack_traits::default_size(), libcopp::util::intrusive_ptr< T >::get(), libcopp::util::intrusive_ptr< T >::reset(), and copp::stack_context::sp.
Referenced by benchmark_round(), CASE_TEST(), copp::coroutine_context_container< TALLOC >::create(), and main().
create() [2/8]
LIBCOPP_COPP_API int copp::coroutine_context::create (coroutine_context * p, callback_t & runner, const stack_context & callee_stack, size_t coroutine_size, size_t private_buffer_size) static inherited
create coroutine context at stack context callee_
Parameters
runner runner
callee_stack stack context
coroutine_size size of coroutine object
private_buffer_size size of private buffer
Returns
COPP_EC_SUCCESS or error code
Definition at line 277 of file coroutine_context.cpp.
References copp::COPP_EC_ARGS_ERROR, copp::COPP_EC_FCONTEXT_MAKE_FAILED, copp::COPP_EC_SUCCESS, copp::fcontext::copp_make_fcontext(), copp::libcopp_inner_api_helper::coroutine_context_callback(), LIBCOPP_COPP_API, LIBCOPP_MACRO_NOEXCEPT, and copp::coroutine_context::start().
Referenced by CASE_TEST(), copp::coroutine_context_container< TALLOC >::create(), and copp::coroutine_context::create().
create() [3/8]
template<typename TRunner > static LIBCOPP_COPP_API_HEAD_ONLY int copp::coroutine_context::create (coroutine_context * p, TRunner * runner, const stack_context & callee_stack, size_t coroutine_size, size_t private_buffer_size) inline static inherited
Definition at line 95 of file coroutine_context.h.
References copp::coroutine_context::create(), LIBCOPP_COPP_API, LIBCOPP_MACRO_NOEXCEPT, copp::coroutine_context::jump_src_data_t::priv_data, copp::coroutine_context::resume(), copp::coroutine_context::start(), and copp::coroutine_context::yield().
create() [4/8]
template<typename TALLOC > template<class TRunner > static ptr_t copp::coroutine_context_container< TALLOC >::create (TRunner * runner, allocator_type & alloc, size_t stack_size = 0, size_t private_buffer_size = 0, size_t coroutine_size = 0) inline static
Definition at line 126 of file coroutine_context_container.h.
References copp::coroutine_context_container< TALLOC >::create().
create() [5/8]
template<typename TALLOC > static ptr_t copp::coroutine_context_container< TALLOC >::create (int(*)(void *) fn, allocator_type & alloc, size_t stack_size = 0, size_t private_buffer_size = 0, size_t coroutine_size = 0) inline static
Definition at line 137 of file coroutine_context_container.h.
References copp::coroutine_context_container< TALLOC >::create().
create() [6/8]
template<typename TALLOC > static ptr_t copp::coroutine_context_container< TALLOC >::create (const callback_t & runner, size_t stack_size = 0, size_t private_buffer_size = 0, size_t coroutine_size = 0) inline static
Definition at line 146 of file coroutine_context_container.h.
References copp::coroutine_context_container< TALLOC >::create().
create() [7/8]
template<typename TALLOC > template<class TRunner > static ptr_t copp::coroutine_context_container< TALLOC >::create (TRunner * runner, size_t stack_size = 0, size_t private_buffer_size = 0, size_t coroutine_size = 0) inline static
Definition at line 158 of file coroutine_context_container.h.
References copp::coroutine_context_container< TALLOC >::create().
create() [8/8]
template<typename TALLOC > static ptr_t copp::coroutine_context_container< TALLOC >::create (int(*)(void *) fn, size_t stack_size = 0, size_t private_buffer_size = 0, size_t coroutine_size = 0) inline static
Definition at line 165 of file coroutine_context_container.h.
References copp::coroutine_context_container< TALLOC >::create().
get_allocator() [1/2]
template<typename TALLOC > const allocator_type& copp::coroutine_context_container< TALLOC >::get_allocator () const inline
get stack allocator
Returns
stack allocator
Definition at line 56 of file coroutine_context_container.h.
References copp::coroutine_context_container< TALLOC >::alloc_.
get_allocator() [2/2]
template<typename TALLOC > allocator_type& copp::coroutine_context_container< TALLOC >::get_allocator () inline
get stack allocator
Returns
stack allocator
Definition at line 62 of file coroutine_context_container.h.
References copp::coroutine_context_container< TALLOC >::alloc_.
get_private_buffer()
UTIL_FORCEINLINE void* copp::coroutine_context_base::get_private_buffer () const inline inherited
get private buffer(raw pointer)
Definition at line 199 of file coroutine_context_base.h.
Referenced by cotask::impl::task_impl::this_task().
get_private_buffer_size()
UTIL_FORCEINLINE size_t copp::coroutine_context_base::get_private_buffer_size () const inline inherited
get private buffer size
Definition at line 204 of file coroutine_context_base.h.
get_ret_code()
UTIL_FORCEINLINE int copp::coroutine_context_base::get_ret_code () const inline inherited
get runner return code
Returns
Definition at line 188 of file coroutine_context_base.h.
References LIBCOPP_COPP_API, and LIBCOPP_MACRO_NOEXCEPT.
get_runner()
UTIL_FORCEINLINE const std::function<int(void *)>& copp::coroutine_context_base::get_runner () const inline inherited
get runner of this coroutine context (const)
Returns
NULL of pointer of runner
Definition at line 182 of file coroutine_context_base.h.
get_this_coroutine_base()
LIBCOPP_COPP_API coroutine_context_base * copp::coroutine_context_base::get_this_coroutine_base () static inherited
get current coroutine
See also
detail::coroutine_context_base
Returns
pointer of current coroutine, if not in coroutine, return NULL
Definition at line 117 of file coroutine_context.cpp.
References copp::detail::get_this_coroutine_context().
Referenced by cotask::impl::task_impl::this_task().
is_finished()
LIBCOPP_COPP_API bool copp::coroutine_context_base::is_finished () const inherited
get runner return code
Returns
true if coroutine has run and finished
Definition at line 112 of file coroutine_context.cpp.
References libcopp::util::lock::memory_order_acquire.
resume()
LIBCOPP_COPP_API int copp::coroutine_context::resume (void * priv_data = UTIL_CONFIG_NULLPTR) inherited
resume coroutine
Parameters
priv_data private data, will be passed to runner operator() or return to yield
Exceptions
if exception is enabled, it will throw all unhandled exception after resumed
Returns
COPP_EC_SUCCESS or error code
Definition at line 406 of file coroutine_context.cpp.
References LIBCOPP_COPP_API, and LIBCOPP_MACRO_NOEXCEPT.
Referenced by copp::coroutine_context::create().
run_and_recv_retcode()
UTIL_FORCEINLINE void copp::coroutine_context_base::run_and_recv_retcode (void * priv_data) inline protected inherited
coroutine entrance function
Definition at line 160 of file coroutine_context_base.h.
References LIBCOPP_COPP_API.
Referenced by copp::libcopp_inner_api_helper::coroutine_context_callback().
set_flags()
LIBCOPP_COPP_API bool copp::coroutine_context_base::set_flags (int flags) inherited
set all flags to true
Parameters
flags (flags & EN_CFT_MASK) must be 0
Returns
true if flags is available, or return false
Definition at line 73 of file coroutine_context.cpp.
set_runner()
LIBCOPP_COPP_API int copp::coroutine_context_base::set_runner (const callback_t & runner) inherited
set runner
Parameters
runner
Returns
COPP_EC_SUCCESS or error code
Definition at line 96 of file coroutine_context.cpp.
References copp::COPP_EC_ALREADY_INITED, copp::COPP_EC_ARGS_ERROR, copp::COPP_EC_SUCCESS, libcopp::util::lock::memory_order_acq_rel, and libcopp::util::lock::memory_order_acquire.
Referenced by copp::coroutine_context_base::check_flags().
set_this_coroutine_base()
LIBCOPP_COPP_API void copp::coroutine_context_base::set_this_coroutine_base (coroutine_context_base * ctx) static inherited
set current coroutine
See also
detail::coroutine_context_base
Parameters
ctx pointer of current coroutine, if not in coroutine, set NULL
Definition at line 121 of file coroutine_context.cpp.
References copp::detail::set_this_coroutine_context().
start()
LIBCOPP_COPP_API int copp::coroutine_context::start (void * priv_data = UTIL_CONFIG_NULLPTR) inherited
start coroutine
Parameters
priv_data private data, will be passed to runner operator() or return to yield
Exceptions
if exception is enabled, it will throw all unhandled exception after resumed
Returns
COPP_EC_SUCCESS or error code
Definition at line 339 of file coroutine_context.cpp.
References copp::coroutine_context_base::check_flags(), copp::COPP_EC_CAN_NOT_USE_CROSS_FCONTEXT_AND_FIBER, copp::COPP_EC_IS_RUNNING, copp::COPP_EC_NOT_INITED, copp::COPP_EC_NOT_READY, copp::COPP_EC_SUCCESS, copp::coroutine_context::jump_src_data_t::from_co, copp::this_coroutine::get_coroutine(), copp::detail::get_this_coroutine_context(), copp::jump_to(), libcopp::util::lock::memory_order_acq_rel, libcopp::util::lock::memory_order_acquire, libcopp::util::lock::memory_order_release, copp::coroutine_context::jump_src_data_t::priv_data, libcopp::util::swap(), copp::coroutine_context::jump_src_data_t::to_co, and unlikely.
Referenced by copp::coroutine_context::create().
unset_flags()
LIBCOPP_COPP_API bool copp::coroutine_context_base::unset_flags (int flags) inherited
set all flags to false
Parameters
flags (flags & EN_CFT_MASK) must be 0
Returns
true if flags is available, or return false
Definition at line 82 of file coroutine_context.cpp.
use_count()
template<typename TALLOC > size_t copp::coroutine_context_container< TALLOC >::use_count () const inline
Definition at line 170 of file coroutine_context_container.h.
References copp::coroutine_context_container< TALLOC >::coroutine_context_container(), libcopp::util::lock::atomic_int_type< Ty >::load(), and copp::coroutine_context_container< TALLOC >::ref_count_.
yield()
LIBCOPP_COPP_API int copp::coroutine_context::yield (void ** priv_data = UTIL_CONFIG_NULLPTR) inherited
yield coroutine
Parameters
priv_data private data, if not NULL, will get the value from start(priv_data) or resume(priv_data)
Returns
COPP_EC_SUCCESS or error code
Definition at line 413 of file coroutine_context.cpp.
References copp::COPP_EC_ALREADY_EXIST, copp::COPP_EC_NOT_INITED, copp::COPP_EC_NOT_RUNNING, copp::COPP_EC_SUCCESS, copp::COPP_EC_UNKNOWN, copp::coroutine_context::jump_src_data_t::from_co, copp::jump_to(), libcopp::util::lock::memory_order_acq_rel, libcopp::util::lock::memory_order_acquire, copp::coroutine_context::jump_src_data_t::priv_data, and copp::coroutine_context::jump_src_data_t::to_co.
Referenced by copp::libcopp_inner_api_helper::coroutine_context_callback(), copp::coroutine_context::create(), copp::this_coroutine::get(), my_runner(), my_runner::operator()(), and copp::this_coroutine::yield().
Friends And Related Function Documentation
intrusive_ptr_add_ref
template<typename TALLOC > void intrusive_ptr_add_ref (this_type * p) friend
Definition at line 176 of file coroutine_context_container.h.
intrusive_ptr_release
template<typename TALLOC > void intrusive_ptr_release (this_type * p) friend
Definition at line 184 of file coroutine_context_container.h.
Field Documentation
alloc_
template<typename TALLOC > allocator_type copp::coroutine_context_container< TALLOC >::alloc_ private
Definition at line 203 of file coroutine_context_container.h.
Referenced by copp::coroutine_context_container< TALLOC >::coroutine_context_container(), and copp::coroutine_context_container< TALLOC >::get_allocator().
callee_
fcontext::fcontext_t copp::coroutine_context::callee_ protected inherited
caller runtime context
Definition at line 60 of file coroutine_context.h.
Referenced by copp::libcopp_inner_api_helper::coroutine_context_callback(), and copp::libcopp_inner_api_helper::set_callee().
callee_stack_
stack_context copp::coroutine_context::callee_stack_ protected inherited
callee runtime context
Definition at line 62 of file coroutine_context.h.
Referenced by copp::libcopp_inner_api_helper::set_callee().
caller_
fcontext::fcontext_t copp::coroutine_context::caller_ protected inherited
Definition at line 59 of file coroutine_context.h.
Referenced by copp::libcopp_inner_api_helper::coroutine_context_callback(), and copp::libcopp_inner_api_helper::set_caller().
flags_
int copp::coroutine_context_base::flags_ protected inherited
coroutine return code
Definition at line 104 of file coroutine_context_base.h.
Referenced by copp::libcopp_inner_api_helper::coroutine_context_callback().
priv_data_
void* copp::coroutine_context_base::priv_data_ protected inherited
coroutine runner
Definition at line 106 of file coroutine_context_base.h.
private_buffer_size_
size_t copp::coroutine_context_base::private_buffer_size_ protected inherited
Definition at line 107 of file coroutine_context_base.h.
ref_count_
template<typename TALLOC > libcopp::util::lock::atomic_int_type<size_t> copp::coroutine_context_container< TALLOC >::ref_count_ private
stack allocator
Definition at line 207 of file coroutine_context_container.h.
Referenced by copp::coroutine_context_container< TALLOC >::coroutine_context_container(), and copp::coroutine_context_container< TALLOC >::use_count().
runner_
callback_t copp::coroutine_context_base::runner_ protected inherited
flags
Definition at line 105 of file coroutine_context_base.h.
runner_ret_code_
int copp::coroutine_context_base::runner_ret_code_ protected inherited
Definition at line 103 of file coroutine_context_base.h.
status_
libcopp::util::lock::atomic_int_type<int> copp::coroutine_context_base::status_ protected inherited
Definition at line 112 of file coroutine_context_base.h.
The documentation for this class was generated from the following file:
/home/travis/build/owt5008137/libcopp/include/libcopp/coroutine/coroutine_context_container.h