libcopp: copp::util::uint64_id_allocator Class Reference
copp::util::uint64_id_allocator Class Reference
#include <uint64_id_allocator.h>
Public Types
typedef uint64_t value_type
Static Public Member Functions
static value_type allocate () LIBCOPP_MACRO_NOEXCEPT
static void deallocate (value_type) LIBCOPP_MACRO_NOEXCEPT
Static Public Attributes
static const value_type npos = 0
Detailed Description
Definition at line 22 of file uint64_id_allocator.h.
Member Typedef Documentation
value_type
typedef uint64_t copp::util::uint64_id_allocator::value_type
Definition at line 27 of file uint64_id_allocator.h.
Member Function Documentation
allocate()
LIBCOPP_COPP_API uint64_id_allocator::value_type copp::util::uint64_id_allocator::allocate () static
invalid key
Definition at line 109 of file uint64_id_allocator.cpp.
References copp::util::details::allocate_id_by_atomic(), copp::util::details::uint64_id_allocator_tls_cache_t::base, copp::util::details::get_uint64_id_allocator_tls_cache(), and copp::util::details::uint64_id_allocator_tls_cache_t::inner_seq.
Referenced by CASE_TEST(), and cotask::impl::task_impl::task_impl().
deallocate()
LIBCOPP_COPP_API void copp::util::uint64_id_allocator::deallocate (value_type) static
Definition at line 130 of file uint64_id_allocator.cpp.
Referenced by cotask::impl::task_impl::~task_impl().
Field Documentation
npos
const value_type copp::util::uint64_id_allocator::npos = 0 static
Definition at line 33 of file uint64_id_allocator.h.
The documentation for this class was generated from the following files:
/home/travis/build/owt5008137/libcopp/include/libcopp/utils/uint64_id_allocator.h
/home/travis/build/owt5008137/libcopp/src/libcopp/utils/uint64_id_allocator.cpp