libcopp: copp::this_coroutine Namespace Reference
copp::this_coroutine Namespace Reference
Functions
LIBCOPP_COPP_API coroutine_context * get_coroutine () LIBCOPP_MACRO_NOEXCEPT
get current coroutine
template<typename Tc >
LIBCOPP_COPP_API_HEAD_ONLY Tc * get ()
get current coroutine and try to convert type
LIBCOPP_COPP_API int yield (void **priv_data=UTIL_CONFIG_NULLPTR) LIBCOPP_MACRO_NOEXCEPT
yield current coroutine
Function Documentation
get()
template<typename Tc > LIBCOPP_COPP_API_HEAD_ONLY Tc* copp::this_coroutine::get ()
get current coroutine and try to convert type
See also
get_coroutine
detail::coroutine_context
Returns
pointer of current coroutine, if not in coroutine or fail to convert type, return NULL
Definition at line 161 of file coroutine_context.h.
References get_coroutine(), LIBCOPP_COPP_API, LIBCOPP_MACRO_NOEXCEPT, copp::coroutine_context::jump_src_data_t::priv_data, and copp::coroutine_context::yield().
get_coroutine()
LIBCOPP_COPP_API coroutine_context * copp::this_coroutine::get_coroutine ()
get current coroutine
See also
detail::coroutine_context
Returns
pointer of current coroutine, if not in coroutine, return NULL
Definition at line 458 of file coroutine_context.cpp.
References copp::coroutine_context_base::check_flags(), copp::coroutine_context_base::flag_t::EN_CFT_IS_FIBER, and copp::detail::get_this_coroutine_context().
Referenced by get(), my_runner(), copp::coroutine_context::start(), and yield().
yield()
LIBCOPP_COPP_API int copp::this_coroutine::yield (void ** priv_data = UTIL_CONFIG_NULLPTR)
yield current coroutine
Parameters
priv_data private data, if not NULL, will get the value from start(priv_data) or resume(priv_data)
Returns
0 or error code
Definition at line 468 of file coroutine_context.cpp.
References copp::COPP_EC_NOT_RUNNING, get_coroutine(), copp::detail::get_this_coroutine_context(), likely, and copp::coroutine_context::yield().
Referenced by cotask::task< TCO_MACRO >::await_task(), cotask::impl::task_impl::get_status(), my_runner(), test_context_private_data_foo_runner::operator()(), and test_context_base_foo_runner::operator()().