libcopp: util::cli::shell_font Class Reference
util::cli::shell_font Class Reference
#include <shell_font.h>
Public Member Functions
shell_font (int iFlag=0)
virtual ~shell_font ()
std::string GenerateString (const std::string &strInput)
std::string GetStyleCode ()
Static Public Member Functions
static std::string GenerateString (const std::string &strInput, int iFlag)
static std::string GetStyleCode (int iFlag)
static std::string GetStyleCloseCode ()
Private Attributes
int m_iFlag
Detailed Description
Definition at line 106 of file shell_font.h.
Constructor & Destructor Documentation
shell_font()
util::cli::shell_font::shell_font (int iFlag = 0)
字体信息
Parameters
iFlag
Definition at line 31 of file shell_font.cpp.
~shell_font()
util::cli::shell_font::~shell_font () virtual
Definition at line 33 of file shell_font.cpp.
Member Function Documentation
GenerateString() [1/2]
std::string util::cli::shell_font::GenerateString (const std::string & strInput)
生成带样式的文本
Parameters
[in] strInput 原始文本
Returns
生成带样式的文本
Definition at line 179 of file shell_font.cpp.
References m_iFlag.
GenerateString() [2/2]
std::string util::cli::shell_font::GenerateString (const std::string & strInput, int iFlag) static
生成带样式的文本
Parameters
[in] strInput 原始文本
[in] iFlag 样式
Returns
生成带样式的文本
Definition at line 168 of file shell_font.cpp.
References util::cli::_check_term_color_status(), GetStyleCloseCode(), and GetStyleCode().
GetStyleCloseCode()
std::string util::cli::shell_font::GetStyleCloseCode () static
获取样式的关闭命令
Returns
样式的关闭命令
Definition at line 90 of file shell_font.cpp.
References SHELL_FONT_SET_OPT_END.
Referenced by GenerateString(), and util::cli::shell_stream::shell_stream_opr::reset().
GetStyleCode() [1/2]
std::string util::cli::shell_font::GetStyleCode ()
获取样式的生成命令
Returns
样式的生成命令
Definition at line 88 of file shell_font.cpp.
References m_iFlag.
Referenced by util::cli::shell_stream::shell_stream_opr::close(), and GenerateString().
GetStyleCode() [2/2]
std::string util::cli::shell_font::GetStyleCode (int iFlag) static
获取样式的生成命令
Parameters
[in] iFlag 样式
Returns
样式的生成命令
Definition at line 35 of file shell_font.cpp.
References util::cli::shell_font_style::SHELL_FONT_SPEC_BOLD, util::cli::shell_font_style::SHELL_FONT_SPEC_DARK, util::cli::shell_font_style::SHELL_FONT_SPEC_FLASH, and util::cli::shell_font_style::SHELL_FONT_SPEC_UNDERLINE.
Field Documentation
m_iFlag
int util::cli::shell_font::m_iFlag private
Definition at line 108 of file shell_font.h.
Referenced by GenerateString(), and GetStyleCode().
The documentation for this class was generated from the following files:
/home/runner/work/libcopp/libcopp/test/cli/shell_font.h
/home/runner/work/libcopp/libcopp/test/cli/shell_font.cpp