libcopp: cotask::task_action_functor< Ty > Class Template Reference
cotask::task_action_functor< Ty > Class Template Reference
#include <task_actions.h>
Public Types
typedef Ty value_type
Public Member Functions
task_action_functor (const value_type &functor)
~task_action_functor ()
virtual int operator() (void *priv_data)
virtual int on_finished (task_impl &)
Static Public Member Functions
static void placement_destroy (void *selfp)
Private Attributes
value_type functor_
Detailed Description
template<typename Ty>
class cotask::task_action_functor< Ty >
Definition at line 74 of file task_actions.h.
Member Typedef Documentation
value_type
template<typename Ty > typedef Ty cotask::task_action_functor< Ty >::value_type
Definition at line 102 of file task_actions.h.
Constructor & Destructor Documentation
task_action_functor()
template<typename Ty > cotask::task_action_functor< Ty >::task_action_functor (const value_type & functor) inline
Definition at line 103 of file task_actions.h.
~task_action_functor()
template<typename Ty > cotask::task_action_functor< Ty >::~task_action_functor () inline
Definition at line 105 of file task_actions.h.
Referenced by cotask::task_action_functor< Ty >::placement_destroy().
Member Function Documentation
on_finished()
virtual int cotask::impl::task_action_impl::on_finished (task_impl &) inline virtual inherited
Definition at line 38 of file task_action_impl.h.
operator()()
template<typename Ty > virtual int cotask::task_action_functor< Ty >::operator() (void * priv_data) inline virtual
Implements cotask::impl::task_action_impl.
Definition at line 106 of file task_actions.h.
References cotask::detail::task_action_functor_check::call().
placement_destroy()
template<typename Ty > static void cotask::task_action_functor< Ty >::placement_destroy (void * selfp) inline static
Definition at line 110 of file task_actions.h.
References cotask::task_action_functor< Ty >::~task_action_functor().
Field Documentation
functor_
template<typename Ty > value_type cotask::task_action_functor< Ty >::functor_ private
Definition at line 120 of file task_actions.h.
The documentation for this class was generated from the following file:
/home/runner/work/libcopp/libcopp/include/libcotask/task_actions.h